/* 游戏目录清单 —— 加新游戏只需在这里加一项 + 把 HTML 放进 games/ 目录。
   字段: file 路径 | emoji 图标 | name 名称 | desc 一句话 | tags 标签(用于搜索/分类) */
window.GAMES = [
  {
    file: "games/english.html",
    emoji: "🔵",
    name: "珠珠学习乐园",
    desc: "人教PEP三到六年级英语，36条3D路线、沿途10题、美式发音和33款珠珠皮肤",
    tags: ["英语", "学习", "3D", "皮肤", "手机"],
  },
  {
    file: "games/rescue.html?v=20261003rescue-online3",
    emoji: "🐿️",
    name: "松鼠大作战",
    desc: "11个经典区域的3D横版重制，举箱子、扔队友，本机 / 联网双人救援",
    tags: ["经典", "3D", "本机双人", "联网双人", "手柄", "闯关"],
  },
  {
    file: "games/parkour.html",
    emoji: "🌸",
    name: "微光跑酷",
    desc: "12关自由移动3D跑酷，穿过樱花、花林、城市与木屋，还能自创路线",
    tags: ["跑酷", "3D", "闯关", "手机"],
  },
  {
    file: "games/racing.html",
    emoji: "🏎️",
    name: "峰谷竞速",
    desc: "十四张3D赛道穿越山海、霓虹与云端，与十位车手竞速赢取车库奖金",
    tags: ["赛车", "3D", "皮肤", "手机"],
  },
  {
    file: "games/territory.html",
    emoji: "🟥",
    name: "纸片领地",
    desc: "驾驶折角小纸片，在纸艺岛屿闭合圈地，收集60款纸片",
    tags: ["圈地", "策略", "皮肤", "手机"],
  },
  {
    file: "games/shooter.html",
    emoji: "🛸",
    name: "星际小队",
    desc: "16人联网合作，200大关×50小关，随机抽卡与百道扩散",
    tags: ["射击", "闯关", "手机", "升级"],
  },
  {
    file: "games/pinyin.html",
    emoji: "🚀",
    name: "拼音打字小火箭",
    desc: "看拼音敲字母，把汉字宝宝送上太空，练键盘指法",
    tags: ["键盘", "拼音", "识字"],
  },
  {
    file: "games/snake.html",
    emoji: "🐍",
    name: "贪吃蛇吃痘痘",
    desc: "经典贪吃蛇，方向键控制，越吃越长别撞墙",
    tags: ["反应", "经典"],
  },
  {
    file: "games/fish.html",
    emoji: "🐟",
    name: "大鱼吃小鱼",
    desc: "吃掉比自己小的鱼，慢慢长成海里最大的鱼",
    tags: ["休闲", "成长"],
  },
  {
    file: "games/fishing.html",
    emoji: "🎣",
    name: "捕鱼达人",
    desc: "点击发射炮弹打鱼，鱼越大金币越多，升级炮台火力更猛",
    tags: ["射击", "金币", "休闲"],
  },
  {
    file: "games/goldminer.html",
    emoji: "⛏️",
    name: "黄金矿工",
    desc: "西部矿井有几块矿物就发几钩，收集金币、补给炸药、挑战下一关",
    tags: ["经典", "金币", "反应", "手机"],
  },
  {
    file: "games/maze.html",
    emoji: "👑",
    name: "皇冠迷宫",
    desc: "集齐死角钥匙，穿越十九座华丽宫殿，还有金币奖励迷宫",
    tags: ["迷宫", "闯关", "金币", "手机"],
  },
  {
    file: "games/merge4096.html",
    emoji: "🎼",
    name: "合成4096",
    desc: "抽数字牌叠进五列，连锁合成4096，伴着卡农挑战通关",
    tags: ["合成", "数字", "卡牌", "音乐", "金币"],
  },
];
