import test from 'node:test';
import assert from 'node:assert/strict';
import {createCourseCloud,profileStorageKey,guestStorageKey} from '../english/course-cloud.js';
const empty=()=>({version:1,lessons:{},items:{},session:null});
const storage=()=>{const map=new Map();return {getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)}};
function fixture(request){const store=storage(),changes=[];const course={value:empty(),key:guestStorageKey,home(){},save(){},snapshot(){return structuredClone(this.value)},replaceProgress(p,{storageKey}){this.value=structuredClone(p);this.key=storageKey;changes.push(storageKey)}};let id=0;const cloud=createCourseCloud({course,storage:store,request,uuid:()=>`00000000-0000-4000-8000-${String(++id).padStart(12,'0')}`,debounceMs:999999});return {store,course,cloud,changes};}
const answer={contentId:'pep3-2024-u1-l1',kind:'answer',result:{itemKey:'word:test',correct:true,hinted:false}};
test('loads remote before accepting child saves and restores guest on logout',async()=>{let release;const f=fixture(()=>new Promise(r=>release=r));f.store.setItem(guestStorageKey,JSON.stringify(empty()));const loading=f.cloud.select('parent-a',{id:'child-a'});f.cloud.onSave({progress:empty(),event:answer});assert.equal(f.cloud.pending.length,0);release({revision:2,data:empty()});await loading;assert.equal(f.course.key,profileStorageKey('parent-a','child-a'));await f.cloud.logout();assert.equal(f.course.key,guestStorageKey);assert.equal(f.cloud.owner,null);});
test('offline and conflicting requests preserve pending event IDs across recreation',async()=>{let mode='load',payload;const f=fixture(async(path,options)=>{if(mode==='load')return {revision:0,data:empty()};payload=options.body;if(mode==='offline')throw new TypeError('offline');const error=new Error('conflict');error.status=409;error.data={current:{revision:3,data:empty()}};throw error;});await f.cloud.select('parent-a',{id:'child-a'});f.cloud.onSave({progress:{...empty(),session:{lessonId:'local',index:4}},event:answer});mode='offline';await f.cloud.flush();const id=f.cloud.pending[0].eventId;assert.equal(f.cloud.status,'离线待同步');mode='conflict';await f.cloud.flush();assert.equal(f.cloud.status,'需选择进度');assert.equal(f.cloud.pending[0].eventId,id);assert.equal(payload.baseRevision,0);assert.equal(f.cloud.conflict.local.session.index,4);assert.equal(JSON.parse(f.store.getItem(`${profileStorageKey('parent-a','child-a')}:sync`)).events[0].eventId,id);});
test('choosing cloud session retries all pending events at current revision',async()=>{let mode='load',sent;const f=fixture(async(path,options)=>{if(mode==='load')return {revision:0,data:empty()};sent=options.body;if(mode==='conflict'){const e=new Error('conflict');e.status=409;e.data={current:{revision:9,data:{...empty(),session:{lessonId:'remote',index:7}}}};throw e;}return {revision:10,data:{...empty(),session:sent.session}}});await f.cloud.select('a',{id:'c'});f.cloud.onSave({progress:{...empty(),session:{lessonId:'local',index:2}},event:answer});mode='conflict';await f.cloud.flush();mode='ok';await f.cloud.resolveConflict('cloud');assert.equal(sent.baseRevision,9);assert.equal(sent.session.lessonId,'remote');assert.equal(sent.events.length,1);assert.equal(f.cloud.pending.length,0);assert.equal(f.cloud.status,'已同步');});
test('limits batches to 256 and retains concurrent saves until another successful upload',async()=>{let cloud,post=0;const f=fixture(async(path,options)=>{if(!options)return {revision:0,data:empty()};assert.ok(options.body.events.length<=256);post++;if(post===1)cloud.onSave({progress:empty(),event:answer});return {revision:post,data:empty()}});cloud=f.cloud;await cloud.select('a',{id:'c'});for(let i=0;i<257;i++)cloud.onSave({progress:empty(),event:answer});await cloud.flush();assert.equal(post,2);assert.equal(cloud.pending.length,0);});
test('offline child load requires its previously authenticated cache and keeps guest copy',async()=>{let offline=false;const f=fixture(async()=>{if(offline)throw new TypeError('offline');return {revision:0,data:empty()}});f.store.setItem(guestStorageKey,JSON.stringify({...empty(),session:{lessonId:'guest',index:2}}));await f.cloud.select('a',{id:'c'});offline=true;await f.cloud.select('a',{id:'c'});assert.equal(f.cloud.status,'离线待同步');await assert.rejects(f.cloud.select('b',{id:'c'}),/offline/);assert.equal(f.course.key,guestStorageKey);assert.equal(JSON.parse(f.store.getItem(guestStorageKey)).session.lessonId,'guest');});
test('guest import retains stable source ID and never erases original copy',async()=>{let imports=[];const f=fixture(async(path,options)=>{if(path.endsWith('/import')){imports.push(options.body);return {revision:1,data:options.body.data}}return {revision:0,data:empty()}});const guest=JSON.stringify(empty());f.store.setItem(guestStorageKey,guest);await f.cloud.select('a',{id:'c'});await f.cloud.importGuest();await f.cloud.importGuest();assert.equal(imports[0].sourceId,imports[1].sourceId);assert.equal(f.store.getItem(guestStorageKey),guest);});
test('logout during upload cannot put a delayed cloud response into the guest save',async()=>{let resolve,mode='load';const f=fixture(async()=>mode==='load'?{revision:0,data:empty()}:new Promise(r=>resolve=r));const guest=JSON.stringify({...empty(),session:{lessonId:'guest',index:3}});f.store.setItem(guestStorageKey,guest);await f.cloud.select('a',{id:'c'});f.cloud.onSave({progress:empty(),event:answer});mode='upload';const uploading=f.cloud.flush();await f.cloud.logout();resolve({revision:1,data:{...empty(),session:{lessonId:'cloud',index:9}}});await uploading;assert.equal(f.course.key,guestStorageKey);assert.equal(f.course.value.session.lessonId,'guest');assert.equal(f.store.getItem(guestStorageKey),guest);assert.equal(f.cloud.owner,null);});
test('completion events omit reconstructable steps and batches stay below body size limit',async()=>{let uploaded=[];const f=fixture(async(path,options)=>{if(!options)return {revision:0,data:empty()};uploaded.push(options.body);assert.ok(new TextEncoder().encode(JSON.stringify(options.body)).length<512*1024);return {revision:uploaded.length,data:empty()}});await f.cloud.select('a',{id:'c'});const completed={lessonId:'l',index:4,startedAt:1,completedAt:2,steps:[{huge:'x'.repeat(20000)}],answers:{}};for(let i=0;i<30;i++)f.cloud.onSave({progress:{...empty(),session:completed},event:{kind:'completion',contentId:'l',result:{session:completed}}});await f.cloud.flush();assert.equal(uploaded.flatMap(b=>b.events).length,30);assert.equal(uploaded[0].session.steps,undefined);assert.equal(uploaded[0].events[0].result.session.steps,undefined);assert.equal(uploaded[0].events[0].result.session.index,4);});
