import test from 'node:test';
import assert from 'node:assert/strict';
import {mountCourse} from '../english/course-ui.js';
import {LESSONS} from '../english/course-curriculum.js';
import {createSession} from '../english/course-engine.js';
function mount(){let handler;const map=new Map(),events=[];globalThis.localStorage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)};globalThis.window={};globalThis.addEventListener=()=>{};const root={innerHTML:'',addEventListener(type,fn){handler=fn},scrollIntoView(){}};const course=mountCourse({root,speak(){},read(){},stopAudio(){},openPages(){},onReward(){},notice(){},onSave:payload=>events.push(payload)});return {course,map,events,click:button=>handler({target:{closest:()=>button}})}}
test('first answer emits once, correct retry preserves first result',()=>{const {course,events,click}=mount();course.start(LESSONS[0].id);const quiz=course.session.steps.findIndex(s=>s.kind==='listen');course.session.index=quiz;const step=course.session.steps[quiz],wrong=step.choices.find(x=>x!==step.answer);click({dataset:{courseAnswer:wrong}});click({dataset:{courseAnswer:step.answer}});const answers=events.filter(x=>x.event?.kind==='answer');assert.equal(answers.length,1);assert.equal(answers[0].event.result.correct,false);assert.equal(answers[0].event.result.itemKey,step.itemKey);assert.equal(course.session.feedback.correct,true)});
test('completion callback includes final session before clearing live session',()=>{const {course,events,click}=mount();const session=createSession(LESSONS[0]);session.index=session.steps.length-1;session.answers[session.steps.at(-1).id]={selfReported:true};course.replaceProgress({version:1,lessons:{},items:{},session},{storageKey:'child-owned'});course.start();click({id:'courseNext',dataset:{}});const completion=events.filter(x=>x.event?.kind==='completion');assert.equal(completion.length,1);assert.equal(completion[0].event.result.session.index,session.steps.length);assert.ok(completion[0].event.result.session.completedAt);assert.equal(completion[0].progress.session,null);assert.equal(course.session,null)});
test('replacing child progress and returning home never writes under guest key',()=>{const {course,map}=mount();const guest={version:1,lessons:{},items:{},session:createSession(LESSONS[1])};map.set('pearl-english-course-v1',JSON.stringify(guest));course.replaceProgress({version:1,lessons:{},items:{},session:null},{storageKey:'owner-child'});course.start(LESSONS[0].id);course.home();course.save();assert.equal(JSON.parse(map.get('pearl-english-course-v1')).session.lessonId,LESSONS[1].id);assert.equal(JSON.parse(map.get('owner-child')).session.lessonId,LESSONS[0].id);assert.equal(course.snapshot().session.lessonId,LESSONS[0].id)});
