import test from 'node:test';
import assert from 'node:assert/strict';
import {openBrowser,sleep} from './game-browser-harness.mjs';
import {LESSONS} from '../math/curriculum.js';
async function tap(b,selector,touch=true){await b.evaluate(`document.querySelector(${JSON.stringify(selector)})?.scrollIntoView({block:'center'})`);const r=await b.evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)return null;const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);assert.ok(r,selector);if(touch){await b.call('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[r]});await b.call('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else{await b.call('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...r});await b.call('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...r});}await sleep(70);}
async function fill(b,selector,value){await tap(b,selector);await b.call('Input.dispatchKeyEvent',{type:'keyDown',key:'a',code:'KeyA',windowsVirtualKeyCode:65,modifiers:2});await b.call('Input.dispatchKeyEvent',{type:'keyUp',key:'a',code:'KeyA',windowsVirtualKeyCode:65,modifiers:2});await b.call('Input.insertText',{text:String(value)});await b.call('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await b.call('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await sleep(80);}
async function explore(b,type){const l=LESSONS.find(l=>l.steps.some(s=>s.kind==='explore'&&s.widget?.type===type));await b.navigate('games/math.html');await tap(b,'#mathDirectory');await tap(b,`[data-lesson="${l.id}"]`);for(let i=0;i<20;i++){if(await b.evaluate(`document.querySelector('[data-widget="${type}"]')!==null`))return;await tap(b,'#mathNext');}throw Error(type);}
test('native controls change exact figures; rigid fold animation pauses and resumes',{timeout:60000},async()=>{const b=await openBrowser();try{await b.size(390,844,true);await explore(b,'net');await tap(b,'[data-widget-set="fold"]');await sleep(200);await tap(b,'#mathNetPause');const frozen=await b.evaluate('document.querySelector(".math-net-frame").innerHTML');await sleep(300);assert.equal(await b.evaluate('document.querySelector(".math-net-frame").innerHTML'),frozen);await tap(b,'#mathNetPause');await sleep(1900);assert.match(await b.evaluate('document.querySelector(".math-net-frame svg").getAttribute("aria-label")'),/100%/);
 await explore(b,'multiply');await fill(b,'[data-widget-field="a"]',268);await fill(b,'[data-widget-field="b"]',4);await tap(b,'[data-widget-set="revealed"]');assert.equal(await b.evaluate('document.querySelector(".math-carry-row").textContent.replaceAll("\u00a0"," ")'),'  3 ');assert.match(await b.evaluate('document.querySelector(".math-vertical").textContent'),/2/);
 await explore(b,'angle');await tap(b,'[data-widget-set="degrees"]');assert.match(await b.evaluate('document.querySelector(".math-widget svg").getAttribute("aria-label")'),/90度/);for(let i=0;i<8;i++)await tap(b,'[data-widget-set="rotation"]');assert.ok(await b.evaluate('document.documentElement.scrollWidth<=innerWidth+1'));
 await explore(b,'fraction');const before=await b.evaluate('document.querySelector(".math-widget-result").textContent');await tap(b,'[data-widget-paint="0"]');assert.notEqual(await b.evaluate('document.querySelector(".math-widget-result").textContent'),before);
 await explore(b,'groups');await fill(b,'[data-widget-field="total"]',12);assert.match(await b.evaluate('document.querySelector(".math-widget-result").textContent'),/12 ÷/);
 await explore(b,'match');await fill(b,'[data-widget-field="tops"]',3);await tap(b,'[data-widget-set="selected"]');assert.match(await b.evaluate('document.querySelector(".math-widget-result").textContent'),/已找到 1/);
 assert.deepEqual(b.errors,[]);}finally{b.close()}});
test('all 39 lessons complete through native choices and free inputs, then survive reload',{timeout:240000},async()=>{const b=await openBrowser();try{await b.size(390,844,true);await b.navigate('games/math.html');for(const l of LESSONS){await tap(b,'#mathDirectory');await tap(b,`[data-lesson="${l.id}"]`);for(let n=0;n<30;n++){if(await b.evaluate('!!document.querySelector(".math-finish")'))break;const s=await b.evaluate('mathCourse.session.steps[mathCourse.session.index]');if(s.itemKey){if(s.choices)await tap(b,`[data-answer="${s.choices.indexOf(s.answer)}"]`);else{await fill(b,'#mathAnswer',s.answer);await tap(b,'#mathAnswerForm button');}}await tap(b,'#mathNext');}assert.equal(await b.evaluate(`mathCourse.progress.lessons[${JSON.stringify(l.id)}]?.completed`),true,l.id);await tap(b,'#mathHome');}await b.navigate('games/math.html');assert.equal(await b.evaluate('Object.values(mathCourse.progress.lessons).filter(l=>l.completed).length'),39);assert.deepEqual(b.errors,[]);}finally{b.close()}});
test('math entry is usable at five sizes and every lesson can be reached through native directory',{timeout:60000},async()=>{const b=await openBrowser();try{for(const [w,h] of [[320,568],[390,844],[768,1024],[1024,768],[1366,900]]){await b.size(w,h,w<=1024);await b.navigate('games/math.html');assert.ok(await b.evaluate('!!document.querySelector("#startMath")'));await tap(b,'#mathDirectory',w<=1024);assert.ok(await b.evaluate('document.querySelectorAll("[data-lesson]").length>=32'));assert.ok(await b.evaluate('document.documentElement.scrollWidth<=innerWidth+1'));await tap(b,'#closeDirectory',w<=1024);}assert.deepEqual(b.errors,[]);}finally{b.close()}});
test('native wrong answer, persisted hint, retry and refresh preserve a true first attempt',{timeout:60000},async()=>{const b=await openBrowser();try{await b.size(390,844,true);await b.navigate('games/math.html');await tap(b,'#startMath');for(let i=0;i<30;i++){if(await b.evaluate('!!mathCourse.session.steps[mathCourse.session.index].itemKey'))break;await tap(b,'#mathNext');}const wrong=await b.evaluate('(()=>{const s=mathCourse.session.steps[mathCourse.session.index];return s.choices?.findIndex(c=>c!==s.answer)??-1})()');assert.ok(wrong>=0);await tap(b,`[data-answer="${wrong}"]`);assert.ok(await b.evaluate('document.querySelector("#mathNext").disabled'));await tap(b,'#mathHint');await tap(b,'#mathHint');const correct=await b.evaluate('(()=>{const s=mathCourse.session.steps[mathCourse.session.index];return s.choices.indexOf(s.answer)})()');await tap(b,`[data-answer="${correct}"]`);assert.deepEqual(await b.evaluate('(()=>{const a=mathCourse.session.answers[mathCourse.session.steps[mathCourse.session.index].id];return [a.correct,a.latest.correct,a.latest.hinted]})()'),[false,true,true]);await tap(b,'[data-subject="english"]');for(let i=0;i<100;i++){if(await b.evaluate('!!window.englishCourse'))break;await sleep(60);}await tap(b,'[data-subject="math"]');for(let i=0;i<100;i++){if(await b.evaluate('!!window.mathCourse'))break;await sleep(60);}await tap(b,'#startMath');assert.deepEqual(await b.evaluate('(()=>{const a=mathCourse.session.answers[mathCourse.session.steps[mathCourse.session.index].id];return [a.correct,a.latest.correct,a.latest.hinted]})()'),[false,true,true]);assert.deepEqual(b.errors,[]);}finally{b.close()}});
