import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync,chmodSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {normalizeEvent} from '../platform/english-progress.mjs';
const require=createRequire(import.meta.url);
const {createClient}=require('../miniprogram/lib/client.js');
const root=new URL('../',import.meta.url);
const copy=x=>JSON.parse(JSON.stringify(x));
function harness(route,sharedStorage=new Map()){let definition;const storage=sharedStorage,requests=[],audios=[],scrolls=[];let recorder;
 const wx={getStorageSync:k=>storage.get(k),setStorageSync:(k,v)=>storage.set(k,copy(v)),removeStorageSync:k=>storage.delete(k),request:o=>{if(o.url.includes('/english/miniprogram-data/')){const path=o.url.split('/english/miniprogram-data/')[1];o.success({statusCode:200,data:JSON.parse(readFileSync(new URL('english/miniprogram-data/'+path,root)))})}else{requests.push(o)}return{abort(){o.aborted=true}}},createInnerAudioContext(){const a={play(){},stop(){a.stopped=true},destroy(){a.destroyed=true},onEnded:f=>a.ended=f,onError:f=>a.error=f};audios.push(a);return a},getRecorderManager(){return recorder??={onStart:f=>recorder.started=f,onStop:f=>recorder.stopped=f,onError:f=>recorder.error=f,offStart(){},offStop(){},offError(){},start(options){recorder.options=options;recorder.started()},stop(){recorder.stopCalled=true}}},requirePrivacyAuthorize:o=>o.success(),authorize:o=>o.success(),getFileSystemManager:()=>({unlink:o=>storage.set('deleted:'+o.filePath,true),readFile:o=>o.success({data:new ArrayBuffer(44)})}),pageScrollTo:o=>scrolls.push(o),navigateTo(){},navigateBack(){},openSetting(){},openPrivacyContract(){}};
 const client=createClient(wx),file=new URL('miniprogram/pages/'+route+'/'+route+'.js',root);vm.runInNewContext(readFileSync(file,'utf8'),{Page:d=>definition=d,require:createRequire(file),wx,getApp:()=>({client}),console,Date,Set,Number,JSON});const page={...definition,data:copy(definition.data),setData(update){Object.assign(this.data,copy(update))}};return{page,client,wx,storage,requests,audios,scrolls,get recorder(){return recorder}};
}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const event=data=>({currentTarget:{dataset:data}});
test('native lesson source answer retry preserves first incorrect answer and cannot skip quiz',async()=>{const h=harness('lesson');h.page.onLoad({id:'g3-upper-u1-l1'});await tick();assert.equal(h.page.data.loading,false);while(!['listen','meaning','sentence','check'].includes(h.page.data.step.kind))h.page.next();const step=h.page.data.step,index=h.page.session.index;h.page.next();assert.equal(h.page.session.index,index);const wrong=step.choices.find(x=>x!==step.answer);h.page.answer(event({answer:wrong}));assert.equal(h.page.data.feedback.correct,false);h.page.answer(event({answer:step.answer}));assert.equal(h.page.data.feedback.correct,true);assert.equal(h.page.session.answers[step.id].correct,false);assert.equal(h.page.progress.items[step.itemKey].incorrect,1);assert.equal(h.page.progress.items[step.itemKey].correct,0);h.page.next();assert.equal(h.page.session.index,index+1)});
test('page controls play sequential real media and hide cancels queued callback',async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();h.page.readPage();assert.equal(h.page.data.media.playing,true);const first=h.audios[0];assert.ok(first.src.startsWith('https://games.nblord.com/english/audio/'));first.ended();assert.equal(h.audios.length,2);h.page.onHide();h.audios[1].ended();assert.equal(h.audios.length,2);assert.equal(h.page.data.media.playing,false)});
test('native stop button cancels sequence without later restarting playback',async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();h.page.readPage();h.page.stopAudio();h.audios[0].ended();assert.equal(h.audios.length,1);assert.equal(h.page.data.media.playing,false)});
test('page answer retries record one first answer and display-only target cannot record',async()=>{const h=harness('page');h.page.onLoad({page:57});await tick();const q=h.page.data.question;h.page.answer(event({answer:q.choices.find(x=>x!==q.answer)}));h.page.answer(event({answer:q.answer}));assert.equal(h.page.data.feedback.correct,true);assert.equal(h.client.pageHistory(57)[q.id].attempts,1);assert.equal(h.client.pageHistory(57)[q.id].correct,0);const silent=h.page.targets.find(t=>t.id==='p57-line-2-3');assert.equal(silent.speakable,false);h.page.chooseTarget(event({id:silent.id}));assert.equal(h.page.data.speakingTarget,null);assert.ok(!h.page.questions.some(q=>q.targetId===silent.id))});
test('recording prevents page, tab and target changes until explicit discard',async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();const target=h.page.targets.find(t=>t.audio);h.page.chooseAndSpeak(event({id:target.id}));await h.page.record();h.page.changePage(event({delta:1}));h.page.switchTab(event({tab:'read'}));h.page.chooseTarget(event({id:h.page.targets[1].id}));assert.equal(h.page.pageNumber,2);assert.equal(h.page.data.tab,'speak');assert.equal(h.page.data.speakingTarget.id,target.id);assert.equal(h.page.data.media.recording,true);h.page.cancelRecording();h.recorder.stopped({tempFilePath:'/temp/stale.wav',duration:1000});h.page.changePage(event({delta:1}));await tick();assert.equal(h.storage.get('deleted:/temp/stale.wav'),true);assert.equal(h.page.data.page.page,3)});
test('native account input and failed login clear password and busy state',async()=>{const h=harness('account');h.page.onLoad();h.page.input({currentTarget:{dataset:{key:'username'}},detail:{value:'parent'}});h.page.input({currentTarget:{dataset:{key:'password'}},detail:{value:'wrong'}});const action=h.page.usernameLogin();h.requests[0].success({statusCode:401,data:{error:'bad credentials'}});await action;assert.equal(h.page.data.password,'');assert.equal(h.page.data.busy,false);assert.ok(h.page.data.error)});
test('returning to open lesson after child switch reloads and never saves the old child session',async()=>{const h=harness('lesson');h.page.onLoad({id:'g3-upper-u1-l1'});await tick();h.page.next();const oldIndex=h.page.session.index;h.page.onHide();const saved={version:1,lessons:{},items:{},session:null};let writes=0;Object.defineProperty(h.client,'identity',{get:()=> 'new-child'});h.client.progress=()=>copy(saved);h.client.saveProgress=data=>{writes++;assert.ok(data.session.index===0)};h.page.onShow();await tick();assert.equal(h.page.session.index,0);assert.ok(oldIndex>0);assert.ok(writes>0)});
test('replay uses local file path and delayed stop after unload deletes a clip',async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();h.page.chooseAndSpeak(event({id:h.page.targets[0].id}));await h.page.record();h.page.stopRecord();h.recorder.stopped({tempFilePath:'wxfile://temp/current.wav',duration:1000});h.page.replay();assert.equal(h.audios[0].src,'wxfile://temp/current.wav');await h.page.record();h.page.onUnload();h.recorder.stopped({tempFilePath:'wxfile://temp/late.wav',duration:1000});assert.equal(h.storage.get('deleted:wxfile://temp/late.wav'),true)});
test('logout network failure still returns account view to visitor',async()=>{const h=harness('account');h.page.onLoad();h.storage.set('mini-session-v1',{token:'session',user:{id:'parent'}});h.client.restore();h.page.setData({user:h.client.user});const exiting=h.page.logout();h.requests[0].fail();await exiting;assert.equal(h.client.user,null);assert.equal(h.page.data.user,null)});
test('app restart revalidates bearer session before restoring selected child',async()=>{const h=harness('home');h.storage.set('mini-session-v1',{token:'token',user:{id:'owner'}});h.storage.set('mini-profile-v1:owner',{id:'child',nickname:'小豆'});let app;const file=new URL('miniprogram/app.js',root);vm.runInNewContext(readFileSync(file,'utf8'),{App:d=>app=d,wx:h.wx,require:createRequire(file)});app.onLaunch();assert.equal(typeof app.ready?.then,'function');h.requests[0].success({statusCode:200,data:{user:{id:'owner'}}});await tick();h.requests[1].success({statusCode:200,data:{profiles:[{id:'child',nickname:'小豆'}]}});await tick();h.requests[2].success({statusCode:200,data:{revision:0,data:{version:1,lessons:{},items:{},session:null}}});await app.ready;assert.equal(app.client.profile.id,'child')});

test('native full guided lesson emits events accepted by existing FamilyStore normalization',async()=>{const h=harness('lesson'),events=[],save=h.client.saveProgress;h.client.saveProgress=(data,event)=>{if(event)events.push(copy(event));return save(data,event)};h.page.onLoad({id:'g3-upper-u1-l1'});await tick();while(h.page.session){const step=h.page.data.step;if(['listen','meaning','sentence','check'].includes(step.kind))h.page.submitAnswer(step.answer);if(step.kind==='oral')h.page.markOral();h.page.next()}assert.equal(h.page.data.finished,true);assert.ok(events.some(e=>e.kind==='answer'));for(const [i,event] of events.entries()){const normalized=normalizeEvent({...event,eventId:'00000000-0000-4000-8000-'+String(i).padStart(12,'0'),contentVersion:'pep3-2024-v1',occurredAt:Date.now()});assert.equal(normalized.contentId,'g3-upper-u1-l1')}assert.equal(h.client.progress().lessons['g3-upper-u1-l1'].completed,true)});
test('native lesson ignores a second completion tap after the finished view replaces next',async()=>{const h=harness('lesson');h.page.onLoad({id:'g3-upper-u1-l1'});await tick();let completions=0;const save=h.client.saveProgress;h.client.saveProgress=(data,event)=>{if(event?.kind==='completion')completions++;return save(data,event)};while(h.page.session){const step=h.page.data.step;if(['listen','meaning','sentence','check'].includes(step.kind))h.page.submitAnswer(step.answer);if(step.kind==='oral')h.page.markOral();h.page.next()}assert.doesNotThrow(()=>h.page.next());assert.equal(h.page.data.finished,true);assert.equal(h.page.data.canNext,false);assert.equal(completions,1)});

test('native page practice finishes after six questions and later rounds reach every source question',async()=>{const h=harness('page');h.page.onLoad({page:79});await tick();const source=h.page.data.page.questions,seen=[];assert.ok(source.length>200);while(seen.length<source.length){assert.ok(h.page.data.questions.length<=6);const size=h.page.data.questions.length;for(let i=0;i<size;i++){const q=h.page.data.question;seen.push(q.id);h.page.submitAnswer(q.answer);h.page.nextQuestion()}assert.equal(h.page.data.practiceFinished,true);assert.equal(h.page.data.question,null);if(seen.length<source.length)h.page.restartPractice()}assert.deepEqual(seen,source.map(q=>q.id));assert.ok(h.scrolls.length>source.length)});
test('page reading groups keep every original word and line reachable without an unbounded list',async()=>{const h=harness('page');h.page.onLoad({page:79});await tick();const groups=h.page.data.allReadingGroups;assert.ok(groups.length>1);const source=[...h.page.data.page.words,...h.page.data.page.blocks.flatMap(b=>b.lines)];assert.deepEqual(groups.flatMap(g=>g.lines).map(t=>t.targetId).sort(),source.map(t=>t.targetId).sort());assert.ok(groups.every(g=>g.lines.length<=6));h.page.toggleSupportWords();h.page.selectReadingGroup({detail:{value:groups.length-1}});assert.equal(h.page.data.readingGroupIndex,groups.length-1);assert.equal(h.page.data.readingGroup.title,groups.at(-1).title)});
test('page picker and adjacent controls keep all speakable source targets accessible',async()=>{const h=harness('page');h.page.onLoad({page:79});await tick();h.page.switchTab(event({tab:'speak'}));const expected=h.page.targets.filter(t=>t.audio&&t.speakable!==false);assert.equal(h.page.data.speakingTargets.length,expected.length);for(let index=0;index<expected.length;index++){h.page.selectSpeakingTarget({detail:{value:index}});assert.equal(h.page.data.speakingTarget.id,expected[index].id)}h.page.adjacentTarget(event({delta:-1}));assert.equal(h.page.data.speakingTarget.id,expected.at(-2).id)});
test('navigation protects an unsubmitted clip and pending feedback',async()=>{for(const route of ['page','lesson']){const h=harness(route);h.page.onLoad(route==='page'?{page:2}:{id:'g3-upper-u1-l1'});await tick();const before=route==='page'?h.page.pageNumber:h.page.session.index;for(const state of [{requesting:true},{assessing:true},{clip:true,result:null}]){h.page.setData({media:state});if(route==='page')h.page.changePage(event({delta:1}));else h.page.next();assert.equal(route==='page'?h.page.pageNumber:h.page.session.index,before)}}});
test('lesson long reading chooses one original line at a time and protects recording from next',async()=>{const h=harness('lesson');h.page.onLoad({id:'g3-upper-u6-l4'});await tick();while(h.page.data.step.kind!=='reading'){const s=h.page.data.step;if(['listen','meaning','sentence','check'].includes(s.kind))h.page.submitAnswer(s.answer);if(s.kind==='oral')h.page.markOral();h.page.next()}const lines=h.page.data.step.lines;assert.ok(lines.length>15);assert.equal(h.page.data.stepTargetItems.length,lines.length);h.page.selectStepTarget({detail:{value:lines.length-1}});assert.equal(h.page.data.speakingTarget.id,lines.at(-1).targetId);const index=h.page.session.index;await h.page.record();h.page.next();assert.equal(h.page.session.index,index);assert.equal(h.page.data.media.recording,true)});
test('answer feedback identifies the selected option and step navigation returns to start',async()=>{for(const route of ['page','lesson']){const h=harness(route);h.page.onLoad(route==='page'?{page:57}:{id:'g3-upper-u1-l1'});await tick();if(route==='lesson')while(!h.page.data.step.choices?.length)h.page.next();const q=route==='page'?h.page.data.question:h.page.data.step;const wrong=q.choices.find(v=>v!==q.answer);h.page.answer(event({answer:wrong}));assert.equal(h.page.data.feedback.selected,wrong);h.page.answer(event({answer:q.answer}));assert.equal(h.page.data.feedback.selected,q.answer);const before=h.scrolls.length;if(route==='page')h.page.nextQuestion();else h.page.next();assert.ok(h.scrolls.length>before)}});

test('native read view prioritizes source words outside headings and preserves collapsed heading vocabulary',async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();assert.deepEqual(h.page.data.readingGroup.lines.map(w=>w.en),['make','friend']);assert.equal(h.page.data.supportWordCount,6);assert.equal(h.page.data.showSupportWords,false);h.page.toggleSupportWords();const supplemental=h.page.data.readingGroups.filter(g=>g.supportWords).flatMap(g=>g.lines);assert.deepEqual(supplemental.map(w=>w.en),['unit','making','friends','how','do','we']);for(const w of supplemental){h.page.chooseAndSpeak(event({id:w.targetId}));assert.equal(h.page.data.speakingTarget.id,w.targetId)}});

test('every native textbook page retains all source words and lines in finite reading groups',async()=>{for(let number=2;number<=91;number++){const h=harness('page');h.page.onLoad({page:number});await tick();assert.equal(h.page.data.error,'');const expected=[...h.page.data.page.words,...h.page.data.page.blocks.flatMap(b=>b.lines)].map(t=>t.targetId).sort();assert.deepEqual(h.page.data.allReadingGroups.flatMap(g=>g.lines).map(t=>t.targetId).sort(),expected,'page '+number);assert.ok(h.page.data.allReadingGroups.every(g=>g.lines.length<=6),'page '+number);assert.ok(h.page.data.questions.length<=6);h.page.onUnload()}});

const nativeCompilerEnabled=process.arch==='x64'||!!process.env.MINIPROGRAM_COMPILER_PREFIX;
let compiledRenderer;
function nativeRenderer(){
 if(compiledRenderer)return compiledRenderer;
 const prefix=JSON.parse(process.env.MINIPROGRAM_COMPILER_PREFIX||'[]');
 const binary=new URL('node_modules/miniprogram-compiler/bin/'+(process.platform==='darwin'?'mac':'linux')+'/wcc',root).pathname;chmodSync(binary,0o755);
 const files=['pages/page/page.wxml','pages/lesson/lesson.wxml','components/speaking.wxml'];
 const result=spawnSync(prefix[0]||binary,[...prefix.slice(1),...(prefix.length?[binary]:[]),'-d','-cc','0',...files,'-gn','$gwx'],{cwd:new URL('miniprogram/',root),encoding:'utf8',maxBuffer:8*1024*1024});assert.equal(result.status,0,result.stderr||result.error?.message);
 const context={window:{},console};vm.createContext(context);vm.runInContext(result.stdout,context,{timeout:5000});compiledRenderer=(route,data)=>context.$gwx('pages/'+route+'/'+route+'.wxml')(data);return compiledRenderer;
}
const nativeNodes=tree=>[tree,...(tree.children||[]).filter(c=>typeof c==='object').flatMap(nativeNodes)];
const nativeText=tree=>typeof tree==='string'?tree:(tree.children||[]).map(nativeText).join('');
test('a displayed word opens its actual practice question and preserves the new resume cursor',async()=>{const h=harness('page');h.page.onLoad({page:79});await tick();const q=h.page.allQuestions[18];h.page.practiceTarget(event({id:q.targetId}));assert.equal(h.page.data.tab,'practice');assert.equal(h.page.data.question.targetId,q.targetId);assert.equal(h.page.data.roundNumber,4);assert.deepEqual(copy(h.client.pageCursor(79)),{roundStart:18,questionIndex:0});h.page.setData({media:{recording:true}});h.page.practiceTarget(event({id:h.page.allQuestions[0].targetId}));assert.equal(h.page.data.question.targetId,q.targetId);h.page.onUnload()});
test('native speaking help is folded until requested and recording keeps only the completion action',{skip:!nativeCompilerEnabled},async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();h.page.switchTab(event({tab:'speak'}));let nodes=nativeNodes(nativeRenderer()('page',h.page.data));assert.equal(nodes.filter(n=>n.attr?.bindtap==='openMicSettings').length,0);h.page.toggleSpeakingHelp();nodes=nativeNodes(nativeRenderer()('page',h.page.data));assert.equal(nodes.filter(n=>n.attr?.bindtap==='openMicSettings').length,1);await h.page.record();nodes=nativeNodes(nativeRenderer()('page',h.page.data));assert.equal(nodes.filter(n=>n.attr?.bindtap==='toggleSpeakingAudio').length,0);assert.equal(nodes.filter(n=>n.attr?.bindtap==='stopRecord').length,1);h.page.onUnload()});
test('real WCC lesson render shows one example action before safe-area next control', {skip:!nativeCompilerEnabled},async()=>{const h=harness('lesson');h.page.onLoad({id:'g3-upper-u1-l1'});await tick();const nodes=nativeNodes(nativeRenderer()('lesson',h.page.data));assert.equal(nodes.filter(n=>['listen','listenSpeaking','toggleSpeakingAudio'].includes(n.attr?.bindtap)).length,1);const record=nodes.findIndex(n=>n.attr?.bindtap==='record'),next=nodes.findIndex(n=>n.attr?.bindtap==='next');assert.ok(record>=0&&next>record);const footer=nodes.find(n=>n.attr?.class==='bottom-actions');assert.ok(footer);assert.equal(nativeNodes(footer).find(n=>n.attr?.bindtap==='next').attr.disabled,false);await h.page.record();const recordingNodes=nativeNodes(nativeRenderer()('lesson',h.page.data));assert.equal(recordingNodes.find(n=>n.attr?.bindtap==='next').attr.disabled,true);assert.ok(recordingNodes.some(n=>n.attr?.bindtap==='stopRecord'));assert.ok(recordingNodes.some(n=>nativeText(n).includes('正在录音')))});
test('real WCC page render reaches record without rendering a hundred target buttons', {skip:!nativeCompilerEnabled},async()=>{const h=harness('page');h.page.onLoad({page:79});await tick();h.page.switchTab(event({tab:'speak'}));const nodes=nativeNodes(nativeRenderer()('page',h.page.data));assert.ok(h.page.data.speakingTargets.length>100);assert.equal(nodes.filter(n=>n.attr?.bindtap==='chooseTarget').length,0);assert.ok(nodes.some(n=>n.tag==='wx-picker'&&n.attr?.bindchange==='selectSpeakingTarget'));assert.equal(nodes.filter(n=>n.attr?.bindtap==='record').length,1);assert.ok(nodes.filter(n=>n.tag==='wx-button').length<20);assert.ok(!nativeText(nodes[0]).includes('NaN'));h.page.selectSpeakingTarget({detail:{value:h.page.data.speakingTargets.length-1}});const selected=nativeRenderer()('page',h.page.data);assert.ok(nativeText(selected).includes(h.page.data.speakingTargets.at(-1).en))});
test('real WCC answer and spoken-word feedback show the chosen answer and useful retry cues', {skip:!nativeCompilerEnabled},async()=>{const h=harness('page');h.page.onLoad({page:57});await tick();h.page.switchTab(event({tab:'practice'}));const q=h.page.data.question,wrong=q.choices.find(v=>v!==q.answer);h.page.submitAnswer(wrong);const nodes=nativeNodes(nativeRenderer()('page',h.page.data));const chosen=nodes.find(n=>n.tag==='wx-button'&&n.attr?.['data-answer']===wrong);assert.ok(chosen.attr.class.includes('answer-retry'));assert.ok(nativeText(chosen).includes('再试试'));h.page.switchTab(event({tab:'speak'}));h.page.setData({media:{clip:true,result:{score:79,accuracy:80,completeness:90,words:[{word:'friend',score:91},{word:'hello',score:60}]}}});const spoken=nativeRenderer()('page',h.page.data);assert.ok(nativeText(spoken).includes('91 分 · 读得清楚'));assert.ok(nativeText(spoken).includes('60 分 · 再读一读'))});

test('lesson listen quiz uses its actual word as the speaking target',async()=>{const h=harness('lesson');h.page.onLoad({id:'g3-upper-u1-l1'});await tick();while(h.page.data.step.kind!=='listen')h.page.next();const step=h.page.data.step;assert.equal(h.page.data.speakingTarget?.en,step.say);h.page.listenSpeaking();assert.equal(h.audios.at(-1).src,require('../miniprogram/lib/view.js').absolute(h.page.data.speakingTarget.audio))});
test('all thirty-six native lessons complete with every selected reading and letter target reachable',async()=>{const catalog=JSON.parse(readFileSync(new URL('english/miniprogram-data/catalog.json',root)));const lessons=catalog.units.flatMap(u=>u.lessons);assert.equal(lessons.length,36);for(const lesson of lessons){const h=harness('lesson');h.page.onLoad({id:lesson.id});await tick();let steps=0;while(h.page.session){const s=h.page.data.step;assert.ok(steps++<200,'lesson cannot finish: '+lesson.id);if(s.lines||s.letters){const entries=s.lines||s.letters;for(const [index,item] of entries.entries()){h.page.selectStepTarget({detail:{value:index}});if(item.audio&&item.speakable!==false)assert.equal(h.page.data.speakingTarget.id,item.targetId,lesson.id+' '+item.en);else assert.equal(h.page.data.speakingTarget,null)}}if(['listen','meaning','sentence','check'].includes(s.kind))h.page.submitAnswer(s.answer);if(s.kind==='oral')h.page.markOral();h.page.next()}assert.equal(h.page.data.finished,true,lesson.id);assert.equal(h.client.progress().lessons[lesson.id].completed,true);h.page.onUnload()}});
test('real WCC listen quiz keeps reference text hidden until the child chooses', {skip:!nativeCompilerEnabled},async()=>{const h=harness('lesson');h.page.onLoad({id:'g3-upper-u1-l1'});await tick();while(h.page.data.step.kind!=='listen')h.page.next();const nodes=nativeNodes(nativeRenderer()('lesson',h.page.data));assert.equal(nodes.filter(n=>n.attr?.class==='english').length,0);assert.equal(nodes.filter(n=>n.attr?.bindtap==='toggleSpeakingAudio').length,1)});
test('real WCC successful feedback offers replay and rerecord without a duplicate scoring submission', {skip:!nativeCompilerEnabled},async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();h.page.switchTab(event({tab:'speak'}));h.page.setData({media:{clip:true,result:{score:90,accuracy:90,completeness:100,words:[{word:'friend',score:90}]}},mediaLocked:false});const nodes=nativeNodes(nativeRenderer()('page',h.page.data));assert.equal(nodes.filter(n=>n.attr?.bindtap==='submitRecording').length,0);assert.equal(nodes.filter(n=>n.attr?.bindtap==='replay').length,1);assert.equal(nodes.filter(n=>n.attr?.bindtap==='record').length,1)});

test('real WCC speaking demonstration toggles pause in the same button without an extra stop row', {skip:!nativeCompilerEnabled},async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();h.page.switchTab(event({tab:'speak'}));h.page.toggleSpeakingAudio();const nodes=nativeNodes(nativeRenderer()('page',h.page.data));const listener=nodes.find(n=>n.attr?.bindtap==='toggleSpeakingAudio');assert.ok(listener);assert.equal(nativeText(listener),'暂停播放');assert.equal(nodes.filter(n=>n.attr?.bindtap==='stopAudio').length,0);h.audios.at(-1).pause=()=>{};h.page.toggleSpeakingAudio();const paused=nativeNodes(nativeRenderer()('page',h.page.data));assert.equal(nativeText(paused.find(n=>n.attr?.bindtap==='toggleSpeakingAudio')),'继续播放')});

test('native page reopens at round two question three without overwriting the saved cursor',async()=>{const h=harness('page');h.page.onLoad({page:79});await tick();for(let i=0;i<6;i++){h.page.submitAnswer(h.page.data.question.answer);h.page.nextQuestion()}h.page.restartPractice();for(let i=0;i<2;i++){h.page.submitAnswer(h.page.data.question.answer);h.page.nextQuestion()}const id=h.page.data.question.id,cursor=copy(h.client.pageCursor(79));assert.deepEqual(cursor,{roundStart:6,questionIndex:2});h.page.onUnload();const reopened=harness('page',h.storage);let writes=0;const save=reopened.client.savePageCursor;reopened.client.savePageCursor=(...args)=>{writes++;save(...args)};reopened.page.onLoad({page:79});await tick();assert.equal(reopened.page.data.question.id,id);assert.equal(reopened.page.data.roundNumber,2);assert.equal(reopened.page.data.questionIndex,3);assert.equal(writes,0);assert.deepEqual(reopened.client.pageCursor(79),cursor)});
test('native page reopens a completed round before moving to the next finite round',async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();for(let i=0;i<6;i++){h.page.submitAnswer(h.page.data.question.answer);h.page.nextQuestion()}h.page.onUnload();const reopened=harness('page',h.storage);reopened.page.onLoad({page:2});await tick();assert.equal(reopened.page.data.practiceFinished,true);assert.equal(reopened.page.data.question,null);assert.equal(reopened.page.data.roundNumber,1);reopened.page.restartPractice();assert.equal(reopened.page.data.roundNumber,2);assert.equal(reopened.page.data.questionIndex,1);assert.deepEqual(copy(reopened.client.pageCursor(2)),{roundStart:6,questionIndex:0})});
test('native page rejects invalid cursors without destroying the stored value on load',async()=>{for(const cursor of [{roundStart:-6,questionIndex:0},{roundStart:1,questionIndex:0},{roundStart:9996,questionIndex:0},{roundStart:0,questionIndex:-1},{roundStart:0,questionIndex:7},{roundStart:0,questionIndex:1.5},{roundStart:'6',questionIndex:0}]){const h=harness('page');h.client.savePageCursor(2,cursor);h.page.onLoad({page:2});await tick();assert.equal(h.page.data.roundNumber,1);assert.equal(h.page.data.questionIndex,1);assert.deepEqual(h.client.pageCursor(2),cursor)}});
test('resumed native practice keeps first wrong answer and retry counting within the current question',async()=>{const h=harness('page');h.client.savePageCursor(57,{roundStart:6,questionIndex:2});h.page.onLoad({page:57});await tick();const q=h.page.data.question;h.page.submitAnswer(q.choices.find(v=>v!==q.answer));h.page.submitAnswer(q.answer);assert.equal(h.client.pageHistory(57)[q.id].attempts,1);assert.equal(h.client.pageHistory(57)[q.id].correct,0);h.page.nextQuestion();assert.deepEqual(copy(h.client.pageCursor(57)),{roundStart:6,questionIndex:3})});
test('native speaking demonstration pauses and resumes the same audio position',async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();h.page.switchTab(event({tab:'speak'}));h.page.toggleSpeakingAudio();const audio=h.audios.at(-1);audio.currentTime=1.25;audio.pause=()=>{};h.page.toggleSpeakingAudio();assert.equal(h.page.data.media.playing,false);assert.equal(h.page.data.media.paused,true);assert.equal(audio.destroyed,undefined);h.page.toggleSpeakingAudio();assert.equal(h.page.data.media.playing,true);assert.equal(h.audios.length,1);assert.equal(h.audios.at(-1).currentTime,1.25);h.page.onUnload();assert.equal(audio.destroyed,true)});
test('native full-page listening resumes within its queue and hide clears the paused audio',async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();h.page.readPage();h.audios[0].ended();const audio=h.audios.at(-1);audio.pause=()=>{};audio.currentTime=.75;h.page.readPage();assert.equal(h.page.data.media.playing,false);assert.equal(h.page.data.media.paused,true);h.page.readPage();assert.equal(h.audios.length,2);assert.equal(h.audios.at(-1).currentTime,.75);audio.ended();assert.equal(h.audios.length,3);assert.equal(h.page.data.media.playing,true);const next=h.audios.at(-1);next.pause=()=>{};h.page.readPage();h.page.onHide();assert.equal(next.destroyed,true);assert.equal(h.page.data.media.paused,false);next.ended();assert.equal(h.audios.length,3)});
test('native rerecord and target changes dispose of paused demonstration audio',async()=>{for(const action of ['record','target']){const h=harness('page');h.page.onLoad({page:2});await tick();h.page.switchTab(event({tab:'speak'}));h.page.toggleSpeakingAudio();const audio=h.audios.at(-1);audio.pause=()=>{};h.page.toggleSpeakingAudio();assert.equal(h.page.data.media.paused,true);if(action==='record')await h.page.record();else h.page.adjacentTarget(event({delta:1}));assert.equal(audio.destroyed,true);assert.equal(h.page.data.media.paused,false);if(action==='record')assert.equal(h.page.data.media.recording,true);h.page.onUnload()}});
test('real WCC reading audio keeps pause and resume on its own button', {skip:!nativeCompilerEnabled},async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();h.page.readGroup();h.audios.at(-1).pause=()=>{};let nodes=nativeNodes(nativeRenderer()('page',h.page.data));assert.equal(nativeText(nodes.find(n=>n.attr?.bindtap==='readGroup')),'暂停这一组');assert.equal(nativeText(nodes.find(n=>n.attr?.bindtap==='readPage')),'听全页');assert.equal(nodes.filter(n=>n.attr?.bindtap==='stopAudio').length,0);h.page.readGroup();nodes=nativeNodes(nativeRenderer()('page',h.page.data));assert.equal(nativeText(nodes.find(n=>n.attr?.bindtap==='readGroup')),'继续这一组');h.page.switchTab(event({tab:'practice'}));h.page.listenQuestion();nodes=nativeNodes(nativeRenderer()('page',h.page.data));assert.equal(nativeText(nodes.find(n=>n.attr?.bindtap==='listenQuestion')),'暂停原句');assert.equal(nodes.filter(n=>n.attr?.bindtap==='stopAudio').length,0)});
test('native paused queue defers a late ended callback until the child resumes',async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();h.page.readPage();const first=h.audios[0];first.pause=()=>{};h.page.readPage();first.ended();assert.equal(h.audios.length,1);assert.equal(h.page.data.media.playing,false);assert.equal(h.page.data.media.paused,true);h.page.readPage();assert.equal(h.audios.length,2);assert.equal(h.page.data.media.playing,true);assert.equal(h.page.data.media.paused,false);h.page.onUnload()});
test('native last audio ending while paused completes only on resume and clears pause state',async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();h.page.switchTab(event({tab:'speak'}));h.page.toggleSpeakingAudio();const audio=h.audios[0];audio.pause=()=>{};h.page.toggleSpeakingAudio();audio.ended();assert.equal(h.page.data.media.paused,true);assert.equal(h.page.data.media.playing,false);h.page.toggleSpeakingAudio();assert.equal(h.audios.length,1);assert.equal(h.page.data.media.playing,false);assert.equal(h.page.data.media.paused,false);assert.equal(h.page.data.media.source,'');h.page.toggleSpeakingAudio();assert.equal(h.audios.length,2);assert.equal(h.page.data.media.playing,true);h.page.onUnload()});
test('native retired queue player cannot stop or skip the next audio with late callbacks',async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();h.page.readPage();const first=h.audios[0];first.ended();const next=h.audios[1];first.error();assert.equal(h.page.data.media.playing,true);assert.equal(next.destroyed,undefined);assert.equal(next.stopped,undefined);first.ended();assert.equal(h.audios.length,2);assert.equal(h.page.data.media.message,'');next.ended();assert.equal(h.audios.length,3);h.page.onUnload()});
test('native hide discards a queue waiting on a paused end callback',async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();h.page.readPage();const first=h.audios[0];first.pause=()=>{};h.page.readPage();first.ended();h.page.onHide();assert.equal(h.page.data.media.paused,false);first.ended();assert.equal(h.audios.length,1);h.page.onShow();h.page.readPage();assert.equal(h.audios.length,2);h.page.onUnload()});
