import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {normalizeEvent} from '../platform/english-progress.mjs';
const require=createRequire(import.meta.url);
const {createClient}=require('../miniprogram/lib/client.js');
const root=new URL('../',import.meta.url);
const copy=x=>JSON.parse(JSON.stringify(x));
function harness(route){let definition;const storage=new Map(),requests=[],audios=[];let recorder;
 const wx={getStorageSync:k=>storage.get(k),setStorageSync:(k,v)=>storage.set(k,copy(v)),removeStorageSync:k=>storage.delete(k),request:o=>{if(o.url.includes('/english/miniprogram-data/')){const path=o.url.split('/english/miniprogram-data/')[1];o.success({statusCode:200,data:JSON.parse(readFileSync(new URL('english/miniprogram-data/'+path,root)))})}else{requests.push(o)}return{abort(){o.aborted=true}}},createInnerAudioContext(){const a={play(){},stop(){a.stopped=true},destroy(){a.destroyed=true},onEnded:f=>a.ended=f,onError:f=>a.error=f};audios.push(a);return a},getRecorderManager(){return recorder??={onStart:f=>recorder.started=f,onStop:f=>recorder.stopped=f,onError:f=>recorder.error=f,offStart(){},offStop(){},offError(){},start(options){recorder.options=options;recorder.started()},stop(){recorder.stopCalled=true}}},requirePrivacyAuthorize:o=>o.success(),authorize:o=>o.success(),getFileSystemManager:()=>({unlink:o=>storage.set('deleted:'+o.filePath,true),readFile:o=>o.success({data:new ArrayBuffer(44)})}),navigateTo(){},navigateBack(){},openSetting(){},openPrivacyContract(){}};
 const client=createClient(wx),file=new URL('miniprogram/pages/'+route+'/'+route+'.js',root);vm.runInNewContext(readFileSync(file,'utf8'),{Page:d=>definition=d,require:createRequire(file),wx,getApp:()=>({client}),console,Date,Set,Number,JSON});const page={...definition,data:copy(definition.data),setData(update){Object.assign(this.data,copy(update))}};return{page,client,wx,storage,requests,audios,get recorder(){return recorder}};
}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const event=data=>({currentTarget:{dataset:data}});
test('native lesson source answer retry preserves first incorrect answer and cannot skip quiz',async()=>{const h=harness('lesson');h.page.onLoad({id:'g3-upper-u1-l1'});await tick();assert.equal(h.page.data.loading,false);while(!['listen','meaning','sentence','check'].includes(h.page.data.step.kind))h.page.next();const step=h.page.data.step,index=h.page.session.index;h.page.next();assert.equal(h.page.session.index,index);const wrong=step.choices.find(x=>x!==step.answer);h.page.answer(event({answer:wrong}));assert.equal(h.page.data.feedback.correct,false);h.page.answer(event({answer:step.answer}));assert.equal(h.page.data.feedback.correct,true);assert.equal(h.page.session.answers[step.id].correct,false);assert.equal(h.page.progress.items[step.itemKey].incorrect,1);assert.equal(h.page.progress.items[step.itemKey].correct,0);h.page.next();assert.equal(h.page.session.index,index+1)});
test('page controls play sequential real media and hide cancels queued callback',async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();h.page.readPage();assert.equal(h.page.data.media.playing,true);const first=h.audios[0];assert.ok(first.src.startsWith('https://games.nblord.com/english/audio/'));first.ended();assert.equal(h.audios.length,2);h.page.onHide();h.audios[1].ended();assert.equal(h.audios.length,2);assert.equal(h.page.data.media.playing,false)});
test('native stop button cancels sequence without later restarting playback',async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();h.page.readPage();h.page.stopAudio();h.audios[0].ended();assert.equal(h.audios.length,1);assert.equal(h.page.data.media.playing,false)});
test('page answer retries record one first answer and display-only target cannot record',async()=>{const h=harness('page');h.page.onLoad({page:57});await tick();const q=h.page.data.question;h.page.answer(event({answer:q.choices.find(x=>x!==q.answer)}));h.page.answer(event({answer:q.answer}));assert.equal(h.page.data.feedback.correct,true);assert.equal(h.client.pageHistory(57)[q.id].attempts,1);assert.equal(h.client.pageHistory(57)[q.id].correct,0);const silent=h.page.targets.find(t=>t.id==='p57-line-2-3');assert.equal(silent.speakable,false);h.page.chooseTarget(event({id:silent.id}));assert.equal(h.page.data.speakingTarget,null);assert.ok(!h.page.questions.some(q=>q.targetId===silent.id))});
test('changing page discards pending recording file and target',async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();const target=h.page.targets.find(t=>t.audio);h.page.chooseAndSpeak(event({id:target.id}));await h.page.record();assert.equal(h.page.data.media.recording,true);h.page.changePage(event({delta:1}));h.recorder.stopped({tempFilePath:'/temp/stale.wav',duration:1000});await tick();assert.equal(h.storage.get('deleted:/temp/stale.wav'),true);assert.equal(h.page.data.media.clip,false);assert.equal(h.page.data.speakingTarget,null);assert.equal(h.page.data.page.page,3)});
test('native account input and failed login clear password and busy state',async()=>{const h=harness('account');h.page.onLoad();h.page.input({currentTarget:{dataset:{key:'username'}},detail:{value:'parent'}});h.page.input({currentTarget:{dataset:{key:'password'}},detail:{value:'wrong'}});const action=h.page.usernameLogin();h.requests[0].success({statusCode:401,data:{error:'bad credentials'}});await action;assert.equal(h.page.data.password,'');assert.equal(h.page.data.busy,false);assert.ok(h.page.data.error)});
test('returning to open lesson after child switch reloads and never saves the old child session',async()=>{const h=harness('lesson');h.page.onLoad({id:'g3-upper-u1-l1'});await tick();h.page.next();const oldIndex=h.page.session.index;h.page.onHide();const saved={version:1,lessons:{},items:{},session:null};let writes=0;Object.defineProperty(h.client,'identity',{get:()=> 'new-child'});h.client.progress=()=>copy(saved);h.client.saveProgress=data=>{writes++;assert.ok(data.session.index===0)};h.page.onShow();await tick();assert.equal(h.page.session.index,0);assert.ok(oldIndex>0);assert.ok(writes>0)});
test('replay uses local file path and delayed stop after unload deletes a clip',async()=>{const h=harness('page');h.page.onLoad({page:2});await tick();h.page.chooseAndSpeak(event({id:h.page.targets[0].id}));await h.page.record();h.page.stopRecord();h.recorder.stopped({tempFilePath:'wxfile://temp/current.wav',duration:1000});h.page.replay();assert.equal(h.audios[0].src,'wxfile://temp/current.wav');await h.page.record();h.page.onUnload();h.recorder.stopped({tempFilePath:'wxfile://temp/late.wav',duration:1000});assert.equal(h.storage.get('deleted:wxfile://temp/late.wav'),true)});
test('logout network failure still returns account view to visitor',async()=>{const h=harness('account');h.page.onLoad();h.storage.set('mini-session-v1',{token:'session',user:{id:'parent'}});h.client.restore();h.page.setData({user:h.client.user});const exiting=h.page.logout();h.requests[0].fail();await exiting;assert.equal(h.client.user,null);assert.equal(h.page.data.user,null)});
test('app restart revalidates bearer session before restoring selected child',async()=>{const h=harness('home');h.storage.set('mini-session-v1',{token:'token',user:{id:'owner'}});h.storage.set('mini-profile-v1:owner',{id:'child',nickname:'小豆'});let app;const file=new URL('miniprogram/app.js',root);vm.runInNewContext(readFileSync(file,'utf8'),{App:d=>app=d,wx:h.wx,require:createRequire(file)});app.onLaunch();assert.equal(typeof app.ready?.then,'function');h.requests[0].success({statusCode:200,data:{user:{id:'owner'}}});await tick();h.requests[1].success({statusCode:200,data:{profiles:[{id:'child',nickname:'小豆'}]}});await tick();h.requests[2].success({statusCode:200,data:{revision:0,data:{version:1,lessons:{},items:{},session:null}}});await app.ready;assert.equal(app.client.profile.id,'child')});

test('native full guided lesson emits events accepted by existing FamilyStore normalization',async()=>{const h=harness('lesson'),events=[],save=h.client.saveProgress;h.client.saveProgress=(data,event)=>{if(event)events.push(copy(event));return save(data,event)};h.page.onLoad({id:'g3-upper-u1-l1'});await tick();while(h.page.session){const step=h.page.data.step;if(['listen','meaning','sentence','check'].includes(step.kind))h.page.submitAnswer(step.answer);if(step.kind==='oral')h.page.markOral();h.page.next()}assert.equal(h.page.data.finished,true);assert.ok(events.some(e=>e.kind==='answer'));for(const [i,event] of events.entries()){const normalized=normalizeEvent({...event,eventId:'00000000-0000-4000-8000-'+String(i).padStart(12,'0'),contentVersion:'pep3-2024-v1',occurredAt:Date.now()});assert.equal(normalized.contentId,'g3-upper-u1-l1')}assert.equal(h.client.progress().lessons['g3-upper-u1-l1'].completed,true)});
