import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {LESSONS} from '../english/course-curriculum.js';
import {buildSteps,createSession} from '../english/course-engine.js';
const require=createRequire(import.meta.url);
const {createClient}=require('../miniprogram/lib/client.js');
const {createMedia}=require('../miniprogram/lib/media.js');
const engine=require('../miniprogram/lib/course-engine.js');
function wavRecording(){const b=Buffer.alloc(16044);b.write('RIFF');b.writeUInt32LE(16036,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(16000,24);b.writeUInt32LE(32000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(16000,40);return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}
function port(){const store=new Map(),requests=[],audio=[];let recorder;
 const wx={getStorageSync:k=>store.get(k),setStorageSync:(k,v)=>store.set(k,v),removeStorageSync:k=>store.delete(k),request:o=>{requests.push(o);return {abort(){o.aborted=true}}},login:o=>o.success({code:'temporary-code'}),createInnerAudioContext(){const a={stop(){a.stopped=true},destroy(){a.destroyed=true},play(){a.played=true},onEnded:f=>a.ended=f,onError:f=>a.error=f};audio.push(a);return a},getRecorderManager(){return recorder??=( {onStart(f){this.started=f},onStop(f){this.stopped=f},onError(f){this.error=f},offStart(){},offStop(){},offError(){},start(o){this.options=o;this.started()},stop(){this.stopCalled=true}})},requirePrivacyAuthorize:o=>o.success(),authorize:o=>o.success(),getFileSystemManager:()=>({unlink:o=>{store.set('deleted:'+o.filePath,true);o.success?.()},readFile:o=>o.success({data:wavRecording()})})};return {wx,store,requests,audio,get recorder(){return recorder}}}
const ok=(r,data)=>r.success({statusCode:200,data});
test('native CommonJS engine has identical source steps and resume wire format',()=>{for(const lesson of LESSONS){assert.deepEqual(engine.buildSteps(lesson),buildSteps(lesson));assert.deepEqual(engine.createSession(lesson,{now:1}),createSession(lesson,{now:1}))}});
test('login requires server token and authenticated requests carry only verified session',async()=>{const p=port(),c=createClient(p.wx);const task=c.username('parent','secret');assert.equal(p.requests[0].url.endsWith('/username'),true);ok(p.requests[0],{token:'server-token',user:{id:'u'}});await task;const profiles=c.request('/profiles');assert.equal(p.requests[1].header.Authorization,'Bearer server-token');ok(p.requests[1],{profiles:[]});await profiles;const rejected=c.wechatLogin();await Promise.resolve();ok(p.requests[2],{user:{id:'fake'}});await assert.rejects(rejected,/登录/);assert.equal(c.user.id,'u')});
test('profile selection ignores earlier cloud response and page history stays separate',async()=>{const p=port(),c=createClient(p.wx);p.store.set('mini-session-v1',{token:'token',user:{id:'owner'}});c.restore();const a=c.selectProfile({id:'a',nickname:'A'}),b=c.selectProfile({id:'b',nickname:'B'});ok(p.requests[1],{revision:2,data:{version:1,lessons:{b:{}},items:{},session:null}});await b;ok(p.requests[0],{revision:1,data:{version:1,lessons:{a:{}},items:{},session:null}});await a;assert.equal(c.profile.id,'b');c.savePageHistory(4,{attempts:1});assert.equal(c.pageHistory(4).attempts,1);const change=c.selectProfile({id:'a'});ok(p.requests[2],{revision:1,data:{version:1,lessons:{},items:{},session:null}});await change;assert.deepEqual(c.pageHistory(4),{})});
test('audio sequence stops on cancellation and delayed ended never restarts it',()=>{const p=port(),states=[],m=createMedia(p.wx,{onState:s=>states.push(s)});m.play(['/english/audio/a.mp3','/english/audio/b.mp3']);assert.equal(p.audio[0].src,'https://games.nblord.com/english/audio/a.mp3');m.cancel();p.audio[0].ended();assert.equal(p.audio.length,1);assert.equal(p.audio[0].destroyed,true);assert.equal(states.at(-1).playing,false)});
test('record permission, WAV options, explicit binary score and stale cleanup',async()=>{const p=port(),m=createMedia(p.wx);m.setTarget({id:'p2-word-0',en:'hello',audio:'/english/audio/hello.mp3'});await m.record();assert.deepEqual(p.recorder.options,{duration:20000,sampleRate:16000,numberOfChannels:1,encodeBitRate:48000,format:'wav'});assert.equal(p.requests.length,0);m.stopRecord();p.recorder.stopped({tempFilePath:'/temp/a.wav',duration:500});const scoring=m.submit();await Promise.resolve();assert.ok(p.requests[0].data instanceof ArrayBuffer);assert.equal(p.requests[0].header['Content-Type'],'audio/wav');m.setTarget({id:'p2-word-1',en:'goodbye'});assert.equal(p.requests[0].aborted,true);ok(p.requests[0],{engine:'local-phoneme',score:80,accuracy:80,completeness:90,duration:.5,words:[{word:'hello',score:80}]});await scoring;assert.equal(m.state.result,null);assert.equal(p.store.get('deleted:/temp/a.wav'),true);m.destroy()});
test('cancel before microphone grant cannot start recorder and stale stop file is deleted',async()=>{const p=port();let grant;p.wx.authorize=o=>grant=o;const m=createMedia(p.wx);m.setTarget({id:'p2-word-0',en:'hello'});const recording=m.record();await Promise.resolve();m.cancel();grant.success();await recording;assert.equal(p.recorder,undefined);});
test('save during active flush gets a second batch without losing later answers',async()=>{const p=port(),c=createClient(p.wx);p.store.set('mini-session-v1',{token:'token',user:{id:'owner'}});c.restore();const selecting=c.selectProfile({id:'child'});ok(p.requests[0],{revision:0,data:{version:1,lessons:{},items:{},session:null}});await selecting;const data=c.progress();c.saveProgress(data,{contentId:'g3-upper-u1-l1',kind:'answer',result:{itemKey:'first',correct:false,hinted:false}});const flushing=c.flush();c.saveProgress({...data,items:{second:{correct:1}}},{contentId:'g3-upper-u1-l1',kind:'answer',result:{itemKey:'second',correct:true,hinted:false}});ok(p.requests[1],{revision:1,data});await Promise.resolve();assert.equal(p.requests.length,3);assert.equal(p.requests[2].data.events.length,1);assert.equal(p.requests[2].data.events[0].result.itemKey,'second');ok(p.requests[2],{revision:2,data:{...data,items:{second:{correct:1}}}});await flushing;assert.equal(c.pending,0)});
test('verified profile can reopen its pending local journal offline',async()=>{const p=port(),c=createClient(p.wx);p.store.set('mini-session-v1',{token:'token',user:{id:'owner'}});c.restore();const selecting=c.selectProfile({id:'child'});ok(p.requests[0],{revision:2,data:{version:1,lessons:{},items:{},session:null}});await selecting;c.saveProgress({...c.progress(),session:{lessonId:'g3-upper-u1-l1'}},null);c.guest();const reopening=c.selectProfile({id:'child'});p.requests[1].fail();await reopening;assert.equal(c.profile.id,'child');assert.equal(c.progress().session.lessonId,'g3-upper-u1-l1');assert.ok(c.pending)});
test('microphone refusal keeps listen available and never starts recording',async()=>{const p=port();p.wx.authorize=o=>o.fail({errMsg:'deny'});const m=createMedia(p.wx);m.setTarget({id:'p2-word-0',en:'hello'});await m.record();assert.equal(m.state.requesting,false);assert.equal(m.state.recording,false);assert.equal(p.recorder,undefined);m.play(['/english/audio/hello.mp3']);assert.equal(m.state.playing,true)});
test('stale session refresh cannot overwrite a newly authenticated account',async()=>{const p=port(),c=createClient(p.wx);p.store.set('mini-session-v1',{token:'old-token',user:{id:'old'}});c.restore();const refresh=c.refresh();const login=c.username('new','secret');ok(p.requests[1],{token:'new-token',user:{id:'new'}});await login;ok(p.requests[0],{user:{id:'old'}});await refresh;assert.equal(c.user.id,'new');assert.equal(p.store.get('mini-session-v1').token,'new-token')});
test('reselecting same child waits for in-flight acknowledgement before reading cloud',async()=>{const p=port(),c=createClient(p.wx);p.store.set('mini-session-v1',{token:'token',user:{id:'owner'}});c.restore();const selecting=c.selectProfile({id:'child'});ok(p.requests[0],{revision:0,data:{version:1,lessons:{},items:{},session:null}});await selecting;c.saveProgress(c.progress());const flushing=c.flush(),reselect=c.selectProfile({id:'child'});assert.equal(p.requests.length,2);ok(p.requests[1],{revision:1,data:c.progress()});await flushing;await Promise.resolve();assert.equal(p.requests.length,3);ok(p.requests[2],{revision:1,data:c.progress()});await reselect;assert.equal(c.conflict,null);assert.equal(c.pending,0)});
test('page round cursors persist per child and visitor without mixing identities',async()=>{const p=port(),c=createClient(p.wx);c.savePageCursor(4,{roundStart:6,questionIndex:2});assert.deepEqual(c.pageCursor(4),{roundStart:6,questionIndex:2});p.store.set('mini-session-v1',{token:'token',user:{id:'owner'}});c.restore();const a=c.selectProfile({id:'a'});ok(p.requests[0],{revision:0,data:{version:1,lessons:{},items:{},session:null}});await a;assert.equal(c.pageCursor(4),null);c.savePageCursor(4,{roundStart:12,questionIndex:1});const b=c.selectProfile({id:'b'});ok(p.requests[1],{revision:0,data:{version:1,lessons:{},items:{},session:null}});await b;assert.equal(c.pageCursor(4),null);c.guest();assert.deepEqual(c.pageCursor(4),{roundStart:6,questionIndex:2})});
