import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {createPronunciation,validateWav} from '../platform/pronunciation.mjs';
function wav(seconds=1){const b=Buffer.alloc(44+32000*seconds);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(16000,24);b.writeUInt32LE(32000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(b.length-44,40);return b;}
test('WAV validates duration, encoding and malformed lengths',()=>{assert.equal(validateWav(wav()).duration,1);assert.throws(()=>validateWav(wav(21)));const bad=wav();bad.writeUInt16LE(2,22);assert.throws(()=>validateWav(bad));assert.throws(()=>validateWav(Buffer.from('x')));});
test('unconfigured service is truthfully disabled',async()=>{assert.deepEqual(await createPronunciation().status(),{enabled:false,provider:null});});
test('service validates health, response and limits before inference',async t=>{let requests=0, malformed=false;const server=http.createServer(async(req,res)=>{res.setHeader('content-type','application/json');if(req.url==='/health')return res.end('{"ready":true,"engine":"local-phoneme"}');requests++;for await(const chunk of req){};res.end(JSON.stringify(malformed?{score:999}:{score:90,accuracy:90,completeness:100,words:[{word:'cat',score:90,errorType:'None'}],duration:1,engine:'local-phoneme'}));});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());const p=createPronunciation({localUrl:`http://127.0.0.1:${server.address().port}`,perMinute:1});assert.equal((await p.status()).enabled,true);assert.equal((await p.assess({ip:'a',target:{id:'cat',text:'cat'},audio:wav()})).score,90);await assert.rejects(p.assess({ip:'a',target:{id:'cat',text:'cat'},audio:wav()}),{status:429});assert.equal(requests,1);malformed=true;await assert.rejects(p.assess({ip:'b',target:{id:'cat',text:'cat'},audio:wav()}),{status:503});});
test('HTTP route accepts only server-known targets and same-origin WAV',async t=>{const{createApi}=await import('../platform/server.mjs');let called=0;const api=createApi({store:{},secret:'testing-secret-longer-than-thirty-two-characters',publicOrigin:'https://games.test',getSpeechTarget:id=>id==='cat'?{id,en:'cat'}:null,pronunciation:{status:async()=>({enabled:true,provider:'local-phoneme'}),assess:async({target})=>{called++;assert.equal(target.en,'cat');return{score:80};}}});await new Promise(r=>api.listen(0,'127.0.0.1',r));t.after(()=>api.close());const base=`http://127.0.0.1:${api.address().port}`;assert.deepEqual(await(await fetch(base+'/api/english/speech-status')).json(),{enabled:true,provider:'local-phoneme'});const post=(target,origin='https://games.test',type='audio/wav')=>fetch(base+'/api/english/pronunciation?target='+target,{method:'POST',headers:{origin,'content-type':type},body:wav()});assert.equal((await post('cat','https://foreign.test')).status,403);assert.equal((await post('arbitrary')).status,400);assert.equal((await post('cat','https://games.test','application/json')).status,415);assert.equal((await post('cat')).status,200);assert.equal(called,1);});
test('daily caps and active concurrency reject requests before acoustic call',async t=>{let finish,calls=0;const server=http.createServer(async(req,res)=>{if(req.url==='/health'){res.end('{"ready":true,"engine":"local-phoneme"}');return;}calls++;for await(const chunk of req){};await new Promise(r=>finish=r);res.end(JSON.stringify({score:100,accuracy:100,completeness:100,duration:1,words:[{word:'cat',score:100,errorType:'None'}],engine:'local-phoneme'}));});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());const p=createPronunciation({localUrl:`http://127.0.0.1:${server.address().port}`,dailyLimit:1});const pending=p.assess({ip:'a',target:{id:'cat',en:'cat'},audio:wav()});while(!finish)await new Promise(r=>setTimeout(r,5));await assert.rejects(p.assess({ip:'b',target:{id:'cat',en:'cat'},audio:wav()}),{status:429});finish();await pending;assert.equal(calls,1);});
