import {COURSE,LESSONS} from './curriculum.js';
import {loadProgress,createSession,recordAnswer,advance,completeLesson,recommendLesson,dueItems,buildSteps} from './engine.js';
import {initialWidget,renderWidget,updateWidget,netDiagram} from './widgets.js';
import {escapeHTML as esc,browserStorage} from '../shared/family-client.js';
import {mountClassroomNav} from '../shared/classroom-nav.js';
import {mountFamily} from './family.js';
import {MandarinReader} from '../chinese/audio.js';
import {createWebEncouragement,stopEncouragement} from '../english/encouragement-audio.js';
const root=document.querySelector('#courseRoot'),storage=browserStorage(),KEY='pearl-math-course-v1',dialog=document.querySelector('#directory');
let raw;try{raw=storage.getItem(KEY);}catch{}
let progress=loadProgress(raw),storageKey=KEY,session=null,cloud,shownHint=false,widgetState=null,netAnimation=null;
const hinted=new Set();
const mathText=value=>esc(value).replace(/(\d+)\/(\d+)/g,(_,n,d)=>`<span class="math-fraction" role="math" aria-label="${d}分之${n}"><span>${n}</span><span>${d}</span></span>`);
const notice=value=>{document.querySelector('#notice').textContent=value;};
const reader=new MandarinReader({onState:value=>{document.querySelector('#audioStatus').textContent=value;document.querySelector('#mathStop').hidden=!value;}});
const encouragement=createWebEncouragement({stopAudio:()=>reader.cancel()});
function stop(){reader.cancel();stopEncouragement();if(netAnimation)cancelAnimationFrame(netAnimation.frame);netAnimation=null;}
function animateNet(from,to){if(netAnimation)cancelAnimationFrame(netAnimation.frame);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;netAnimation={from,to,start:performance.now(),paused:false,frame:0};const a=netAnimation;const tick=now=>{if(netAnimation!==a||a.paused)return;const elapsed=Math.min(1,(now-a.start)/1700),t=a.from+(a.to-a.from)*elapsed;widgetState.foldPosition=t;const container=root.querySelector('.math-net-frame');if(!container){netAnimation=null;return;}container.innerHTML=netDiagram(widgetState,t);const pause=root.querySelector('#mathNetPause');if(pause)pause.disabled=elapsed===1;if(elapsed<1)a.frame=requestAnimationFrame(tick);else netAnimation=null;};if(reduced){a.start-=1700;tick(performance.now());}else{root.querySelector('#mathNetPause').disabled=false;a.frame=requestAnimationFrame(tick);}}
function pauseNet(){const a=netAnimation;if(!a)return;const b=root.querySelector('#mathNetPause');if(!a.paused){a.paused=true;cancelAnimationFrame(a.frame);b.textContent='继续动画';}else{const from=widgetState.foldPosition;animateNet(from,a.to);b.textContent='暂停动画';}}
function save(event=null){if(session)progress.session=session;try{storage.setItem(storageKey,JSON.stringify(progress));}catch{notice('进度暂时无法保存，请保持页面打开。');}cloud?.onSave({progress:JSON.parse(JSON.stringify(progress)),event});}
function replaceProgress(value,{storageKey:key=KEY,preserveView=false}={}){const learning=!!session,keepFinish=preserveView&&key===storageKey&&root.querySelector('.math-finish')&&!value?.session;stop();storageKey=key;progress=loadProgress(value);if(keepFinish)return;session=preserveView&&learning?progress.session:null;widgetState=null;shownHint=false;session?renderStep():home();}
function home(){stop();if(session)save();session=null;widgetState=null;shownHint=false;const lesson=recommendLesson(LESSONS,progress)||LESSONS[0],resume=progress.session&&!progress.session.completedAt;const done=LESSONS.filter(l=>progress.lessons[l.id]?.completed).length;const due=dueItems(progress).filter(k=>progress.lessons[k.split(':')[0]]?.completed).length;
 root.innerHTML=`<section class="math-hero"><div><span class="cn-kicker">数学 · 三年级上册</span><h1>动手试一试，<br>看见数学。</h1><p>换个方向看，分一分，想清楚每一步。</p><span class="cn-progress-label">已发现 ${done} / ${LESSONS.length} 个小课</span></div><img src="../math/illustrations/garden.webp" alt="孩子们在花园课堂观察积木、折纸与尺子" width="1200" height="800" fetchpriority="high"></section><section class="math-today"><div><span class="cn-kicker">${resume?'接着上次的发现':'今天的小发现'}</span><h2>${esc(lesson.title)}</h2><p>${esc(lesson.goal)}</p></div><button id="startMath" class="cn-primary">${resume?'继续学习':'开始小课'} →</button></section><div class="cn-section-title"><div><span class="cn-kicker">一步一步，自己想清楚</span><h2>我的数学旅程</h2></div><button id="mathDirectory">完整目录 ↗</button></div><section class="math-units">${COURSE.units.map((u,i)=>`<button data-unit="${u.id}" class="math-unit"><span class="math-unit-symbol" aria-hidden="true">${['◧','＋','↔','⚖','×','▥','∠','½','↗'][i]}</span><span>${u.number?`第 ${u.number} 单元`:'数学活动'}</span><strong>${esc(u.title)}</strong><small>${esc(u.description)}</small><small>课本第 ${u.pages[0]}—${u.pages.at(-1)} 页</small></button>`).join('')}</section><section class="cn-review"><div><h2>再想一次，发现会更清楚</h2><p>${due?`${due} 道练习，等你再试一次。`:'学过的题目会按你的答题情况安排回顾。'}</p></div><button id="mathReview" ${due?'':'disabled'}>复习错题与到期内容</button></section><p class="cn-source">${esc(COURSE.edition)}<br>按用户提供的课本页码设计；教学说明、练习和互动图形为原创。说一说与动手活动由自己确认尝试。</p>`;
}
function start(id=null,{review=false,reviewKeys=[]}={}){if(review&&progress.session&&!progress.session.completedAt&&!progress.session.review){notice('先接着完成上次的小课，再来复习。学习位置已保存。');return;}const saved=progress.session,lesson=LESSONS.find(l=>l.id===(id||saved?.lessonId))||recommendLesson(LESSONS,progress)||LESSONS[0];if(review&&!progress.lessons[lesson.id]?.completed)return;stop();session=saved&&!saved.completedAt&&!review&&(!id||id===saved.lessonId)?saved:createSession(lesson,{review,reviewKeys});if(!session)return;encouragement.reset();notice('');widgetState=null;shownHint=false;save();renderStep();focusStep();}
function focusStep(){const heading=root.querySelector('h1');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});heading.scrollIntoView({block:'start'});}}
function hintKey(){return `${storageKey}:hint:${session?.startedAt}:${session?.steps[session.index]?.id}`;}
function usedHint(){try{return hinted.has(hintKey())||storage.getItem(hintKey())==='1';}catch{return hinted.has(hintKey());}}
function renderStep(){if(!session)return home();const s=session.steps[session.index],l=LESSONS.find(l=>l.id===session.lessonId);if(!s)return finish();const answer=session.answers[s.id],correct=answer?.latest?.correct;let body=`<div class="math-text">${mathText(s.prompt||s.text||'')}</div>`;if(s.widget){widgetState ||= initialWidget(s.widget);body+=renderWidget(widgetState,{interactive:!s.itemKey});}
 if(s.kind==='preview')body=`<p class="math-goal">这次的小目标：${esc(l.goal)}</p>`+body;
 if(s.itemKey){if(s.choices?.length)body+=`<div class="math-choices">${s.choices.map((v,i)=>`<button data-answer="${i}" ${correct?'disabled':''} class="${answer?.latest?.selected===v?(correct?'is-correct':'is-retry'):''}"><span class="math-choice-label">${String.fromCharCode(65+i)}</span>${mathText(v)}</button>`).join('')}</div>`;else body+=`<form id="mathAnswerForm"><label for="mathAnswer">你的答案</label><div class="math-answer-row"><input id="mathAnswer" name="answer" autocomplete="off" inputmode="${String(s.answer).includes('/')?'text':'numeric'}" maxlength="20" placeholder="${String(s.answer).includes('/')?'例如 1/2':'填写数字'}" ${correct?'disabled':''} value="${esc(answer?.latest?.selected||'')}"><button class="cn-primary" ${correct?'disabled':''}>核对答案</button></div></form>`;if(answer)body+=`<div class="math-feedback" role="status">${correct?`想清楚了！${mathText(s.explanation||'')}`:'再看看题目。可以使用提示，然后再试一次。'}</div>`;}
 if(s.kind==='expression')body+='<p class="math-honest">可以对家人说，也可以画在本子上。这里记录你自己的尝试。</p>';
 const stage={preview:'先想一想',explore:'动手发现',learn:'想清楚方法',question:'自己试一试',expression:'说说为什么',recap:'回想今天的发现'}[s.kind]||'继续发现';
 root.innerHTML=`<section class="math-study"><div class="cn-study-top"><button id="mathExit">← 保存并退出</button><span>${session.index+1} / ${session.steps.length} 步</span></div><progress max="${session.steps.length}" value="${session.index}" aria-label="本课进度"></progress><div class="cn-study-meta"><span>${stage}</span><span>课本第 ${l.pages[0]}—${l.pages.at(-1)} 页</span></div><h1>${esc(l.title)}</h1>${s.title?`<h2>${esc(s.title)}</h2>`:''}${body}${s.hint?`<button id="mathHint" class="cn-text-button">${shownHint?'收起提示':'给我一个小提示'}</button><p class="cn-hint" ${shownHint?'':'hidden'}>${mathText(s.hint)}</p>`:''}<button id="mathListen" class="math-listen">▶ 听一听题目</button><div class="cn-step-action"><button id="mathNext" class="cn-primary" ${s.itemKey&&!correct?'disabled':''}>${s.kind==='expression'?'我已尝试，继续':s.kind==='explore'?'我试过了，继续 →':'继续发现 →'}</button></div></section>`;
}
function answer(selected){const s=session?.steps[session.index];if(!s?.itemKey)return;stop();const result=recordAnswer(progress,session,s,selected,{hinted:usedHint()});if(!result){notice('请按题目要求填写答案。');return;}notice('');encouragement.answer(`${session.startedAt}:${s.id}`,result.correct,result.firstAttempt&&!result.hinted);save(result.firstAttempt?{contentId:session.lessonId,kind:'answer',result:{itemKey:result.itemKey,selected:result.selected,correct:result.correct,hinted:result.hinted}}:null);renderStep();}
function next(){const s=session?.steps[session.index];if(!s)return;if(!s.itemKey)recordAnswer(progress,session,s,s.kind==='expression'?{selfReported:true}:{visited:true});if(!advance(session))return;stop();widgetState=null;shownHint=false;save();renderStep();focusStep();}
function finish(){const active=session,l=LESSONS.find(l=>l.id===active.lessonId);if(!completeLesson(progress,active)){notice('学习位置已保留，请继续完成本课。');session=null;return home();}session=null;progress.session=null;save({contentId:l.id,kind:'completion',result:{session:active}});encouragement.complete(`${active.startedAt}:${l.id}`);const questions=Object.values(active.answers).filter(a=>a.latest),first=questions.filter(a=>a.correct&&!a.hinted).length;root.innerHTML=`<section class="math-finish"><span class="math-finish-symbol" aria-hidden="true">✦</span><span class="cn-kicker">自己的思考，又多了一点</span><h1>${active.review?'这次复习，完成了！':'这一课，完成了！'}</h1><p>${esc(l.goal)}</p><p>第一次独立答对 ${first} / ${questions.length} 道。提示和重试帮你找到的方法，隔一天再想想。</p><button id="mathHome" class="cn-primary">回到数学旅程 →</button></section>`;}
function directory(unit){dialog.innerHTML=`<div class="cn-dialog-heading"><h2>我的数学小课</h2><button id="closeDirectory" autofocus>关闭</button></div><p>${LESSONS.length} 个小课 · 从观察到推理</p>${COURSE.units.map(u=>`<section id="dir-${u.id}"><h3>${u.number?`第 ${u.number} 单元`:'数学活动'} · ${esc(u.title)}</h3><div class="cn-directory-list">${LESSONS.filter(l=>l.unitId===u.id).map(l=>`<button data-lesson="${l.id}"><strong>${esc(l.title)}</strong><small>第${l.pages[0]}—${l.pages.at(-1)}页 ${progress.lessons[l.id]?.completed?'· 已学':''}</small></button>`).join('')}</div></section>`).join('')}`;dialog.showModal();if(unit)dialog.querySelector(`#dir-${unit}`)?.scrollIntoView({block:'start'});}
root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.id==='mathNetPause')return pauseNet();if(b.dataset.widgetPaint!==undefined){if(widgetState&&updateWidget(widgetState,'paint',b.dataset.widgetPaint))root.querySelector('.math-widget').outerHTML=renderWidget(widgetState);return;}if(b.dataset.unit)return directory(b.dataset.unit);if(b.dataset.answer!==undefined)return answer(session.steps[session.index].choices[Number(b.dataset.answer)]);if(b.dataset.widgetSet){const from=widgetState?.foldPosition??widgetState?.fold;if(widgetState&&updateWidget(widgetState,b.dataset.widgetSet,b.dataset.value)){root.querySelector('.math-widget').outerHTML=renderWidget(widgetState);if(b.dataset.widgetSet==='fold')animateNet(from,widgetState.fold);}return;}switch(b.id){case'startMath':return start();case'mathExit':case'mathHome':return home();case'mathNext':return next();case'mathDirectory':return directory();case'mathHint':shownHint=!shownHint;if(shownHint){hinted.add(hintKey());try{storage.setItem(hintKey(),'1');}catch{}}return renderStep();case'mathListen':{stopEncouragement();const s=session.steps[session.index];return reader.speak((s.prompt||s.text||'').replace(/(\d+)\/(\d+)/g,(_,n,d)=>`${d}分之${n}`).replaceAll('+','加').replaceAll('×','乘以').replaceAll('÷','除以').replaceAll('＝','等于').replaceAll('−','减'));}case'mathReview':{const keys=dueItems(progress).filter(k=>progress.lessons[k.split(':')[0]]?.completed);const l=LESSONS.find(l=>buildSteps(l).some(s=>keys.includes(s.itemKey)));if(l)return start(l.id,{review:true,reviewKeys:keys});}}});
root.addEventListener('change',e=>{const field=e.target.dataset.widgetField;if(field&&widgetState){if(updateWidget(widgetState,field,e.target.value)){root.querySelector('.math-widget').outerHTML=renderWidget(widgetState);root.querySelector(`[data-widget-field="${field}"]`)?.focus({preventScroll:true});}else{notice('请在标出的范围内选择数据；尺子的右端要在左端后面。');e.target.value=widgetState[field];}}});
root.addEventListener('submit',e=>{if(e.target.id==='mathAnswerForm'){e.preventDefault();answer(new FormData(e.target).get('answer'));}});
dialog.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='closeDirectory')return dialog.close();if(b.dataset.lesson){dialog.close();start(b.dataset.lesson);}});
const course={root,lessons:LESSONS,get progress(){return progress},get session(){return session},get storageKey(){return storageKey},save,home,start,snapshot:()=>JSON.parse(JSON.stringify(progress)),replaceProgress};window.mathCourse=course;
document.querySelector('#mathStop').onclick=()=>reader.cancel();function muteLabel(){const b=document.querySelector('#mathMute');b.textContent=`鼓励声音：${encouragement.muted?'关':'开'}`;b.setAttribute('aria-pressed',String(encouragement.muted));}document.querySelector('#mathMute').onclick=()=>{encouragement.toggle();muteLabel();};muteLabel();
mountClassroomNav({subject:'math',beforeLeave:()=>{save();stop();}});home();cloud=mountFamily({course,root:document.querySelector('#familyBar'),notice});window.mathCourseCloud=cloud;addEventListener('pagehide',()=>{save();stop();});document.addEventListener('visibilitychange',()=>{if(document.hidden){save();stop();}});
