import {evaluateExpression,expressionTrace,multiplicationTrace,convertLength,classifyAngle,groupShare,projectBlocks} from './models.js';
import {escapeHTML as esc} from '../shared/family-client.js';
import {foldNet} from './geometry.js';
const colors=['#e4aa67','#82b6a4','#9ebbd3','#d88e95','#b7a3d0','#e6c66e'];
const svg=(body,label,view='0 0 420 230')=>`<svg viewBox="${view}" role="img" aria-label="${esc(label)}">${body}</svg>`;
const text=(x,y,value,extra='')=>`<text x="${x}" y="${y}" ${extra}>${esc(String(value))}</text>`;
const number=(key,label,value,min,max,step=1)=>`<label>${label}<input data-widget-field="${key}" type="number" min="${min}" max="${max}" step="${step}" value="${value}"></label>`;
const button=(key,value,label,current)=>`<button type="button" data-widget-set="${key}" data-value="${value}" aria-pressed="${String(current===value)}">${label}</button>`;
export function netDiagram(s,t=s.foldPosition??s.fold){const w=s.solid==='cuboid'?1.6:1,d=s.solid==='cuboid'?.7:1,scale=Math.min(82,350/(2*w+2*d));const project=([x,y,z])=>[100+(x*.85+z*.65*t)*scale,85+(y*.85-x*.22*t-z*.38*t)*scale];const faces=foldNet(s.solid,t),order=[4,5,1,3,0,2];let p='';for(const i of order){const face=faces[i],points=face.points.map(project),cx=points.reduce((a,v)=>a+v[0],0)/4,cy=points.reduce((a,v)=>a+v[1],0)/4;p+=`<polygon points="${points.map(p=>p.join(',')).join(' ')}" fill="${colors[face.color]}" stroke="#395d55" stroke-width="1.7"/>${text(cx,cy+4,face.name,'text-anchor="middle"')}`;}return svg(p,`${s.solid==='cube'?'正方体':'长方体'}的六个面沿共同边折叠，当前折叠进度${Math.round(t*100)}%`);}
const names={mm:'毫米',cm:'厘米',dm:'分米',m:'米',km:'千米'};
function lengthDescription(value,from,to){const converted=convertLength(value,from,to);if(Number.isInteger(converted))return `${converted}${names[to]}`;const ratio=convertLength(1,to,from);return `${Math.floor(converted)}${names[to]}又${value%ratio}${names[from]}`;}
function massDescription(grams){const kg=Math.floor(grams/1000),g=grams%1000;const tonne=Math.floor(grams/1000000),remaining=grams%1000000;return `${kg?kg+'千克':''}${g?g+'克':kg?'':'0千克'}；${tonne?tonne+'吨'+(remaining?'又'+remaining+'克':''):'不足1吨'}`;}
export function initialWidget(config={}){return {type:config.type,...({view:{blocks:[[0,0,0],[1,0,0],[0,0,1]],direction:'front'},order:{expression:'24−13+18',revealed:0},ruler:{startMm:12,endMm:38},units:{value:3,from:'cm',to:'mm'},mass:{grams:1200,added:0},multiply:{a:24,b:9,revealed:0},code:{prefix:'2601',serial:3},angle:{degrees:60,length:110,rotation:0},fraction:{numerator:1,denominator:4,shape:'bar'},groups:{total:12,numerator:1,denominator:3},match:{tops:2,bottoms:3,selected:0},net:{solid:'cube',fold:0}}[config.type]||{}),...config};}
export function fractionDiagram(n,d,shape='bar',painted=null){
 const filled=i=>painted?painted.includes(i):i<n;
 if(shape==='circle'){const cx=210,cy=112,r=86;let p='';for(let i=0;i<d;i++){const a=-Math.PI/2+2*Math.PI*i/d,b=-Math.PI/2+2*Math.PI*(i+1)/d;const x1=cx+r*Math.cos(a),y1=cy+r*Math.sin(a),x2=cx+r*Math.cos(b),y2=cy+r*Math.sin(b);p+=`<path d="M${cx},${cy} L${x1},${y1} A${r},${r} 0 ${d===1?1:0} 1 ${x2},${y2} Z" fill="${filled(i)?'#80b5a2':'#fcfaf4'}" stroke="#395d55" stroke-width="2"/>`;}if(d===1)p=`<circle cx="210" cy="112" r="86" fill="${n?'#80b5a2':'#fcfaf4'}" stroke="#395d55" stroke-width="2"/>`;return svg(p,`一个圆平均分成${d}份，其中${n}份涂色`);}
 let p='';for(let i=0;i<d;i++)p+=`<rect x="${30+360*i/d}" y="58" width="${360/d}" height="112" fill="${filled(i)?'#80b5a2':'#fcfaf4'}" stroke="#395d55" stroke-width="2"/>`;return svg(p,`同一个长方形平均分成${d}份，其中${n}份涂色`);
}
function viewDiagram(s){
 const cells=projectBlocks(s.blocks,s.direction),maxX=Math.max(...cells.map(c=>c[0])),maxY=Math.max(...cells.map(c=>c[1]));const scale=Math.min(56,310/(maxX+1),175/(maxY+1));const ox=210-(maxX+1)*scale/2,oy=195;
 return svg(cells.map(([x,y])=>`<rect x="${ox+x*scale}" y="${oy-(y+1)*scale}" width="${scale}" height="${scale}" rx="2" fill="#87b4a2" stroke="#395d55" stroke-width="2"/>`).join(''),`从${{front:'正面',right:'右面',top:'上面'}[s.direction]}观察，投影有${cells.length}个小方格`);
}
function sceneBlocks(blocks){
 const occupied=new Set(blocks.map(b=>b.join(','))),project=([x,y,z])=>[x+.65*y,.26*x-.4*y-z];const points=blocks.flatMap(([x,y,z])=>[[x,y,z],[x+1,y,z],[x,y+1,z],[x+1,y+1,z],[x,y,z+1],[x+1,y,z+1],[x,y+1,z+1],[x+1,y+1,z+1]]).map(project),xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),scale=Math.min(70,300/(maxX-minX),165/(maxY-minY));const screen=v=>{const [x,y]=project(v);return [210+(x-(minX+maxX)/2)*scale,120+(y-(minY+maxY)/2)*scale];};let body='';
 const sorted=[...blocks].sort((a,b)=>(.65*a[0]-a[1]+.57*a[2])-(.65*b[0]-b[1]+.57*b[2]));
 for(const [x,y,z] of sorted){const faces=[{neighbor:[x,y-1,z],color:'#80b5a2',corners:[[x,y,z],[x+1,y,z],[x+1,y,z+1],[x,y,z+1]]},{neighbor:[x+1,y,z],color:'#d5a777',corners:[[x+1,y,z],[x+1,y+1,z],[x+1,y+1,z+1],[x+1,y,z+1]]},{neighbor:[x,y,z+1],color:'#e8ca94',corners:[[x,y,z+1],[x+1,y,z+1],[x+1,y+1,z+1],[x,y+1,z+1]]}];for(const face of faces)if(!occupied.has(face.neighbor.join(',')))body+=`<polygon points="${face.corners.map(screen).map(p=>p.join(',')).join(' ')}" fill="${face.color}" stroke="#395d55" stroke-width="1.5"/>`;}
 return svg(body+text(150,220,'正面')+text(335,155,'右面')+text(220,18,'上面'),`由${blocks.length}个相同小正方体组成的物体，图中右侧为右面`);
}
function ruler(s){let p=`<path d="M20 78H400V143H20Z" fill="#f4dfad" stroke="#90764a"/>`;for(let i=0;i<=50;i++){const x=20+7.6*i;p+=`<path d="M${x} 78V${i%10===0?112:i%5===0?101:92}" stroke="#625d4d"/>`;if(i%10===0)p+=text(x,133,i/10,'text-anchor="middle"');}p+=`<path d="M${20+s.startMm*7.6} 57H${20+s.endMm*7.6}" stroke="#688fbd" stroke-width="12" stroke-linecap="butt"/>`;
 return svg(p+text(20+s.startMm*7.6,39,`${s.startMm}毫米`,'text-anchor="middle"')+text(20+s.endMm*7.6,39,`${s.endMm}毫米`,'text-anchor="middle"'),`物体左端${s.startMm}毫米，右端${s.endMm}毫米；示意尺每厘米有10毫米`);
}
function angle(s){const radians=s.degrees*Math.PI/180,ox=205,oy=115,l=s.length||110;return svg(`<g transform="rotate(${s.rotation||0} ${ox} ${oy})"><path d="M${ox+l} ${oy}H${ox}L${ox+l*Math.cos(radians)} ${oy-l*Math.sin(radians)}" fill="none" stroke="#395d55" stroke-width="4"/><path d="M${ox+36} ${oy} A36 36 0 0 0 ${ox+36*Math.cos(radians)} ${oy-36*Math.sin(radians)}" fill="none" stroke="#d7975c" stroke-width="3"/><circle cx="${ox}" cy="${oy}" r="4" fill="#395d55"/>${text(ox+6,oy+23,'顶点')}</g>`,`${s.degrees}度的${classifyAngle(s.degrees)}。边的显示长度与旋转方向不影响开口大小`);}
function groups(s){const g=groupShare(s.total,s.numerator,s.denominator);const cols=Math.min(6,g.perGroup),r=Math.ceil(g.perGroup/cols),cell=25,groupW=cols*cell+16;let body='';for(let k=0;k<s.denominator;k++){const x=16+(k%2)*groupW,y=20+Math.floor(k/2)*(r*cell+35);body+=`<rect x="${x}" y="${y}" width="${groupW-8}" height="${r*cell+15}" rx="8" fill="${k<s.numerator?'#deeee5':'#faf7ef'}" stroke="#b0c4b7"/>`;for(let i=0;i<g.perGroup;i++)body+=`<circle cx="${x+14+(i%cols)*cell}" cy="${y+15+Math.floor(i/cols)*cell}" r="7" fill="${k<s.numerator?'#65977c':'#b9c2b9'}"/>`;}
 return svg(body,`${s.total}个物体平均分成${s.denominator}组，选其中${s.numerator}组，每组${g.perGroup}个`,`0 0 ${2*groupW+20} ${Math.ceil(s.denominator/2)*(r*cell+35)+10}`);
}
export function renderWidget(state,{interactive=true}={}){
 const s=state,type=s.type;let art='',controls='',result='',caption='';const controlsOn=interactive;
 try{
 if(type==='view'){art=`<div class="math-view-pair">${sceneBlocks(s.blocks)}${viewDiagram(s)}</div>`;controls=['front','right','top'].map(v=>button('direction',v,{front:'正面',right:'右面',top:'上面'}[v],s.direction)).join('');controls+='<button data-widget-set="move" data-value="1">移动最后一个方块</button>';caption='换一个观察位置，看投影会怎样改变。投影中的重叠方块只显示一次。';}
 if(type==='order'){const stages=expressionTrace(s.expression),shown=Math.min(s.revealed,stages.length);art=`<div class="math-equation">${esc(s.expression)}</div><ol class="math-carry">${stages.slice(0,shown).map(step=>`<li>先算 ${esc(step.operation)} = ${step.result}<br>${esc(step.before)} = ${esc(step.after)}</li>`).join('')}</ol>`;controls=`<label>试一个新算式<input data-widget-field="expression" type="text" maxlength="50" value="${esc(s.expression)}" aria-label="尝试新的混合算式"></label>`+button('revealed',Math.min(shown+1,stages.length),'展示下一步',shown)+button('revealed',0,'重新思考',shown);result=shown===stages.length?`结果：${evaluateExpression(s.expression)}`:'先找括号，再找乘除，最后按顺序算加减。';caption='先说说第一步要算什么，再一步一步核对。输入 ×、÷ 或 *、/ 都可以。';}
 if(type==='ruler'){art=ruler(s);controls=number('startMm','左端刻度（毫米）',s.startMm,0,49)+number('endMm','右端刻度（毫米）',s.endMm,1,50);result=`长度：${s.endMm} − ${s.startMm} = ${s.endMm-s.startMm} 毫米`;caption='这是一把放大的示意尺。真实测量请使用自己的直尺。';}
 if(type==='units'){art=`<div class="math-equation">${s.value}${names[s.from]} <span>＝</span> ${lengthDescription(s.value,s.from,s.to)}</div>`;controls=number('value','数量',s.value,0,10000)+['from','to'].map(k=>`<label>${k==='from'?'原单位':'换成'}<select data-widget-field="${k}">${['mm','cm','dm','m','km'].map(u=>`<option ${s[k]===u?'selected':''} value="${u}">${{mm:'毫米',cm:'厘米',dm:'分米',m:'米',km:'千米'}[u]}</option>`).join('')}</select></label>`).join('');caption='长度没有改变，表示它的数和单位一起改变了。';}
 if(type==='mass'){const tilt=s.grams===s.added?0:Math.sign(s.grams-s.added)*18,yL=120+tilt,yR=120-tilt;art=svg(`<path d="M80 ${yL}L340 ${yR}M210 80V202M150 202H270" stroke="#5b7569" stroke-width="5" fill="none"/><path d="M80 ${yL}v18l-28 32h56l-28-32M340 ${yR}v18l-28 32h56l-28-32" fill="#e5cfab" stroke="#786a50"/>${text(80,yL-12,`${s.grams}克`,'text-anchor="middle"')}${text(340,yR-12,`${s.added}克`,'text-anchor="middle"')}`,`左边${s.grams}克，右边添加${s.added}克；${s.grams===s.added?'两边相等':'较重的一边下降'}`);controls=number('grams','左边质量（克）',s.grams,0,10000000)+[100,500,1000,1000000].map(n=>button('added',s.added+n,`加${n===1000000?'1吨':n+'克'}`,s.added)).join('')+button('added',0,'清空右边',s.added);result=`${s.grams}克：${massDescription(s.grams)}。${s.grams===s.added?'两边质量相等了。':`右边${s.added}克，${s.added<s.grams?'还轻':'更重'}。`}`;caption='较重的一边下降；相等时横梁水平。单位换了，表示的质量没有改变。';}
 if(type==='multiply'){const trace=multiplicationTrace(s.a,s.b),shown=Math.min(s.revealed,trace.steps.length),width=Math.max(String(s.a).length,String(trace.result).length),partial=Array(width).fill('?'),carries=Array(width).fill(' ');for(let i=0;i<shown;i++){partial[width-1-i]=String(trace.steps[i].write);if(trace.steps[i].carryOut&&width-2-i>=0)carries[width-2-i]=String(trace.steps[i].carryOut);}const product=shown===trace.steps.length?String(trace.result).padStart(width,' '):partial.join('');const digits=value=>[...value.padStart(width,' ')].map(v=>`<span>${v===' '?'&nbsp;':esc(v)}</span>`).join('');art=`<div class="math-vertical" aria-label="按数位对齐的乘法竖式"><div class="math-carry-row">${digits(carries.join(''))}</div><div>${digits(String(s.a))}</div><div class="math-multiplier"><span>×</span><span>${s.b}</span></div><hr><div>${digits(product)}</div></div><ol class="math-carry">${trace.steps.slice(0,shown).map(c=>`<li>${esc(c.place===1?'个位':c.place===10?'十位':c.place===100?'百位':'千位')}：${c.digit} × ${s.b}${c.carryIn?` + 进来的 ${c.carryIn}`:''} = ${c.product}，写 ${c.write}${c.carryOut?`，向前一位进 ${c.carryOut}`:''}。</li>`).join('')}${shown===trace.steps.length&&trace.finalCarry?`<li>最高位还要写上进位 ${trace.finalCarry}。</li>`:''}</ol>`;controls=number('a','多位数',s.a,0,9999)+number('b','一位数',s.b,0,9)+button('revealed',Math.min(shown+1,trace.steps.length),'展示下一位',shown)+button('revealed',0,'重新演示',shown);caption='从个位开始，每次演示一个数位。小字是向前一位的进位，下面的数在对应位置写下。';}
 if(type==='code'){const serial=String(s.serial).padStart(2,'0');art=`<div class="math-code"><span>${esc(s.prefix.slice(0,2))}<small>入学年份后两位</small></span><span>${esc(s.prefix.slice(2))}<small>班级</small></span><span>${serial}<small>班内序号</small></span></div>`;controls=number('serial','虚构的班内序号',s.serial,1,99);caption='这是我们设计的虚构编号方案。开头的 0 也有意义，编号不是用于计算的数量。';}
 if(type==='angle'){art=angle(s);controls=`<label>改变开口<input type="range" data-widget-field="degrees" min="10" max="170" step="5" value="${s.degrees}"></label>`+button('degrees',90,'和直角比一比',s.degrees)+button('length',s.length===110?70:110,'改变边的显示长度',s.length)+button('rotation',((s.rotation||0)+45)%360,'转个方向',s.rotation);result=`开口 ${s.degrees}° · ${classifyAngle(s.degrees)}`;caption='角的大小由开口决定。转方向、改变边的显示长度，都不会改变开口。';}
 if(type==='fraction'){art=fractionDiagram(s.numerator,s.denominator,s.shape,s.painted);controls=number('denominator','平均分成几份',s.denominator,2,12)+number('numerator','取其中几份',s.numerator,0,s.denominator)+button('shape',s.shape==='bar'?'circle':'bar','换一种整体形状',s.shape)+`<div class="math-piece-controls">${Array.from({length:s.denominator},(_,i)=>`<button data-widget-paint="${i}" aria-pressed="${s.painted?s.painted.includes(i):i<s.numerator}">第${i+1}份 · ${(s.painted?s.painted.includes(i):i<s.numerator)?'已涂':'未涂'}</button>`).join('')}</div>`;result=`平均分成 ${s.denominator} 份，取 ${s.numerator} 份：${s.numerator}/${s.denominator}`;caption='点击每一份的按钮来涂色。每一份都要同样大，涂哪里不改变取了几份。';}
 if(type==='groups'){const g=groupShare(s.total,s.numerator,s.denominator);art=groups(s);controls=number('total','整体有几个',s.total,s.denominator,48,s.denominator)+number('numerator','取几组',s.numerator,0,s.denominator);result=`${s.total} ÷ ${s.denominator} = ${g.perGroup}，${g.perGroup} × ${s.numerator} = ${g.selected}（个）`;caption='把这组物体看成一个整体。先平均分组，再看取了几组。';}
 if(type==='match'){let p='';for(let i=0;i<s.tops;i++){p+=`<circle cx="${100+i*90}" cy="45" r="18" fill="${colors[i]}"/>`;p+=text(100+i*90,49,`上${i+1}`,'text-anchor="middle"');}for(let j=0;j<s.bottoms;j++){p+=`<rect x="${80+j*90}" y="150" width="40" height="40" fill="${colors[j+2]}" rx="5"/>`;p+=text(100+j*90,176,`下${j+1}`,'text-anchor="middle"');}for(let n=0;n<s.selected;n++){const i=Math.floor(n/s.bottoms),j=n%s.bottoms;p+=`<path class="math-draw-line" d="M${100+i*90} 65L${100+j*90} 145" stroke="${colors[i]}" stroke-width="3"/>`;}art=svg(p,`有${s.tops}件上衣和${s.bottoms}件下装，已找出${s.selected}种搭配`);controls=number('tops','上衣件数',s.tops,1,3)+number('bottoms','下装件数',s.bottoms,1,4)+button('selected',Math.min(s.selected+1,s.tops*s.bottoms),'找下一种搭配',s.selected)+button('selected',0,'重新连一连',s.selected);result=`已找到 ${s.selected} / ${s.tops*s.bottoms} 种。`;caption='固定一件上衣，依次搭配每一件下装，再换下一件上衣。';}
 if(type==='net'){art=`<div class="math-net-frame">${netDiagram(s)}</div>`;controls=button('fold',s.fold?0:1,s.fold?'慢慢展开':'慢慢合起来',s.fold)+'<button type="button" id="mathNetPause" disabled>暂停动画</button>';caption='六个面沿共同边转动，形状与边长不改变。“前”连接上、下、左、右；“后”连接右。';}
 }catch{result='请在标出的范围内选择数据。';}
 return `<section class="math-widget" data-widget="${esc(type)}">${art}${controlsOn?`<div class="math-widget-controls">${controls}</div>`:''}${result&&controlsOn?`<p class="math-widget-result" role="status">${esc(result)}</p>`:''}<p class="math-widget-caption">${esc(caption)}</p></section>`;
}
export function updateWidget(state,key,value){
 if(key==='move'){if(state.type!=='view')return false;const blocks=state.blocks.map(b=>[...b]),last=blocks.length-1;if(state.originalLast){blocks[last]=state.originalLast;state.originalLast=null;}else{state.originalLast=[...blocks[last]];let x=0;while(blocks.slice(0,-1).some(b=>b[0]===x&&b[1]===0&&b[2]===0))x++;blocks[last]=[x,0,0];}state.blocks=blocks;return true;}
 if(key==='expression'){if(typeof value!=='string'||value.length>50)return false;try{expressionTrace(value);}catch{return false;}state.expression=value;state.revealed=0;return true;}
 if(key==='paint'){const index=Number(value);if(state.type!=='fraction'||!Number.isInteger(index)||index<0||index>=state.denominator)return false;state.painted ||= Array.from({length:state.numerator},(_,i)=>i);state.painted=state.painted.includes(index)?state.painted.filter(i=>i!==index):[...state.painted,index];state.numerator=state.painted.length;return true;}
 const numeric=new Set(['startMm','endMm','value','grams','added','a','b','revealed','serial','degrees','length','rotation','numerator','denominator','total','selected','fold','tops','bottoms']);
 if(numeric.has(key)){value=Number(value);if(!Number.isSafeInteger(value))return false;const ranges={startMm:[0,49],endMm:[1,50],value:[0,10000],added:[0,10000000],grams:[0,10000000],a:[0,9999],b:[0,9],revealed:[0,10],serial:[1,99],degrees:[10,170],length:[50,110],rotation:[0,359],numerator:[0,state.denominator],denominator:[2,12],selected:[0,state.tops*state.bottoms],tops:[1,3],bottoms:[1,4],total:[state.denominator,48],fold:[0,1]};if(ranges[key]&&(value<ranges[key][0]||value>ranges[key][1]))return false;}
 else if(!({direction:['front','right','top'],shape:['bar','circle'],from:['mm','cm','dm','m','km'],to:['mm','cm','dm','m','km']}[key]||[]).includes(value))return false;
 if(key==='startMm'&&value>=state.endMm||key==='endMm'&&value<=state.startMm)return false;
 if(key==='total'&&value%state.denominator!==0)return false;state[key]=value;if(key==='tops'||key==='bottoms')state.selected=0;if(key==='a'||key==='b')state.revealed=0;if(key==='denominator'&&state.numerator>value)state.numerator=value;if(key==='denominator'||key==='numerator')state.painted=null;return true;
}
