import {COURSE,LESSONS} from './course-curriculum.js';
import {createSession,loadProgress,recordAnswer,dueItems,completeLesson,recommendLesson} from './course-engine.js';
import {courseArt,wordArt} from './course-art.js';
import {answerMatches} from './core.js';
import {BOOKS} from './curriculum.js';
import {pageTargets,getTarget} from './page-practice.js';
import {mountSpeaking} from './speaking.js';
const KEY='pearl-english-course-v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const unitArt=(unitId)=>{const n=Number(unitId.match(/u(\d+)/)?.[1]||1),label=['朋友在学校问好','一家人相互关爱','认识不同的动物','和家人照顾苹果树','绘画和大自然中的颜色','分享生日和数字的快乐'][n-1];return `<img class="course-illustration" src="${new URL(`illustrations/u${n}.webp`,import.meta.url).href}" alt="${label}" width="1536" height="1024" loading="lazy" decoding="async">`};
const lessonArt=lesson=>lesson.type==='story'?courseArt(lesson.unitId,{story:true}):unitArt(lesson.unitId);
const stages=['看图听一听','词语记一记','句子练一练','读读说说'];
const quizKinds=new Set(['listen','meaning','sentence','check']);
const READING_GROUP_SIZE=4;
export function mountCourse({root,speak,read,stopAudio,openPages,onReward,notice,onActivity=()=>{},onSave=()=>{}}){
 let raw;try{raw=localStorage.getItem(KEY);}catch{}
 let progress=loadProgress(raw,LESSONS),storageKey=KEY;let lesson=null,session=null,speaking=null,viewEpoch=0,readingGroup=0,readingKey=null;
 const sourcePages=BOOKS.find(book=>book.id==='g3-upper').textbookPages;
 function clearSpeaking(){viewEpoch++;speaking?.destroy();speaking=null;}
 function sourceTarget(entry,kind){if(!entry||!lesson)return null;const pages=lesson.pages.map(number=>sourcePages.find(page=>page.page===number));if(entry.page)pages.sort((a,b)=>(b?.page===entry.page)-(a?.page===entry.page));return pages.flatMap(pageTargets).find(target=>(!kind||target.kind===kind)&&target.en===entry.en&&(kind!=='word'||!entry.id||target.wordId===entry.id))??null;}
 function speakingButton(target,label){return target?`<button data-course-speaking="${esc(target.id)}" class="secondary course-speaking-link">${label}</button>`:'';}
 function oralTarget(){return sourceTarget(lesson.phrases.find(phrase=>phrase.en===lesson.activity.example)||{en:lesson.activity.example},'sentence')||sourceTarget(lesson.words[0],'word');}
 function markAttempt(){const step=current();if(step?.kind!=='oral')return;session.answers[step.id]={selfReported:true};save();const next=root.querySelector?.('#courseNext');if(next)next.disabled=false;}
 function openSourceSpeaking(id){const target=getTarget(id);if(!target||!lesson)return;clearSpeaking();stopAudio();openPages(target.page,lesson.unitId,{speakingTarget:id});}
 function resumeSpeaking(){const step=current();if(step?.kind!=='oral'||speaking)return;const target=oralTarget(),host=root.querySelector?.('#courseSpeaking'),activeSession=session,token=viewEpoch;if(target&&host)speaking=mountSpeaking({root:host,target,speak,stopAudio,onResult:()=>{if(token===viewEpoch&&session===activeSession&&current()?.id===step.id)markAttempt();}});}
 const api={get progress(){return progress},get lesson(){return lesson},get session(){return session},get storageKey(){return storageKey},home,start,save,resumeSpeaking,snapshot:()=>JSON.parse(JSON.stringify(progress)),replaceProgress};window.englishCourse=api;
 function save(event=null){if(session)progress.session=session;try{localStorage.setItem(storageKey,JSON.stringify(progress));}catch{notice('学习进度暂时无法保存，请保持页面打开。');}onSave({progress:JSON.parse(JSON.stringify(progress)),event});}
 function replaceProgress(raw,{storageKey:nextKey=KEY,preserveView=false}={}){
  const incoming=loadProgress(raw,LESSONS),nextSession=incoming.session;
  const sameSession=preserveView&&nextKey===storageKey&&session&&nextSession&&session.lessonId===nextSession.lessonId&&session.startedAt===nextSession.startedAt&&session.seed===nextSession.seed&&session.review===nextSession.review&&session.index===nextSession.index;
  if(!sameSession)clearSpeaking();if(!preserveView)stopAudio();storageKey=nextKey;progress=incoming;
  if(preserveView&&lesson){if(session&&nextSession){if(sameSession){Object.assign(session,nextSession);progress.session=session;}else{session=nextSession;lesson=LESSONS.find(l=>l.id===session.lessonId);render();}}else if(session&&!nextSession){session=null;lesson=null;home();}return;}session=null;lesson=null;home({preserveAudio:preserveView});
 }
 function home({preserveAudio=false}={}){readingGroup=0;readingKey=null;root.classList.remove('course-learning');clearSpeaking();onActivity(false);if(session)save();if(!preserveAudio)stopAudio();lesson=null;session=null;const resume=progress.session,done=LESSONS.filter(l=>progress.lessons[l.id]?.completed).length,recommended=recommendLesson(LESSONS,progress),due=dueItems(progress).length;
  root.innerHTML=`<div class="course-heading"><div><span class="course-kicker">PEARL ENGLISH CLASSROOM</span><h1>学会一点，<br>再开口说一点。</h1><p>三年级上册 · ${esc(COURSE.edition)}<br>看图、听读、练习、表达，一步一步来。</p></div><div class="course-hero-art">${unitArt(recommended?.unitId||LESSONS[0].unitId)}<span>今天也来认识一点新英语</span></div></div><div class="course-today"><div><span class="course-kicker">${resume?'继续上次的小课':'从这里开始'}</span><h2>${esc((resume&&LESSONS.find(l=>l.id===resume.lessonId)||recommended)?.title||'课程小复习')}</h2><p>约15—20分钟 · 不计时，按自己的节奏学</p></div><div class="course-today-actions"><button id="startCourse" class="primary">${resume?'继续学习':'开始今天的小课'} <span>→</span></button><button id="courseTextbook" class="secondary">课本逐页练习 ↗</button></div></div><div class="course-summary"><span>已完成 <strong>${done}</strong> / ${LESSONS.length} 小课</span><progress value="${done}" max="${LESSONS.length}" aria-label="课程完成进度"></progress><button id="reviewCourse" class="secondary">${due?`复习 ${due} 项学过的内容`:'看看复习安排'}</button></div><div class="course-map-title"><h2>我们的英语旅程</h2><p>建议从第一课开始，也可以选课重学</p></div><div class="course-map">${COURSE.units.map((unit,i)=>`<section class="course-unit">${unitArt(unit.id)}<div class="course-unit-top"><span class="course-unit-icon" aria-hidden="true">${unit.icon}</span><div><small>UNIT ${i+1}</small><h3>${esc(unit.title)}</h3><p>${esc(unit.description)}</p></div></div><div class="course-lessons">${unit.lessons.map(l=>`<button data-course-lesson="${l.id}" class="course-lesson ${progress.lessons[l.id]?.completed?'done':''}"><span class="course-lesson-number">${progress.lessons[l.id]?.completed?'✓':l.number}</span><span><strong>${esc(l.title)}</strong><small>${esc(l.goal)}</small></span><span class="course-lesson-arrow">${l.type==='phonics'?'Aa':l.type==='story'?'📖':'→'}</span></button>`).join('')}</div></section>`).join('')}</div><div class="course-helper"><strong>课堂怎么学？</strong><p>先看图片和听声音，再自己选答案。遇到新句子可看解释，也可多听几遍。最后试着说一说，和家人做个小活动。</p><small>已学内容安排在1、3、7天后复习。答错的会优先再练。</small></div>`;
 }
 function start(id=null,{review=false}={}){readingGroup=0;readingKey=null;stopAudio();const stored=progress.session;lesson=LESSONS.find(l=>l.id===(id||stored?.lessonId))||recommendLesson(LESSONS,progress)||LESSONS[0];session=!id&&stored?stored:createSession(lesson,{review});progress.session=session;save();render();onActivity(!!session);scrollToCurrentStep();}
 function review(){const keys=dueItems(progress);if(!keys.length){const next=Object.values(progress.items).map(i=>i.nextReview).filter(Number.isFinite).sort((a,b)=>a-b)[0];notice(next?`下一次复习：${new Date(next).toLocaleDateString('zh-CN')}。也可以选一课再练。`:'先完成一节小课，学过的词句就会进入复习安排。');return;}
  const candidate=LESSONS.find(l=>keys.some(k=>k.startsWith(`${l.id}:`)));
  if(!candidate)return;stopAudio();lesson=candidate;session=createSession(candidate,{review:true,reviewKeys:keys});save();render();onActivity(!!session);

 }
 function current(){return session?.steps[session.index];}
 function scrollToCurrentStep(){const anchor=globalThis.innerWidth<=1100&&current()?.kind==='reading'?root.querySelector('.course-card'):root;(anchor||root).scrollIntoView({block:'start',behavior:'instant'});}
 function voice(){const step=current();if(!step)return;if(step.kind==='word')return speak(step.word,step.word.id);if(step.kind==='phrase'||step.kind==='sentence')return speak(step.phrase??{en:step.answer});if(step.kind==='reading')return read(step.lines.slice(readingGroup*READING_GROUP_SIZE,(readingGroup+1)*READING_GROUP_SIZE));if(step.kind==='letters')return read(step.letters.map(l=>({en:l.en,say:l.say})));if(step.say)return speak(typeof step.say==='string'?step.say:step.say,step.word?.id);if(step.word)return speak(step.word,step.word.id);}
 function feedback(step){const f=session.feedback;return f?.stepId===step.id?`<div class="course-feedback ${f.correct?'right':'retry'}" role="status"><strong>${f.correct?'答对了，继续试试！':'再听一听、看一看。'}</strong><p>${esc(f.correct?step.why||'你已经找到这句话的意思了。':step.why||'可以回想刚才的图片和声音，再选一次。')}</p>${!f.correct?'<small>这项会加入复习，慢慢来就好。</small>':''}</div>`:'';}
 function render(){clearSpeaking();const step=current();if(!step)return finish();root.classList.add('course-learning');if(step.kind==='reading'){const key=`${storageKey}:${session.startedAt}:${session.seed}:${step.id}`;if(key!==readingKey){readingGroup=0;readingKey=key;}readingGroup=Math.min(readingGroup,Math.max(0,Math.ceil(step.lines.length/READING_GROUP_SIZE)-1));}else{readingGroup=0;readingKey=null;}const stage=Math.min(3,step.stage??0),isQuiz=quizKinds.has(step.kind),f=session.feedback?.stepId===step.id?session.feedback:null;
  let body='';
  if(step.kind==='word'){const w=step.word;body=`<div class="course-word"><span class="course-word-picture" role="img" aria-label="${esc(w.zh)}">${wordArt(w)||w.visual||'✦'}</span><span class="course-kicker">看图认识一个词</span><h2>${esc(w.en)}</h2><span class="course-ipa">${esc(w.ipa)}</span><p>${esc(w.zh)}</p><small>听一遍，再自己跟着说一遍。</small>${speakingButton(sourceTarget(w,'word'),'读这个词')}</div>`;}
  else if(step.kind==='phrase'){const p=step.phrase;body=`${lessonArt(lesson)}<div class="course-phrase"><span class="course-kicker">把词放进句子里</span><h2>${esc(p.en)}</h2><p>${esc(p.zh)}</p>${p.tip?`<div class="course-tip">${esc(p.tip)}</div>`:''}<small>先听原句，再换成自己的名字或喜欢的东西试着说。</small>${speakingButton(sourceTarget(p,'sentence'),'读这句话')}</div>`;}
  else if(step.kind==='letters'){body=`<h2>字母有名字，也有声音</h2><p>点击听字母名称，再听例词中的声音。</p><div class="course-letter-grid">${step.letters.map(l=>`<div><strong>${esc(l.en)}</strong><span>${esc(l.ipa)}</span><small>例词 ${esc(l.example)} · ${esc(l.sound)}</small><button data-letter-example="${esc(l.example)}" class="listen-button">听例词</button></div>`).join('')}</div><div class="course-tip">字母名称和它在单词里的发音可能不同，用例词来感受。</div>`;}
  else if(step.kind==='sentence'){const phrase=step.phrase??{en:step.answer,zh:step.prompt};body=`<span class="course-kicker">把句子搭起来</span><h2>${esc(step.prompt||phrase.zh)}</h2><p>先听句子，再按顺序点词块。</p><div class="course-built">${(session.picked||[]).map((n,i)=>`<button data-course-remove="${i}" class="course-token">${esc(step.tokens[n])}</button>`).join('')||'<span>点下面的词块，放到这里</span>'}</div><div class="course-tokens">${step.tokens.map((t,i)=>`<button data-course-token="${i}" class="course-token" ${(session.picked||[]).includes(i)?'disabled':''}>${esc(t)}</button>`).join('')}</div><button id="courseCheckSentence" class="secondary" ${(session.picked||[]).length===step.tokens.length?'':'disabled'}>检查这句话</button>${feedback(step)}`;}
  else if(isQuiz){body=`<span class="course-kicker">${step.kind==='listen'?'耳朵小挑战':step.kind==='meaning'?'词义小挑战':'读懂小挑战'}</span><h2>${esc(step.prompt||'听声音，选出正确的词')}</h2>${step.kind==='meaning'&&step.word?`<div class="course-question-word">${esc(step.word.en)}</div>`:''}<div class="course-choices">${step.choices.map(c=>`<button data-course-answer="${esc(c)}" class="course-choice" ${f?.correct?'disabled':''}>${esc(c)}</button>`).join('')}</div>${feedback(step)}`;}
  else if(step.kind==='reading'){const start=readingGroup*READING_GROUP_SIZE,end=Math.min(start+READING_GROUP_SIZE,step.lines.length);body=`${lessonArt(lesson)}<h2>现在，我们读一小段</h2><p>听这几句，再试着自己读。遇到难词可以多听。</p><div class="course-reading-tools"><span class="course-reading-progress" role="status">第 ${start+1}—${end} 句 / 共 ${step.lines.length} 句</span><button id="courseReadingPrevious" class="text-button" ${readingGroup?'':'disabled'}>← 上几句</button><button id="courseListenAll" class="text-button">🔊 听全文</button></div><div class="course-reading">${step.lines.slice(start,end).map((l,i)=>`<div><div class="course-reading-text"><strong>${esc(l.en)}</strong><p>${esc(l.zh)}</p></div><div class="course-reading-actions"><button data-course-line="${start+i}" class="listen-button" aria-label="朗读第${start+i+1}句">🔊 听这一句</button>${speakingButton(sourceTarget(l,'sentence'),'读这句话')}</div></div>`).join('')}</div>`;}
  else if(step.kind==='oral'){const a=lesson.activity;body=`${lessonArt(lesson)}<span class="course-kicker">轮到你来试一试</span><h2>${esc(a.title)}</h2><p>${esc(a.prompt)}</p>${a.example?`<div class="course-tip">可以从这句话开始：<strong>${esc(a.example)}</strong></div>`:''}${oralTarget()?'<div id="courseSpeaking" class="course-speaking-practice"></div>':''}<p class="course-quiet-note">先录一遍课本里的词句，也可以和家人完成上面的小活动。这里记录一次尝试。</p><button id="courseOral" class="secondary">我已和家人完成活动</button>`;}
  root.innerHTML=`<div class="course-class-top"><button id="courseExit" class="text-button">← 保存并回到课程</button><span>UNIT ${Number(lesson.unitId.match(/u(\d+)/)?.[1])} · 第${lesson.number}课</span><button id="courseOpenPage" class="text-button">课本 ${lesson.pages[0]}页 ↗</button></div><div class="course-stage-bar">${stages.map((name,i)=>`<span class="${i===stage?'active':i<stage?'passed':''}">${i+1} ${name}</span>`).join('')}</div><div class="course-class-layout"><aside class="course-class-aside">${unitArt(lesson.unitId)}<span class="course-kicker">${session.review?'温习学过的内容':'今天的小目标'}</span><h2>${esc(lesson.title)}</h2><p>${esc(lesson.goal)}</p><div class="course-step-count">第${session.index+1}步 / ${session.steps.length}步</div><progress value="${session.index}" max="${session.steps.length}"></progress><p>约15—20分钟<br>随时可以停下来，下次接着学。</p></aside><section class="course-card">${body}<div class="course-class-actions"><button id="courseListen" class="listen-button" ${(step.kind==='oral'&&(!lesson.activity.example||oralTarget()))||(step.kind==='check'&&!step.say)?'hidden':''}>🔊 ${step.kind==='reading'?'听这几句':step.kind==='letters'?'听字母名称':'听美式发音'}</button><button id="courseStop" class="text-button" hidden>停止朗读</button><button id="courseNext" class="primary" ${isQuiz&&!f?.correct||step.kind==='oral'&&!session.answers[step.id]?'disabled':''}>${step.kind==='reading'&&(readingGroup+1)*READING_GROUP_SIZE<step.lines.length?'再读几句 →':session.index===session.steps.length-1?'完成这节课':'下一步 →'}</button></div></section></div>`;
  resumeSpeaking();
 }
 function answer(value){const step=current();if(!quizKinds.has(step.kind))return;const correct=answerMatches(step,value);
  let event=null;if(!session.answers[step.id]){session.answers[step.id]={correct,hinted:false};if(step.itemKey){recordAnswer(progress,step.itemKey,correct);event={contentId:lesson.id,kind:'answer',result:{itemKey:step.itemKey,correct,hinted:false}};}}
  session.feedback={stepId:step.id,correct,selected:value,why:step.why||''};save(event);render();
 }
 function moveReadingGroup(direction){const step=current();if(step?.kind!=='reading')return;const nextGroup=readingGroup+direction;if(nextGroup<0||nextGroup>=Math.ceil(step.lines.length/READING_GROUP_SIZE))return;stopAudio();readingGroup=nextGroup;render();root.querySelector('.course-reading-tools')?.scrollIntoView({block:'start',behavior:'instant'});}
 function next(){const step=current();if(!step)return;if(step.kind==='reading'&&(readingGroup+1)*READING_GROUP_SIZE<step.lines.length)return moveReadingGroup(1);if(quizKinds.has(step.kind)&&!session.feedback?.correct)return;if(step.kind==='oral'&&!session.answers[step.id])return;stopAudio();session.index++;session.feedback=null;session.picked=[];save();render();scrollToCurrentStep();}
 function finish(){root.classList.remove('course-learning');clearSpeaking();onActivity(false);stopAudio();const wasReview=session.review,first=completeLesson(progress,session);if(first&&!wasReview)onReward(lesson.id);const completed=lesson,next=LESSONS[LESSONS.indexOf(lesson)+1],event={contentId:lesson.id,kind:'completion',result:{session:JSON.parse(JSON.stringify(session))}};session=null;progress.session=null;save(event);root.innerHTML=`<div class="course-finished">${courseArt(completed.unitId,{story:completed.type==='story'})}<span class="course-kicker">今天又向前走了一小步</span><h1>${wasReview?'这次复习，完成了！':'这一课，完成了！'}</h1><p>${esc(completed.goal)}</p><div class="course-tip">新词和句子已经进入复习安排。过几天再认一认、说一说。</div><p>${wasReview?'学过的内容又练了一遍。':'记住词句需要多次练习。完成了一课，再隔一天试着回忆。'}</p><button id="courseFinishHome" class="primary">回到课程旅程</button>${next?`<button data-course-lesson="${next.id}" class="secondary">下一课：${esc(next.title)}</button>`:''}</div>`;}
 root.addEventListener('click',e=>{const t=e.target.closest('button');if(!t||t.disabled)return;if(t.dataset.courseSpeaking)return openSourceSpeaking(t.dataset.courseSpeaking);if(t.dataset.courseLesson)return start(t.dataset.courseLesson);if(t.dataset.courseAnswer!==undefined)return answer(t.dataset.courseAnswer);if(t.dataset.courseToken!==undefined){session.picked??=[];session.picked.push(Number(t.dataset.courseToken));session.feedback=null;save();return render();}if(t.dataset.courseRemove!==undefined){session.picked.splice(Number(t.dataset.courseRemove),1);session.feedback=null;save();return render();}if(t.dataset.letterExample)return speak(t.dataset.letterExample);if(t.dataset.courseLine!==undefined)return speak(current().lines[Number(t.dataset.courseLine)]);
  ({startCourse:()=>start(),reviewCourse:review,courseTextbook:()=>openPages(2,'g3-upper-u1'),courseExit:()=>{save();home();},courseFinishHome:home,courseListen:()=>current().kind==='oral'?speak(lesson.activity.example):voice(),courseStop:stopAudio,courseNext:next,courseReadingPrevious:()=>moveReadingGroup(-1),courseListenAll:()=>read(current().lines),courseCheckSentence:()=>answer(session.picked.map(i=>current().tokens[i]).join(' ')),courseOral:markAttempt,courseOpenPage:()=>{clearSpeaking();stopAudio();openPages(lesson.pages[0],lesson.unitId);}})[t.id]?.();
 });
 addEventListener('pagehide',()=>{clearSpeaking();if(session)save();});home();return api;
}
