import {familyRequest,browserStorage} from '../shared/family-client.js';
export const guestStorageKey='pearl-english-course-v1';
export const profileStorageKey=(owner,id)=>`pearl-english-cloud-v1:${encodeURIComponent(owner)}:${encodeURIComponent(id)}`;
const copy=value=>JSON.parse(JSON.stringify(value));
const empty=()=>({version:1,lessons:{},items:{},session:null});
const wireSession=value=>{if(!value)return null;const {steps,...session}=copy(value);return session};
const stable=value=>Array.isArray(value)?value.map(stable):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,stable(value[key])])):value;
const comparable=progress=>JSON.stringify(stable({...progress,session:wireSession(progress.session)}));
const wireEvent=event=>event.kind==='completion'?{...copy(event),result:{session:wireSession(event.result.session)}}:copy(event);
function eventBatch(events,revision,session){const result=[];for(const event of events.slice(0,256)){const next=wireEvent(event);if(new TextEncoder().encode(JSON.stringify({baseRevision:revision,session,events:[...result,next]})).length>480*1024)break;result.push(next)}return result}
export function createCourseCloud({course,storage=browserStorage(),request=familyRequest,uuid=()=>crypto.randomUUID(),now=()=>Date.now(),onState=()=>{},onAuthLoss=()=>{},debounceMs=650,subject='english',contentVersion=subject==='chinese'?'pep3-cn-2026-v1':'pep3-2024-v1',guestKey=subject==='chinese'?'pearl-chinese-course-v1':guestStorageKey,profileKey=subject==='chinese'?((owner,id)=>`pearl-chinese-cloud-v1:${encodeURIComponent(owner)}:${encodeURIComponent(id)}`):profileStorageKey,emptyProgress=empty}){
 let active=null,status='此设备',conflict=null,timer=null,generation=0,suppress=false;
 const journalId=crypto.randomUUID(),sequences=new Map();
 const read=key=>{try{return JSON.parse(storage.getItem(key))}catch{return null}};
 function emit(value){status=value;onState({status,owner:active?.owner??null,profile:active?.profile??null,conflict,pending:active?.events.length||0})}
 function eventAck(key,id){return `${key}:event-ack:${id}`}
 function sessionAck(key,id,sequence){return `${key}:session-ack:${id}:${sequence}`}
 function acknowledged(key){try{return storage.getItem(key)!==null}catch{return false}}
 function journals(key){const rows=[];try{for(let i=0;i<storage.length;i++){const name=storage.key(i);if(name?.startsWith(`${key}:queue:`)){const row=read(name);if(row?.verified)rows.push({...row,journalId:name.slice(`${key}:queue:`.length)})}}}catch{}return rows}
 function receipts(key,row){return [{journalId:row.journalId,sequence:row.sequence||0},...(row.sources||[])]}
 function prune(target){target.events=target.events.filter(event=>!acknowledged(eventAck(target.key,event.eventId)));if(acknowledged(sessionAck(target.key,journalId,target.sequence)))target.dirty=false}
 function persist(target=active){if(!target||target.sequence<(sequences.get(target.key)||0))return;sequences.set(target.key,Math.max(sequences.get(target.key)||0,target.sequence));try{prune(target);storage.setItem(target.key,JSON.stringify(target.data));if(target.dirty||target.events.length){storage.setItem(`${target.key}:queue:${journalId}`,JSON.stringify({revision:target.revision,data:target.data,events:target.events,dirty:target.dirty,verified:true,sequence:target.sequence,updatedAt:now(),conflict:target.conflict,sources:target.sources||[]}))}else{storage.removeItem(`${target.key}:queue:${journalId}`);const cached=read(`${target.key}:sync`);if(!cached||cached.revision<=target.revision)storage.setItem(`${target.key}:sync`,JSON.stringify({revision:target.revision,data:target.data,events:[],dirty:false,verified:true,conflict:null}))}}catch{emit('离线待同步')}}
 function ack(target,events,sequence,sources,revision){for(const event of events)storage.setItem(eventAck(target.key,event.eventId),String(revision));for(const source of [{journalId,sequence},...sources])storage.setItem(sessionAck(target.key,source.journalId,source.sequence),String(revision));target.sources=[]}

 function replace(data,key,preserveView=false){suppress=true;try{course.replaceProgress(copy(data),{storageKey:key,preserveView})}finally{suppress=false}}
 function schedule(){clearTimeout(timer);timer=setTimeout(()=>flush(),debounceMs);timer.unref?.()}
 function onSave({progress,event}){if(suppress||!active?.ready)return;if(!event&&comparable(progress)===comparable(active.data))return;active.data=copy(progress);if(active.conflict)active.conflict.local=copy(active.data);active.dirty=true;active.sequence++;if(event)active.events.push({...wireEvent(event),eventId:uuid(),occurredAt:now(),contentVersion});persist();emit(conflict?'需选择进度':'此设备');if(!conflict)schedule()}
 async function flush(){const target=active;if(!target?.ready||target.conflict||target.importing)return;if(target.flight)return target.flight;clearTimeout(timer);prune(target);
  target.flight=(async()=>{while(target===active&&(target.dirty||target.events.length)){const session=wireSession(target.data.session),events=eventBatch(target.events,target.revision,session),sequence=target.sequence,sources=[...(target.sources||[])];emit('同步中');try{const result=await request(`/api/family/profiles/${encodeURIComponent(target.profile.id)}/progress/${encodeURIComponent(subject)}`,{method:'POST',body:{baseRevision:target.revision,session,events}});target.revision=result.revision;ack(target,events,sequence,sources,result.revision);const sent=new Set(events.map(e=>e.eventId));target.events=target.events.filter(e=>!sent.has(e.eventId));if(sequence===target.sequence){target.data=copy(result.data);target.dirty=false;if(target===active)replace(target.data,target.key,true)}persist(target);if(target===active)emit(target.dirty||target.events.length?'此设备':'已同步');}catch(error){if(error.status===409&&error.data?.current){target.conflict={local:copy(target.data),cloud:copy(error.data.current.data),revision:error.data.current.revision,alternatives:target.recoveredSnapshots||[]};if(target===active)conflict=target.conflict;persist(target);if(target===active)emit('需选择进度')}else{persist(target);if(error.status===401||error.status===403){if(target===active){guest();onAuthLoss()}}else if(error.status===404){if(target===active)guest();}else if(target===active)emit('离线待同步')}break}}})().finally(()=>target.flight=null);return target.flight;
 }
 function guest(){const preserveView=!active&&course.storageKey===guestKey;const data=preserveView?course.snapshot():read(guestKey)||emptyProgress();clearTimeout(timer);generation++;persist();active=null;conflict=null;replace(data,guestKey,preserveView);emit('此设备')}
 async function select(owner,profile){const token=++generation;clearTimeout(timer);if(active){course.save();persist();await flush();if(token!==generation)return;}course.home();active=null;conflict=null;emit('同步中');const key=profileKey(owner,profile.id),cached=read(`${key}:sync`);let remote,offline=false;
  try{remote=await request(`/api/family/profiles/${encodeURIComponent(profile.id)}/progress/${encodeURIComponent(subject)}`)}catch(error){if(error.status||!cached?.verified){if(token===generation)guest();throw error}remote={revision:cached.revision,data:cached.data};offline=true}if(token!==generation)return;
  const rows=journals(key);if(cached?.verified&&(cached.dirty||cached.events?.length))rows.push({...cached,journalId:'legacy',sequence:cached.sequence||0});
  const candidates=rows.filter(row=>row.dirty&&!acknowledged(sessionAck(key,row.journalId,row.sequence||0))).sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0)||a.journalId.localeCompare(b.journalId));
  const events=[...new Map(rows.flatMap(row=>row.events||[]).filter(event=>!acknowledged(eventAck(key,event.eventId))).map(event=>[event.eventId,event])).values()];
  const local=candidates[0],hasPending=!!local||events.length>0,own=rows.find(row=>row.journalId===journalId),sources=[...new Map(candidates.flatMap(row=>receipts(key,row)).map(source=>[`${source.journalId}:${source.sequence}`,source])).values()];
  active={owner,profile,key,revision:local?local.revision:remote.revision,data:copy(local?local.data:remote.data),events,dirty:!!local,ready:true,sequence:Math.max(own?.sequence||0,sequences.get(key)||0)+1,sources,recoveredSnapshots:candidates.map(row=>({data:copy(row.data),journalId:row.journalId,sequence:row.sequence})),flight:null,conflict:local?.conflict||null};
  const differentSnapshots=candidates.some(row=>comparable(row.data)!==comparable(active.data));if(local&&(differentSnapshots||(!offline&&remote.revision!==active.revision)))active.conflict={local:copy(active.data),cloud:copy(remote.data),revision:remote.revision,alternatives:active.recoveredSnapshots};conflict=active.conflict;replace(active.data,key);persist();emit(conflict?'需选择进度':offline?'离线待同步':hasPending?'此设备':'已同步');if(hasPending&&!offline&&!conflict)await flush();
 }

 async function resolveConflict(choice){if(!active?.conflict)return;const current=active.conflict;active.revision=current.revision;const alternative=choice.startsWith('local:')?current.alternatives?.[Number(choice.slice(6))]?.data:null;active.data.session=copy(choice==='cloud'?current.cloud.session:(alternative||current.local).session);active.conflict=null;conflict=null;active.dirty=true;active.sequence++;replace(active.data,active.key);persist();return flush()}
 async function importGuest(){const target=active;if(!target?.ready)throw new Error('请先选择孩子。');if(target.importing)throw new Error('正在导入，请稍候。');await flush();if(target!==active)throw new Error('档案已切换，请重新选择导入。');if(target.conflict||target.events.length||target.dirty)throw new Error('请先完成进度同步。');let sourceId=storage.getItem(`${guestKey}:source`);if(!sourceId){sourceId=uuid();storage.setItem(`${guestKey}:source`,sourceId)}let importId=storage.getItem(`${target.key}:import:${sourceId}`);if(!importId){importId=uuid();storage.setItem(`${target.key}:import:${sourceId}`,importId)}const sequence=target.sequence;target.importing=true;clearTimeout(timer);try{const result=await request(`/api/family/profiles/${encodeURIComponent(target.profile.id)}/progress/${encodeURIComponent(subject)}/import`,{method:'POST',body:{sourceId,importId,data:read(guestKey)||emptyProgress()}});target.revision=result.revision;if(sequence===target.sequence)target.data=copy(result.data);persist(target);if(target===active&&sequence===target.sequence){replace(target.data,target.key);emit('已同步')}}finally{target.importing=false}if(target===active&&(target.dirty||target.events.length))await flush()}

 // Logout preserves all pending work without waiting on a potentially stalled network.
 function logout(){if(active){course.save();persist()}guest();return Promise.resolve()}
 return {select,onSave,flush,resolveConflict,importGuest,logout,get owner(){return active?.owner??null},get profile(){return active?.profile??null},get pending(){return active?.events||[]},get status(){return status},get conflict(){return conflict}};
}
