import {familyRequest,browserStorage} from '../shared/family-client.js';
export const guestStorageKey='pearl-english-course-v1';
export const profileStorageKey=(owner,id)=>`pearl-english-cloud-v1:${encodeURIComponent(owner)}:${encodeURIComponent(id)}`;
const copy=value=>JSON.parse(JSON.stringify(value));
const empty=()=>({version:1,lessons:{},items:{},session:null});
const wireSession=value=>{if(!value)return null;const {steps,...session}=copy(value);return session};
const stable=value=>Array.isArray(value)?value.map(stable):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,stable(value[key])])):value;
const comparable=progress=>JSON.stringify(stable({...progress,session:wireSession(progress.session)}));
const wireEvent=event=>event.kind==='completion'?{...copy(event),result:{session:wireSession(event.result.session)}}:copy(event);
function eventBatch(events,revision,session){const result=[];for(const event of events.slice(0,256)){const next=wireEvent(event);if(new TextEncoder().encode(JSON.stringify({baseRevision:revision,session,events:[...result,next]})).length>480*1024)break;result.push(next)}return result}
export function createCourseCloud({course,storage=browserStorage(),request=familyRequest,uuid=()=>crypto.randomUUID(),now=()=>Date.now(),onState=()=>{},onAuthLoss=()=>{},debounceMs=650}){
 let active=null,status='此设备',conflict=null,timer=null,generation=0,suppress=false;
 const read=key=>{try{return JSON.parse(storage.getItem(key))}catch{return null}};
 function emit(value){status=value;onState({status,owner:active?.owner??null,profile:active?.profile??null,conflict,pending:active?.events.length||0})}
 function persist(target=active){if(!target)return;try{storage.setItem(target.key,JSON.stringify(target.data));storage.setItem(`${target.key}:sync`,JSON.stringify({revision:target.revision,data:target.data,events:target.events,dirty:target.dirty,verified:true,conflict:target.conflict}))}catch{emit('离线待同步')}}
 function replace(data,key,preserveView=false){suppress=true;try{course.replaceProgress(copy(data),{storageKey:key,preserveView})}finally{suppress=false}}
 function schedule(){clearTimeout(timer);timer=setTimeout(()=>flush(),debounceMs);timer.unref?.()}
 function onSave({progress,event}){if(suppress||!active?.ready)return;if(!event&&comparable(progress)===comparable(active.data))return;active.data=copy(progress);if(active.conflict)active.conflict.local=copy(active.data);active.dirty=true;active.sequence++;if(event)active.events.push({...wireEvent(event),eventId:uuid(),occurredAt:now(),contentVersion:'pep3-2024-v1'});persist();emit(conflict?'需选择进度':'此设备');if(!conflict)schedule()}
 async function flush(){const target=active;if(!target?.ready||target.conflict||target.importing)return;if(target.flight)return target.flight;clearTimeout(timer);
  target.flight=(async()=>{while(target===active&&(target.dirty||target.events.length)){const session=wireSession(target.data.session),events=eventBatch(target.events,target.revision,session),sequence=target.sequence;emit('同步中');try{const result=await request(`/api/family/profiles/${encodeURIComponent(target.profile.id)}/progress/english`,{method:'POST',body:{baseRevision:target.revision,session,events}});target.revision=result.revision;const sent=new Set(events.map(e=>e.eventId));target.events=target.events.filter(e=>!sent.has(e.eventId));if(sequence===target.sequence){target.data=copy(result.data);target.dirty=false;if(target===active)replace(target.data,target.key,true)}persist(target);if(target===active)emit(target.dirty||target.events.length?'此设备':'已同步');}catch(error){if(error.status===409&&error.data?.current){target.conflict={local:copy(target.data),cloud:copy(error.data.current.data),revision:error.data.current.revision};if(target===active)conflict=target.conflict;persist(target);if(target===active)emit('需选择进度')}else{persist(target);if(error.status===401||error.status===403){if(target===active){guest();onAuthLoss()}}else if(error.status===404){if(target===active)guest();}else if(target===active)emit('离线待同步')}break}}})().finally(()=>target.flight=null);return target.flight;
 }
 function guest(){clearTimeout(timer);generation++;persist();active=null;conflict=null;replace(read(guestStorageKey)||empty(),guestStorageKey);emit('此设备')}
 async function select(owner,profile){const token=++generation;clearTimeout(timer);if(active){course.save();persist();await flush();if(token!==generation)return;}course.home();active=null;conflict=null;emit('同步中');const key=profileStorageKey(owner,profile.id),cached=read(`${key}:sync`);let remote,offline=false;
  try{remote=await request(`/api/family/profiles/${encodeURIComponent(profile.id)}/progress/english`)}catch(error){if(error.status||!cached?.verified){if(token===generation)guest();throw error}remote={revision:cached.revision,data:cached.data};offline=true}if(token!==generation)return;
  const hasPending=cached?.verified&&(cached.dirty||cached.events?.length);active={owner,profile,key,revision:hasPending?cached.revision:remote.revision,data:copy(hasPending?cached.data:remote.data),events:hasPending?cached.events||[]:[],dirty:!!hasPending,ready:true,sequence:0,flight:null,conflict:hasPending?cached.conflict||null:null};
  if(hasPending&&!offline&&remote.revision!==active.revision)active.conflict={local:copy(active.data),cloud:copy(remote.data),revision:remote.revision};conflict=active.conflict;replace(active.data,key);persist();emit(conflict?'需选择进度':offline?'离线待同步':hasPending?'此设备':'已同步');if(hasPending&&!offline&&!conflict)await flush();
 }
 async function resolveConflict(choice){if(!active?.conflict)return;const current=active.conflict;active.revision=current.revision;active.data.session=copy(choice==='cloud'?current.cloud.session:current.local.session);active.conflict=null;conflict=null;active.dirty=true;active.sequence++;replace(active.data,active.key);persist();return flush()}
 async function importGuest(){const target=active;if(!target?.ready)throw new Error('请先选择孩子。');if(target.importing)throw new Error('正在导入，请稍候。');await flush();if(target!==active)throw new Error('档案已切换，请重新选择导入。');if(target.conflict||target.events.length||target.dirty)throw new Error('请先完成进度同步。');let sourceId=storage.getItem(`${guestStorageKey}:source`);if(!sourceId){sourceId=uuid();storage.setItem(`${guestStorageKey}:source`,sourceId)}let importId=storage.getItem(`${target.key}:import:${sourceId}`);if(!importId){importId=uuid();storage.setItem(`${target.key}:import:${sourceId}`,importId)}const sequence=target.sequence;target.importing=true;clearTimeout(timer);try{const result=await request(`/api/family/profiles/${encodeURIComponent(target.profile.id)}/progress/english/import`,{method:'POST',body:{sourceId,importId,data:read(guestStorageKey)||empty()}});target.revision=result.revision;if(sequence===target.sequence)target.data=copy(result.data);persist(target);if(target===active&&sequence===target.sequence){replace(target.data,target.key);emit('已同步')}}finally{target.importing=false}if(target===active&&(target.dirty||target.events.length))await flush()}

 // Logout preserves all pending work without waiting on a potentially stalled network.
 function logout(){if(active){course.save();persist()}guest();return Promise.resolve()}
 return {select,onSave,flush,resolveConflict,importGuest,logout,get owner(){return active?.owner??null},get profile(){return active?.profile??null},get pending(){return active?.events||[]},get status(){return status},get conflict(){return conflict}};
}
