import {WORDS,BOOKS} from './curriculum.js';
import {LEVELS,SKINS,MODES,Run,makeQuestions,loadSave,completeCard,buySkin,answerMatches} from './core.js';
import {AdventureScene} from './scene.js';
import AUDIO from './audio-manifest.json';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const SAVE_KEY='pearl-english-v1',SELECTION_KEY='pearl-english-selection-v1';
let raw;try{raw=localStorage.getItem(SAVE_KEY);}catch{}
const save=loadSave(raw);let selectedBook=BOOKS[0],selectedUnit=selectedBook.units[0],modeFilter='all',skinFilter='all',previewSkin=save.skin,shopReturn='english',view='home',run=null,questions=[],roundId='',correct=0,roundWrong=[],answered=false,reviewMode=false,reviewIndex=0,sentencePicked=[],scene=null,lastFrame=0,toastTimer,hiddenPaused=false;
const input={steer:0,jump:false},held=new Set();let touchLeft=false,touchRight=false,touchJump=false;
const canvas=document.createElement('canvas');canvas.setAttribute('aria-label','3D珠珠探险场景');
const state={save,get run(){return run},get questions(){return questions},get view(){return view},get scene(){return scene},get selectedUnit(){return selectedUnit}};
// Exposes live state for diagnostics; gameplay uses the same controller, never a test-only simulation.
window.englishApp=state;
function persist(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(save));}catch{toast('当前浏览器无法保存进度，请保持此页面打开。');}updateCoins();}
function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3200);}
function updateCoins(){document.querySelectorAll('[data-coins]').forEach(el=>el.textContent=save.coins.toLocaleString());$('wrongCount').textContent=save.wrong.length;}
function resetInput(){held.clear();touchLeft=touchRight=touchJump=false;input.steer=0;input.jump=false;}
function setView(next){resetInput();view=next;document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==next);$('shopButton').disabled=next==='play';$('homeButton').disabled=next==='play';if(next!=='play')window.scrollTo({top:0});if(next==='play'){$('gameCanvas').append(canvas);scene?.resize();}if(next==='shop'){$('skinPreview').append(canvas);scene?.resize();}document.body.style.overflow=next==='play'?'hidden':'';}
function getScene(){if(!scene){try{scene=new AdventureScene(canvas,{onError:message=>toast(message?.message||message||'3D画面暂时不可用，请检查浏览器的图形加速。')});}catch(error){toast('3D画面没有启动。可先使用“本单元”听读练习。');console.error(error);return null;}}return scene;}
const termLabel=term=>term==='upper'?'上':'下';
function bookFor(grade,term){return BOOKS.find(b=>b.grade===Number(grade)&&b.term===({上:'upper',下:'lower'}[term]||term));}
function updateBook(){const book=bookFor($('grade').value,$('term').value);if(!book){$('term').value='上';toast('此册目录尚未核实，先选已开放的上册。');selectedBook=bookFor($('grade').value,'上');}else selectedBook=book;
 $('unit').innerHTML=selectedBook.units.map(u=>`<option value="${esc(u.id)}">Unit ${u.number} · ${esc(u.title)}</option>`).join('');selectedUnit=selectedBook.units[0];updateSelection();}
function updateSelection(){selectedUnit=selectedBook.units.find(u=>u.id===$('unit').value)||selectedBook.units[0];$('edition').textContent=`${selectedBook.edition} · 本单元 ${selectedUnit.words.length} 个核心词 · 自编练习，非完整官方词表`;$('sourceLink').href=selectedBook.source;try{localStorage.setItem(SELECTION_KEY,JSON.stringify({book:selectedBook.id,unit:selectedUnit.id}));}catch{}renderLevels();}
function openEnglish(){setView('english');renderLevels();}
const modeIcons={slide:'🛝',parkour:'✦',bike:'🚲',race:'🏎️'},themePalettes={forest:['#88d2bc','#d3f6db'],cloud:['#a0cfff','#f7dcf5'],sunset:['#ffa777','#e7bbcc'],neon:['#5869b4','#ba8add'],coast:['#67c4e1','#b8f2ed'],snow:['#9cc8e8','#e9f5fb'],flowers:['#ebacd1','#ceebbd'],space:['#454f8e','#9ba4df'],lava:['#da855d','#ffc494']};
function renderLevels(){$('modeFilters').innerHTML=[['all','全部路线','✦'],...Object.entries(MODES).map(([m,n])=>[m,n,modeIcons[m]])].map(([m,n,icon])=>`<button data-mode="${m}" class="${modeFilter===m?'active':''}">${icon} ${n}</button>`).join('');$('levels').innerHTML=LEVELS.filter(l=>modeFilter==='all'||l.mode===modeFilter).map(l=>{const record=save.records[`${selectedUnit.id}:${l.id}`],p=themePalettes[l.theme];return `<button class="level" data-level="${l.id}"><div class="level-art" style="--c1:${p[0]};--c2:${p[1]}"><span>${modeIcons[l.mode]}</span></div><div class="level-info"><span class="level-number">ROUTE ${String(LEVELS.indexOf(l)+1).padStart(2,'0')}</span>${record?'<span class="level-status">✓ 已完成</span>':''}<strong>${esc(l.name)}</strong><small>${record?`最佳首次答对 ${record.correct}/10`:'10张题卡 · 2000金币'}</small></div></button>`;}).join('');}
$('modeFilters').addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(b){modeFilter=b.dataset.mode;renderLevels();}});
$('levels').addEventListener('click',e=>{const b=e.target.closest('[data-level]');if(b)start(LEVELS.find(l=>l.id===b.dataset.level));});
$('grade').addEventListener('change',updateBook);$('term').addEventListener('change',updateBook);$('unit').addEventListener('change',updateSelection);
$('englishButton').onclick=openEnglish;$('homeButton').onclick=()=>{if(run&&run.status==='playing')run.pause();setView('home');};
$('chinese').onclick=()=>toast('语文玩法等你来设计，先去英语探险吧。');$('math').onclick=()=>toast('数学玩法等你来设计，先去英语探险吧。');
function start(level){closeDialogs();reviewMode=false;run=new Run(level);roundId=crypto.randomUUID();questions=makeQuestions(selectedUnit,WORDS,level.seed+Math.floor(Math.random()*100000));correct=0;roundWrong=[];answered=false;setView('play');const s=getScene();if(!s){run=null;openEnglish();return;}s.start(level,SKINS.find(x=>x.id===save.skin));$('courseName').textContent=level.name;$('courseUnit').textContent=`${selectedBook.grade}年级${termLabel(selectedBook.term)}册 · Unit ${selectedUnit.number} ${selectedUnit.title}`;updateHUD();lastFrame=performance.now();}
function updateHUD(){if(!run)return;$('cardCount').textContent=`题卡 ${run.completed} / 10`;$('timer').textContent=`${Math.floor(run.elapsed/60)}:${String(Math.floor(run.elapsed)%60).padStart(2,'0')}`;$('raceRank').textContent=run.level.mode==='race'?`第 ${run.rank} / 10 名`:'';$('progressBar').style.width=`${run.progress*100}%`;const hit=run.lastHit!==null&&run.elapsed-run.lastHit<2.5;$('playTip').textContent=hit?'碰到路障会减速，试着转向或跳过去。':run.level.mode==='parkour'?'左右转向躲开路障，空格或“跳跃”越过障碍。':'方向键 / A、D 转向；沿途10张题卡，答题时全场暂停。';}
function closeDialogs(){for(const d of document.querySelectorAll('dialog[open]'))d.close();}
function currentQuestion(){return questions[reviewMode?reviewIndex:run.card];}
const kindNames={word:'单词识记',ipa:'美式音标',sentence:'句子拼装',grammar:'语法小挑战'};
function showQuestion(){resetInput();answered=false;sentencePicked=[];const q=currentQuestion();$('quizKind').textContent=kindNames[q.kind];$('quizCount').textContent=reviewMode?`错题复习 ${reviewIndex+1} / ${questions.length}`:`第 ${run.card+1} / 10 张`;$('pauseNote').textContent=reviewMode?'先试着回答，再看解释。':'⏸ 玩家、对手和计时都已暂停，慢慢想。';$('prompt').textContent=q.prompt;$('listen').hidden=!q.say;$('feedback').hidden=true;$('feedback').className='feedback';$('hintText').hidden=true;$('hintButton').hidden=false;$('continueButton').hidden=true;$('checkSentence').hidden=q.kind!=='sentence';$('listen').disabled=false;
 if(q.kind==='sentence'){$('answerArea').innerHTML='<div class="sentence-answer" id="sentenceAnswer"></div><div class="tokens" id="tokens"></div><button id="clearSentence" class="text-button">重新排列</button>';renderTokens();$('clearSentence').onclick=()=>{sentencePicked=[];renderTokens();};}
 else $('answerArea').innerHTML=`<div class="choices">${q.choices.map((c,i)=>`<button class="choice" data-choice="${i}">${esc(c)}</button>`).join('')}</div>`;
 if(!$('quiz').open)$('quiz').showModal();$('quiz').scrollTop=0;requestAnimationFrame(()=>$('quiz').querySelector('.choice,.token,#listen')?.focus());}
function renderTokens(){const q=currentQuestion();$('sentenceAnswer').innerHTML=sentencePicked.map((index,i)=>`<button class="token" data-remove="${i}">${esc(q.tokens[index])}</button>`).join('');$('tokens').innerHTML=q.tokens.map((t,i)=>`<button class="token" data-token="${i}" ${sentencePicked.includes(i)?'disabled':''}>${esc(t)}</button>`).join('');$('checkSentence').disabled=sentencePicked.length!==q.tokens.length;}
$('answerArea').addEventListener('click',e=>{if(answered)return;const choice=e.target.closest('[data-choice]');if(choice){const q=currentQuestion();gradeAnswer(q.choices[Number(choice.dataset.choice)]);return;}const token=e.target.closest('[data-token]');if(token&&!token.disabled){sentencePicked.push(Number(token.dataset.token));renderTokens();}const remove=e.target.closest('[data-remove]');if(remove){sentencePicked.splice(Number(remove.dataset.remove),1);renderTokens();}});
$('checkSentence').onclick=()=>gradeAnswer(sentencePicked.map(i=>currentQuestion().tokens[i]).join(' '));
function gradeAnswer(answer){if(answered)return;const q=currentQuestion();answered=true;const isCorrect=answerMatches(q,answer);if(isCorrect)correct++;else {roundWrong.push(q);const at=save.wrong.findIndex(x=>x.prompt===q.prompt&&x.answer===q.answer);if(at>=0)save.wrong.splice(at,1);save.wrong.push(q);save.wrong=save.wrong.slice(-100);persist();}
 for(const button of $('answerArea').querySelectorAll('button')){button.disabled=true;if(button.classList.contains('choice')){if(button.textContent===q.answer)button.classList.add('correct');else if(button.textContent===answer)button.classList.add('incorrect');}}
 $('feedback').classList.toggle('wrong',!isCorrect);$('feedback').innerHTML=`<strong>${isCorrect?'答对了！':'这次没答对，看看为什么。'}</strong><span class="solution">${esc(q.solution)}</span><span>${esc(q.explanation)}</span>`;$('feedback').hidden=false;$('checkSentence').hidden=true;$('hintButton').hidden=true;$('continueButton').hidden=false;$('continueButton').textContent=reviewMode?'完成复习 · +200金币':'继续探险 · +200金币';requestAnimationFrame(()=>$('continueButton').focus());}
$('hintButton').onclick=()=>{const q=currentQuestion();const text=q.kind==='word'?`小提示：这个英语词以 ${q.answer[0].toUpperCase()} 开头。`:q.kind==='ipa'?'先听单词，再比较音标。ˈ 标记重读；/ / 里面记录的是声音。':q.kind==='sentence'?'先找谁在做事（主语），再找做什么（动词）。问句留意开头的提问词。':'看看空格前后的词。先找主语，再想动词、人称或时间应怎样搭配。';$('hintText').textContent=text;$('hintText').hidden=false;};
$('continueButton').onclick=()=>{if(!answered)return;const id=`${roundId}:${reviewMode?reviewIndex:run.card}`;if(completeCard(save,id)){persist();toast('+200金币，继续出发！');}answered=false;$('quiz').close();if(reviewMode){reviewIndex++;if(reviewIndex<questions.length)showQuestion();else{reviewMode=false;toast('复习完成！可以再选一条路线。');openEnglish();}}else{run.resumeCard();resetInput();lastFrame=performance.now();updateHUD();}};
$('quiz').addEventListener('cancel',e=>e.preventDefault());
function pause(){if(run?.pause()){resetInput();$('pauseDialog').showModal();}}
$('pauseButton').onclick=pause;$('leaveButton').onclick=pause;$('resumeButton').onclick=()=>{$('pauseDialog').close();run?.resume();resetInput();lastFrame=performance.now();};$('quitButton').onclick=()=>{$('pauseDialog').close();run=null;openEnglish();};$('pauseDialog').addEventListener('cancel',e=>{e.preventDefault();$('resumeButton').click();});
function finish(){const key=`${selectedUnit.id}:${run.level.id}`;const old=save.records[key];save.records[key]={correct:Math.max(correct,old?.correct||0),time:Math.min(run.elapsed,old?.time||Infinity),plays:(old?.plays||0)+1};persist();$('resultStats').textContent=`完成10张题卡 · 首次答对 ${correct}/10 · 获得2000金币${run.level.mode==='race'?` · 赛车第${run.rank}名`:''}`;$('resultWrong').innerHTML=roundWrong.length?`<div class="result-wrong">这些再看一遍：${roundWrong.map(q=>`<p>${esc(q.solution)}<br>${esc(q.explanation)}</p>`).join('')}</div>`:'<p>本轮首次作答全部正确，下一站见！</p>';$('result').showModal();}
$('nextLevel').onclick=()=>start(LEVELS[(LEVELS.indexOf(run.level)+1)%LEVELS.length]);$('resultBack').onclick=()=>{$('result').close();run=null;openEnglish();};$('resultShop').onclick=()=>{$('result').close();run=null;openShop('english');};$('result').addEventListener('cancel',e=>{e.preventDefault();$('resultBack').click();});
function openShop(from=view){shopReturn=from==='play'?'english':from;setView('shop');if(!getScene())return;selectSkin(previewSkin);renderSkins();}
$('shopButton').onclick=()=>openShop();$('shopBack').onclick=()=>setView(shopReturn==='shop'?'english':shopReturn);
const accessoryIcons={none:'',crown:'♛',glasses:'⌐■_■',halo:'◌',ears:'⌁',star:'✦',crystal:'◇',flower:'❀',wings:'⋈'};
function renderSkins(){$('skinFilters').innerHTML=['all','普通','独特','隐藏','神话'].map(t=>`<button class="${skinFilter===t?'active':''}" data-tier="${t}">${t==='all'?'全部33款':t}</button>`).join('');$('skins').innerHTML=SKINS.filter(s=>skinFilter==='all'||s.tier===skinFilter).map(s=>`<button class="skin-card ${previewSkin===s.id?'selected':''}" data-skin="${s.id}">${save.owned.includes(s.id)?`<span class="skin-owned">${save.skin===s.id?'使用中':'已拥有'}</span>`:''}<span class="skin-ball" style="--color:${s.color};--accent:${s.accent}">${accessoryIcons[s.accessory]}</span><strong>${esc(s.name)}</strong><small>${s.price?`${s.tier} · ${s.price}金币`:'免费 · 初始皮肤'}</small></button>`).join('');}
function selectSkin(id){previewSkin=id;const s=SKINS.find(s=>s.id===id);$('previewName').textContent=s.name;$('previewTier').textContent=s.price?`${s.tier} · ${s.price}金币`:'免费';$('buyPreview').textContent=save.skin===id?'正在使用':save.owned.includes(id)?'换上这颗珠珠':save.coins>=s.price?`购买并换上 · ${s.price}金币`:`还差${s.price-save.coins}金币`;$('buyPreview').disabled=save.skin===id||(!save.owned.includes(id)&&save.coins<s.price);scene?.preview(s);renderSkins();}
$('skinFilters').addEventListener('click',e=>{const b=e.target.closest('[data-tier]');if(b){skinFilter=b.dataset.tier;renderSkins();}});$('skins').addEventListener('click',e=>{const b=e.target.closest('[data-skin]');if(b)selectSkin(b.dataset.skin);});
$('buyPreview').onclick=()=>{if(save.owned.includes(previewSkin)){save.skin=previewSkin;persist();}else if(buySkin(save,previewSkin)){persist();toast('新皮肤已换上！下一局带着它出发。');}selectSkin(previewSkin);};
function openStudy(){$('studyTitle').textContent=`Unit ${selectedUnit.number} · ${selectedUnit.title}`;$('studyContent').innerHTML=`<p>${esc(selectedUnit.zh)} · 点击听美式发音</p><div class="study-words">${selectedUnit.words.map(id=>{const w=WORDS[id];return `<button class="study-word" data-say-word="${id}"><strong>${esc(w.en)} 🔊</strong><span>${esc(w.ipa)}</span><small>${esc(w.zh)}</small></button>`;}).join('')}</div><h3>句子小笔记</h3>${selectedUnit.sentences.map((s,i)=>`<div class="study-sentence"><strong>${esc(s.en)}</strong><br>${esc(s.zh)}<br><small>${esc(s.tip)}</small><br><button class="listen-button" data-say-sentence="${i}">🔊 听句子</button></div>`).join('')}<p class="source-note">“本单元”列出精选核心词和自编例句；ˈ 为重音。音频使用美式语音。</p>`;$('study').showModal();}
$('openStudy').onclick=openStudy;$('closeStudy').onclick=()=>$('study').close();$('studyContent').onclick=e=>{const word=e.target.closest('[data-say-word]');if(word)speak(WORDS[word.dataset.sayWord].en,word.dataset.sayWord);const sentence=e.target.closest('[data-say-sentence]');if(sentence)speak(selectedUnit.sentences[Number(sentence.dataset.saySentence)].en);};
let audio=null;let audioSerial=0;
async function speak(text,wordId){const serial=++audioSerial;if(audio){audio.pause();audio=null;}window.speechSynthesis?.cancel();if(wordId&&AUDIO[wordId]){audio=new Audio(new URL(`audio/${AUDIO[wordId]}`,import.meta.url));audio.volume=.85;audio.playbackRate=.85;try{await audio.play();return;}catch{if(serial!==audioSerial)return;}}
 // Bundle is in english/: lexical match also handles question cards and study phrases.
 const id=Object.keys(WORDS).find(id=>WORDS[id].en.toLowerCase()===text.toLowerCase());if(id&&AUDIO[id]&&id!==wordId){audio=new Audio(new URL(`audio/${AUDIO[id]}`,import.meta.url));audio.playbackRate=.85;try{await audio.play();return;}catch{}}
 const synth=window.speechSynthesis,voice=synth?.getVoices().find(v=>/^en[-_]US$/i.test(v.lang));if(synth&&voice){const utterance=new SpeechSynthesisUtterance(text);utterance.voice=voice;utterance.lang='en-US';utterance.rate=.82;synth.speak(utterance);return;}
 // Sentence clips are bundled too. All available voices and clips are US English.
 const phraseKey=Object.keys(AUDIO).find(key=>AUDIO[key]&&key===`sentence:${text}`);if(phraseKey){audio=new Audio(new URL(`audio/${AUDIO[phraseKey]}`,import.meta.url));audio.playbackRate=.85;try{await audio.play();return;}catch{}}
 toast('这段发音暂时无法播放，请稍后再试。');}
$('listen').onclick=()=>{const q=currentQuestion();speak(q.say,q.wordId);};
$('reviewButton').onclick=()=>{if(!save.wrong.length){toast('还没有错题。先去英语探险吧！');return;}reviewMode=true;reviewIndex=0;roundId=crypto.randomUUID();questions=save.wrong.slice(-10).map(q=>({...q}));correct=0;roundWrong=[];showQuestion();};
function computeInput(){input.steer=(held.has('ArrowRight')||held.has('d')||touchRight?1:0)-(held.has('ArrowLeft')||held.has('a')||touchLeft?1:0);input.jump=held.has(' ')||held.has('ArrowUp')||held.has('w')||touchJump;}
addEventListener('keydown',e=>{if(view!=='play'||run?.status!=='playing')return;if(['ArrowLeft','ArrowRight','ArrowUp',' ','a','d','w'].includes(e.key)){e.preventDefault();held.add(e.key);computeInput();}else if(e.key==='Escape'||e.key==='p'){e.preventDefault();pause();}});addEventListener('keyup',e=>{held.delete(e.key);computeInput();});
function touchButton(id,set){const b=$(id);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);set(true);computeInput();});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>{set(false);computeInput();});}
touchButton('leftButton',v=>touchLeft=v);touchButton('rightButton',v=>touchRight=v);touchButton('jumpButton',v=>touchJump=v);
addEventListener('blur',()=>{resetInput();if(view==='play')pause();});document.addEventListener('visibilitychange',()=>{resetInput();if(document.hidden){hiddenPaused=!!run?.pause();if(audio)audio.pause();}else if(hiddenPaused){hiddenPaused=false;if(view==='play'&&!$('pauseDialog').open)$('pauseDialog').showModal();}});
let renderedRun=null,renderedStatus='',needsRender=true;
addEventListener('resize',()=>{scene?.resize();needsRender=true;});
function frame(time){const dt=Math.min(.05,Math.max(0,(time-lastFrame)/1000));lastFrame=time;
 if(view==='play'&&run){run.step(dt,input);if(run.status==='playing'||renderedRun!==run||renderedStatus!==run.status||needsRender){scene?.render(run,input,run.status==='playing'?dt:0);renderedRun=run;renderedStatus=run.status;needsRender=false;}updateHUD();if(run.status==='question'&&!$('quiz').open)showQuestion();if(run.status==='finished'&&!$('result').open)finish();}
 else if(view==='shop')scene?.render(null,{steer:0,jump:false},dt);
 requestAnimationFrame(frame);}
try{const selection=JSON.parse(localStorage.getItem(SELECTION_KEY));const book=BOOKS.find(b=>b.id===selection?.book);if(book){selectedBook=book;selectedUnit=book.units.find(u=>u.id===selection.unit)||book.units[0];}}catch{}
$('grade').value=selectedBook.grade;$('term').value=termLabel(selectedBook.term);const initialUnit=selectedUnit.id;updateBook();$('unit').value=initialUnit;updateSelection();updateCoins();renderSkins();requestAnimationFrame(frame);
