import {mountCourse} from './course-ui.js';
import {createCourseCloud} from './course-cloud.js';
import {LESSONS as COURSE_LESSONS} from './course-curriculum.js';
import {familyAPI,avatars as familyAvatars,selectedProfileKey as familySelectedProfileKey,selectProfile as familySelectProfile,verifiedOwnerKey as familyVerifiedOwnerKey,clearFamilyIdentity as familyClearIdentity,accountError as familyAccountError} from '../shared/family-client.js';
import {WORDS,BOOKS} from './curriculum.js';
import {LEVELS,SKINS,MODES,Run,makeQuestions,loadSave,completeCard,buySkin,answerMatches,snapshotRun,restoreRun} from './core.js';
import {AdventureScene} from './scene.js';
import AUDIO from './audio-manifest.json';
import {AudioReader} from './audio-reader.js';
import {textbookSection,textbookPage} from './textbook.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const SAVE_KEY='pearl-english-v1',SELECTION_KEY='pearl-english-selection-v1';
let raw;try{raw=localStorage.getItem(SAVE_KEY);}catch{}
const save=loadSave(raw);let selectedBook=BOOKS[0],selectedUnit=selectedBook.units[0],modeFilter='all',skinFilter='all',previewSkin=save.skin,shopReturn='english',view='home',run=null,questions=[],roundId='',correct=0,roundWrong=[],answered=false,reviewMode=false,reviewIndex=0,sentencePicked=[],scene=null,lastFrame=0,toastTimer,hiddenPaused=false,lastAnswer=null;
let coursePlaying=false;
function syncActivity(){window.GameActivity?.setPlaying((view==='home'&&coursePlaying&&!$('study').open)||(reviewMode&&$('quiz').open)||(view==='play'&&!!run&&['playing','question'].includes(run.status)&&!$('pauseDialog').open));}
const input={steer:0,jump:false},held=new Set();let touchLeft=false,touchRight=false,touchJump=false;
const canvas=document.createElement('canvas');canvas.setAttribute('aria-label','3D珠珠探险场景');
const state={save,get run(){return run},get questions(){return questions},get view(){return view},get scene(){return scene},get selectedUnit(){return selectedUnit}};
// Exposes live state for diagnostics; gameplay uses the same controller, never a test-only simulation.
window.englishApp=state;
function persist(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(save));}catch{toast('当前浏览器无法保存进度，请保持此页面打开。');}updateCoins();}
function checkpoint(){if(run&&!reviewMode&&run.status!=='finished'){save.session={roundId,bookId:selectedBook.id,unitId:selectedUnit.id,run:snapshotRun(run),questions,correct,wrong:roundWrong,lastAnswer,picked:sentencePicked};persist();}}
function updateContinuation(){for(const id of ['continueSaved','continueEnglish']){const button=$(id);button.hidden=!save.session;if(save.session)button.textContent=`继续上次探险 · 已完成 ${save.session.run.completed}/10 张题卡`;}}
function continueSaved(){const stored=save.session;if(!stored)return;const book=BOOKS.find(b=>b.id===stored.bookId),unit=book?.units.find(u=>u.id===stored.unitId),restored=restoreRun(stored.run);if(!unit||!restored){toast('这段探险进度暂时无法恢复，金币和皮肤仍保留。');return;}
 closeDialogs();selectedBook=book;selectedUnit=unit;$('grade').value=book.grade;$('term').value=termLabel(book.term);updateBook();$('unit').value=unit.id;updateSelection();
 reviewMode=false;run=restored;questions=stored.questions;roundId=stored.roundId;correct=stored.correct;roundWrong=[...stored.wrong];lastAnswer=stored.lastAnswer;answered=lastAnswer!==null;sentencePicked=[...stored.picked];run.resume();if(!enterRun())return;if(run.status==='question')showQuestion(true);checkpoint();}
function enterRun(){setView('play');const s=getScene();if(!s){run=null;openEnglish();return false;}s.start(run.level,SKINS.find(x=>x.id===save.skin));$('courseName').textContent=run.level.name;$('courseUnit').textContent=`${selectedBook.grade}年级${termLabel(selectedBook.term)}册 · Unit ${selectedUnit.number} ${selectedUnit.title}`;updateHUD();lastFrame=performance.now();syncActivity();return true;}
$('continueSaved').onclick=continueSaved;$('continueEnglish').onclick=continueSaved;
function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3200);}
function updateCoins(){document.querySelectorAll('[data-coins]').forEach(el=>el.textContent=save.coins.toLocaleString());$('wrongCount').textContent=save.wrong.length;updateContinuation();}
function resetInput(){held.clear();touchLeft=touchRight=touchJump=false;input.steer=0;input.jump=false;}
function setView(next){stopReading();resetInput();view=next;document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==next);$('shopButton').disabled=next==='play';$('homeButton').disabled=next==='play';if(next!=='play')window.scrollTo({top:0});if(next==='play'){$('gameCanvas').append(canvas);scene?.resize();}if(next==='shop'){$('skinPreview').append(canvas);scene?.resize();}document.body.style.overflow=next==='play'?'hidden':'';syncActivity();}
function getScene(){if(!scene){try{scene=new AdventureScene(canvas,{onError:message=>toast(message?.message||message||'3D画面暂时不可用，请检查浏览器的图形加速。')});}catch(error){toast('3D画面没有启动。可先使用“本单元”听读练习。');console.error(error);return null;}}return scene;}
const termLabel=term=>term==='upper'?'上':'下';
function bookFor(grade,term){return BOOKS.find(b=>b.grade===Number(grade)&&b.term===({上:'upper',下:'lower'}[term]||term));}
function updateBook(){const book=bookFor($('grade').value,$('term').value);if(!book){$('term').value='上';toast('此册目录尚未核实，先选已开放的上册。');selectedBook=bookFor($('grade').value,'上');}else selectedBook=book;
 $('unit').innerHTML=selectedBook.units.map(u=>`<option value="${esc(u.id)}">Unit ${u.number} · ${esc(u.title)}</option>`).join('');selectedUnit=selectedBook.units[0];updateSelection();}
const vocabularyStatus=unit=>unit.coverage?.status==='verified'?'词汇附录已核对':unit.coverage?.wordlistStatus==='verified'?'官方词表音频已核对':'词表核对中';
function updateSelection(){selectedUnit=selectedBook.units.find(u=>u.id===$('unit').value)||selectedBook.units[0];$('edition').textContent=`${selectedBook.edition} · 本单元 ${selectedUnit.words.length} 个词 · ${selectedUnit.sentences.length} 条句式练习 · ${selectedUnit.grammar.length} 个语法练习 · ${vocabularyStatus(selectedUnit)}`;$('sourceLink').href=selectedBook.source;try{localStorage.setItem(SELECTION_KEY,JSON.stringify({book:selectedBook.id,unit:selectedUnit.id}));}catch{}renderLevels();}
function openEnglish(){setView('english');renderLevels();}
const modeIcons={slide:'🛝',parkour:'✦',bike:'🚲',race:'🏎️'},themePalettes={forest:['#88d2bc','#d3f6db'],cloud:['#a0cfff','#f7dcf5'],sunset:['#ffa777','#e7bbcc'],neon:['#5869b4','#ba8add'],coast:['#67c4e1','#b8f2ed'],snow:['#9cc8e8','#e9f5fb'],flowers:['#ebacd1','#ceebbd'],space:['#454f8e','#9ba4df'],lava:['#da855d','#ffc494']};
function renderLevels(){$('modeFilters').innerHTML=[['all','全部路线','✦'],...Object.entries(MODES).map(([m,n])=>[m,n,modeIcons[m]])].map(([m,n,icon])=>`<button data-mode="${m}" class="${modeFilter===m?'active':''}">${icon} ${n}</button>`).join('');$('levels').innerHTML=LEVELS.filter(l=>modeFilter==='all'||l.mode===modeFilter).map(l=>{const record=save.records[`${selectedUnit.id}:${l.id}`],p=themePalettes[l.theme];return `<button class="level" data-level="${l.id}"><div class="level-art" style="--c1:${p[0]};--c2:${p[1]}"><span>${modeIcons[l.mode]}</span></div><div class="level-info"><span class="level-number">ROUTE ${String(LEVELS.indexOf(l)+1).padStart(2,'0')}</span>${record?'<span class="level-status">✓ 已完成</span>':''}<strong>${esc(l.name)}</strong><small>${record?`最佳首次答对 ${record.correct}/10`:'10张题卡 · 2000金币'}</small></div></button>`;}).join('');}
$('modeFilters').addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(b){modeFilter=b.dataset.mode;renderLevels();}});
$('levels').addEventListener('click',e=>{const b=e.target.closest('[data-level]');if(b)start(LEVELS.find(l=>l.id===b.dataset.level));});
$('grade').addEventListener('change',updateBook);$('term').addEventListener('change',updateBook);$('unit').addEventListener('change',updateSelection);
$('englishButton').onclick=openEnglish;$('homeButton').onclick=()=>{if(run&&run.status==='playing')run.pause();course.home();setView('home');};

function start(level){if(save.session?.run.levelId===level.id&&save.session.unitId===selectedUnit.id){continueSaved();return;}closeDialogs();reviewMode=false;run=new Run(level);roundId=crypto.randomUUID();questions=makeQuestions(selectedUnit,WORDS,level.seed+Math.floor(Math.random()*100000));correct=0;roundWrong=[];answered=false;lastAnswer=null;sentencePicked=[];enterRun();checkpoint();}
function updateHUD(){if(!run)return;$('cardCount').textContent=`题卡 ${run.completed} / 10`;$('timer').textContent=`${Math.floor(run.elapsed/60)}:${String(Math.floor(run.elapsed)%60).padStart(2,'0')}`;$('raceRank').textContent=run.level.mode==='race'?`第 ${run.rank} / 10 名`:'';$('progressBar').style.width=`${run.progress*100}%`;const hit=run.lastHit!==null&&run.elapsed-run.lastHit<2.5;$('playTip').textContent=hit?'碰到路障会减速，试着转向或跳过去。':run.level.mode==='parkour'?'左右转向躲开路障，空格或“跳跃”越过障碍。':'方向键 / A、D 转向；沿途10张题卡，答题时全场暂停。';}
function closeDialogs(){stopReading();for(const d of document.querySelectorAll('dialog[open]'))d.close();}
function currentQuestion(){return questions[reviewMode?reviewIndex:run.card];}
const kindNames={word:'单词识记',ipa:'美式音标',sentence:'句子拼装',grammar:'语法小挑战'};
function showQuestion(restoring=false){resetInput();if(!restoring){answered=false;lastAnswer=null;sentencePicked=[];}const q=currentQuestion();$('quizKind').textContent=kindNames[q.kind];$('quizCount').textContent=reviewMode?`错题复习 ${reviewIndex+1} / ${questions.length}`:`第 ${run.card+1} / 10 张`;$('pauseNote').textContent=reviewMode?'先试着回答，再看解释。':'⏸ 玩家、对手和计时都已暂停，慢慢想。';$('prompt').textContent=q.prompt;$('listen').hidden=!q.say;$('feedback').hidden=true;$('feedback').className='feedback';$('hintText').hidden=true;$('hintButton').hidden=false;$('continueButton').hidden=true;$('checkSentence').hidden=q.kind!=='sentence';$('listen').disabled=false;
 if(q.kind==='sentence'){$('answerArea').innerHTML='<div class="sentence-answer" id="sentenceAnswer"></div><div class="tokens" id="tokens"></div><button id="clearSentence" class="text-button">重新排列</button>';renderTokens();$('clearSentence').onclick=()=>{sentencePicked=[];renderTokens();checkpoint();};}
 else $('answerArea').innerHTML=`<div class="choices">${q.choices.map((c,i)=>`<button class="choice" data-choice="${i}">${esc(c)}</button>`).join('')}</div>`;
 if(restoring&&lastAnswer!==null)renderAnswerFeedback(lastAnswer);checkpoint();if(!$('quiz').open)$('quiz').showModal();syncActivity();$('quiz').scrollTop=0;requestAnimationFrame(()=>$('quiz').querySelector('.choice,.token,#listen')?.focus());}
function renderTokens(){const q=currentQuestion();$('sentenceAnswer').innerHTML=sentencePicked.map((index,i)=>`<button class="token" data-remove="${i}">${esc(q.tokens[index])}</button>`).join('');$('tokens').innerHTML=q.tokens.map((t,i)=>`<button class="token" data-token="${i}" ${sentencePicked.includes(i)?'disabled':''}>${esc(t)}</button>`).join('');$('checkSentence').disabled=sentencePicked.length!==q.tokens.length;}
$('answerArea').addEventListener('click',e=>{if(answered)return;const choice=e.target.closest('[data-choice]');if(choice){const q=currentQuestion();gradeAnswer(q.choices[Number(choice.dataset.choice)]);return;}const token=e.target.closest('[data-token]');if(token&&!token.disabled){sentencePicked.push(Number(token.dataset.token));renderTokens();checkpoint();}const remove=e.target.closest('[data-remove]');if(remove){sentencePicked.splice(Number(remove.dataset.remove),1);renderTokens();checkpoint();}});
$('checkSentence').onclick=()=>gradeAnswer(sentencePicked.map(i=>currentQuestion().tokens[i]).join(' '));
function gradeAnswer(answer){if(answered)return;const q=currentQuestion();answered=true;lastAnswer=answer;const isCorrect=answerMatches(q,answer);if(isCorrect)correct++;else {roundWrong.push(q);const at=save.wrong.findIndex(x=>x.prompt===q.prompt&&x.answer===q.answer);if(at>=0)save.wrong.splice(at,1);save.wrong.push(q);save.wrong=save.wrong.slice(-100);}
 renderAnswerFeedback(answer);if(reviewMode)persist();else checkpoint();}
function renderAnswerFeedback(answer){const q=currentQuestion(),isCorrect=answerMatches(q,answer);answered=true;
 for(const button of $('answerArea').querySelectorAll('button')){button.disabled=true;if(button.classList.contains('choice')){if(button.textContent===q.answer)button.classList.add('correct');else if(button.textContent===answer)button.classList.add('incorrect');}}
 $('feedback').classList.toggle('wrong',!isCorrect);$('feedback').innerHTML=`<strong>${isCorrect?'答对了！':'这次没答对，看看为什么。'}</strong><span class="solution">${esc(q.solution)}</span><span>${esc(q.explanation)}</span>`;$('feedback').hidden=false;$('checkSentence').hidden=true;$('hintButton').hidden=true;$('continueButton').hidden=false;$('continueButton').textContent=reviewMode?'完成复习 · +200金币':'继续探险 · +200金币';requestAnimationFrame(()=>$('continueButton').focus());}
$('hintButton').onclick=()=>{const q=currentQuestion();const text=q.kind==='word'?`小提示：这个英语词以 ${q.answer[0].toUpperCase()} 开头。`:q.kind==='ipa'?'先听单词，再比较音标。ˈ 标记重读；/ / 里面记录的是声音。':q.kind==='sentence'?'先找谁在做事（主语），再找做什么（动词）。问句留意开头的提问词。':'看看空格前后的词。先找主语，再想动词、人称或时间应怎样搭配。';$('hintText').textContent=text;$('hintText').hidden=false;};
$('continueButton').onclick=()=>{if(!answered)return;const id=`${roundId}:${reviewMode?reviewIndex:run.card}`;const awarded=completeCard(save,id);answered=false;lastAnswer=null;sentencePicked=[];$('quiz').close();if(reviewMode){persist();reviewIndex++;if(reviewIndex<questions.length)showQuestion();else{reviewMode=false;toast('复习完成！可以再选一条路线。');openEnglish();}}else{run.resumeCard();checkpoint();resetInput();lastFrame=performance.now();updateHUD();}if(awarded)toast('+200金币，继续出发！');};
$('quiz').addEventListener('cancel',e=>e.preventDefault());
function pause(){if(run?.pause()){checkpoint();resetInput();$('pauseDialog').showModal();syncActivity();}}
$('pauseButton').onclick=pause;$('leaveButton').onclick=pause;$('resumeButton').onclick=()=>{$('pauseDialog').close();run?.resume();checkpoint();resetInput();lastFrame=performance.now();};$('quitButton').onclick=()=>{$('pauseDialog').close();checkpoint();run=null;openEnglish();};$('pauseDialog').addEventListener('cancel',e=>{e.preventDefault();$('resumeButton').click();});
function finish(){window.GameActivity?.finish();save.session=null;const key=`${selectedUnit.id}:${run.level.id}`;const old=save.records[key];save.records[key]={correct:Math.max(correct,old?.correct||0),time:Math.min(run.elapsed,old?.time||Infinity),plays:(old?.plays||0)+1};persist();$('resultStats').textContent=`完成10张题卡 · 首次答对 ${correct}/10 · 获得2000金币${run.level.mode==='race'?` · 赛车第${run.rank}名`:''}`;$('resultWrong').innerHTML=roundWrong.length?`<div class="result-wrong">这些再看一遍：${roundWrong.map(q=>`<p>${esc(q.solution)}<br>${esc(q.explanation)}</p>`).join('')}</div>`:'<p>本轮首次作答全部正确，下一站见！</p>';$('result').showModal();}
$('nextLevel').onclick=()=>start(LEVELS[(LEVELS.indexOf(run.level)+1)%LEVELS.length]);$('resultBack').onclick=()=>{$('result').close();run=null;openEnglish();};$('resultShop').onclick=()=>{$('result').close();run=null;openShop('english');};$('result').addEventListener('cancel',e=>{e.preventDefault();$('resultBack').click();});
function openShop(from=view){shopReturn=from==='play'?'english':from;setView('shop');if(!getScene())return;selectSkin(previewSkin);renderSkins();}
$('shopButton').onclick=()=>openShop();$('shopBack').onclick=()=>setView(shopReturn==='shop'?'english':shopReturn);
const accessoryIcons={none:'',crown:'♛',glasses:'⌐■_■',halo:'◌',ears:'⌁',star:'✦',crystal:'◇',flower:'❀',wings:'⋈'};
function renderSkins(){$('skinFilters').innerHTML=['all','普通','独特','隐藏','神话'].map(t=>`<button class="${skinFilter===t?'active':''}" data-tier="${t}">${t==='all'?'全部33款':t}</button>`).join('');$('skins').innerHTML=SKINS.filter(s=>skinFilter==='all'||s.tier===skinFilter).map(s=>`<button class="skin-card ${previewSkin===s.id?'selected':''}" data-skin="${s.id}">${save.owned.includes(s.id)?`<span class="skin-owned">${save.skin===s.id?'使用中':'已拥有'}</span>`:''}<span class="skin-ball" style="--color:${s.color};--accent:${s.accent}">${accessoryIcons[s.accessory]}</span><strong>${esc(s.name)}</strong><small>${s.price?`${s.tier} · ${s.price}金币`:'免费 · 初始皮肤'}</small></button>`).join('');}
function selectSkin(id){previewSkin=id;const s=SKINS.find(s=>s.id===id);$('previewName').textContent=s.name;$('previewTier').textContent=s.price?`${s.tier} · ${s.price}金币`:'免费';$('buyPreview').textContent=save.skin===id?'正在使用':save.owned.includes(id)?'换上这颗珠珠':save.coins>=s.price?`购买并换上 · ${s.price}金币`:`还差${s.price-save.coins}金币`;$('buyPreview').disabled=save.skin===id||(!save.owned.includes(id)&&save.coins<s.price);scene?.preview(s);renderSkins();}
$('skinFilters').addEventListener('click',e=>{const b=e.target.closest('[data-tier]');if(b){skinFilter=b.dataset.tier;renderSkins();}});$('skins').addEventListener('click',e=>{const b=e.target.closest('[data-skin]');if(b)selectSkin(b.dataset.skin);});
$('buyPreview').onclick=()=>{if(save.owned.includes(previewSkin)){save.skin=previewSkin;persist();}else if(buySkin(save,previewSkin)){persist();toast('新皮肤已换上！下一局带着它出发。');}selectSkin(previewSkin);};
let studyPages=[];
function openStudy(){studyPages=selectedUnit.textbookPages??[];$('studyTitle').textContent=`Unit ${selectedUnit.number} · ${selectedUnit.title}`;
 $('studyContent').innerHTML=`<p>${esc(selectedUnit.zh)} · ${selectedUnit.words.length} 个单词/词组 · ${selectedUnit.sentences.length} 条句式 · ${selectedUnit.grammar.length} 个语法练习</p>${textbookSection(selectedUnit,esc,!!selectedBook.textbookPages)}<h3>单词与词组 · 点击听美式发音</h3><div class="study-words">${selectedUnit.words.map(id=>{const w=WORDS[id];return `<button class="study-word" data-say-word="${esc(id)}"><strong>${esc(w.en)} 🔊</strong><span>${esc(w.ipa)}</span><small>${esc(w.zh)}</small></button>`;}).join('')}</div><h3>句式与用法 · ${selectedUnit.sentences.length} 条练习</h3>${selectedUnit.sentences.map((s,i)=>`<div class="study-sentence"><strong>${esc(s.en)}</strong><br>${esc(s.zh)}<br><small>${esc(s.tip)}</small><br><button class="listen-button" data-say-sentence="${i}">🔊 听句子</button></div>`).join('')}<h3>语法小练习 · ${selectedUnit.grammar.length} 题</h3>${selectedUnit.grammar.map((g,i)=>`<div class="study-grammar"><strong>${esc(g.prompt)}</strong>${g.context?`<p class="study-context">${esc(g.context)}</p>`:""}<div class="study-choices">${g.options.map((option,n)=>`<button class="secondary" data-study-grammar="${i}" data-study-option="${n}">${esc(option)}</button>`).join('')}</div><p class="study-explanation" hidden></p><button class="listen-button" data-say-grammar="${i}" hidden>🔊 听完整句子</button></div>`).join('')}<p class="source-note">${selectedUnit.textbookPages?'课本逐页内容按实物照片整理。':''}句式例句与练习自行编写。ˈ 为重音。${vocabularyStatus(selectedUnit)}；句式练习覆盖主要表达。</p>`;$('study').showModal();syncActivity();}
$('openStudy').onclick=openStudy;$('closeStudy').onclick=()=>{stopReading();$('study').close();};$('study').addEventListener('cancel',stopReading);
function currentTextbookPage(){return studyPages.find(p=>String(p.page)===$('textbookPage')?.value);}
$('studyContent').addEventListener('change',e=>{if(e.target.id==='textbookPage'){stopReading();$('textbookPageContent').innerHTML=textbookPage(currentTextbookPage(),esc);}});
$('studyContent').onclick=async e=>{
 const page=currentTextbookPage(),line=e.target.closest('[data-textbook-line]'),pageWord=e.target.closest('[data-textbook-word]');
 if(line&&page){const [b,i]=line.dataset.textbookLine.split(':').map(Number);speak(page.blocks[b].lines[i]);return;}
 if(pageWord&&page){const word=page.words.find(w=>w.id===pageWord.dataset.textbookWord);speak(word,word.id);return;}
 if(e.target.closest('#showBookPages')){stopReading();studyPages=selectedBook.textbookPages;e.target.closest('.textbook-section').outerHTML=textbookSection({textbookPages:studyPages},esc);return;}
 if(e.target.closest('#stopTextbookReading')){stopReading();return;}
 if(e.target.closest('#readTextbookPage')&&page){stopReading();const token=pageReadToken,button=$('readTextbookPage');button.textContent='🔊 正在朗读本页…';await reader.read(page.blocks.flatMap(b=>b.lines).filter(l=>/[A-Za-z0-9]/.test(l.en)));if(token===pageReadToken)button.textContent='🔊 朗读本页';return;}

 const word=e.target.closest('[data-say-word]');if(word)speak(WORDS[word.dataset.sayWord].en,word.dataset.sayWord);
 const sentence=e.target.closest('[data-say-sentence]');if(sentence)speak(selectedUnit.sentences[Number(sentence.dataset.saySentence)].en);
 const choice=e.target.closest('[data-study-grammar]');if(choice){const g=selectedUnit.grammar[Number(choice.dataset.studyGrammar)],card=choice.closest('.study-grammar'),right=g.options[Number(choice.dataset.studyOption)]===g.answer,feedback=card.querySelector('.study-explanation');feedback.textContent=`${right?'答对了！':'再看一下：'}${g.prompt.replaceAll('___',g.answer)} ${g.explanation}`;feedback.hidden=false;card.querySelector('[data-say-grammar]').hidden=false;}
 const grammar=e.target.closest('[data-say-grammar]');if(grammar){const g=selectedUnit.grammar[Number(grammar.dataset.sayGrammar)];speak(g.prompt.replaceAll('___',g.answer));}
};
const reader=new AudioReader({manifest:AUDIO,words:WORDS,baseURL:import.meta.url,onError:toast});let pageReadToken=0;
function stopReading(){pageReadToken++;reader.cancel();const button=$('readTextbookPage');if(button)button.textContent='🔊 朗读本页';}
function speak(text,wordId){stopReading();return reader.speak(text,wordId);}
$('listen').onclick=()=>{const q=currentQuestion();speak(q.say,q.wordId);};
$('reviewButton').onclick=()=>{if(!save.wrong.length){toast('还没有错题。先去英语探险吧！');return;}reviewMode=true;reviewIndex=0;roundId=crypto.randomUUID();questions=save.wrong.slice(-10).map(q=>({...q}));correct=0;roundWrong=[];showQuestion();};
function computeInput(){input.steer=(held.has('ArrowRight')||held.has('d')||touchRight?1:0)-(held.has('ArrowLeft')||held.has('a')||touchLeft?1:0);input.jump=held.has(' ')||held.has('ArrowUp')||held.has('w')||touchJump;}
addEventListener('keydown',e=>{if(view!=='play'||run?.status!=='playing')return;if(['ArrowLeft','ArrowRight','ArrowUp',' ','a','d','w'].includes(e.key)){e.preventDefault();held.add(e.key);computeInput();}else if(e.key==='Escape'||e.key==='p'){e.preventDefault();pause();}});addEventListener('keyup',e=>{held.delete(e.key);computeInput();});
function touchButton(id,set){const b=$(id);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);set(true);computeInput();});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>{set(false);computeInput();});}
touchButton('leftButton',v=>touchLeft=v);touchButton('rightButton',v=>touchRight=v);touchButton('jumpButton',v=>touchJump=v);
addEventListener('blur',()=>{resetInput();if(view==='play')pause();});document.addEventListener('visibilitychange',()=>{resetInput();if(document.hidden){hiddenPaused=!!run?.pause();checkpoint();stopReading();}else if(hiddenPaused){hiddenPaused=false;if(view==='play'&&!$('pauseDialog').open)$('pauseDialog').showModal();}});
addEventListener('pagehide',checkpoint);setInterval(()=>{if(view==='play')checkpoint();},1000);
let renderedRun=null,renderedStatus='',needsRender=true;
addEventListener('resize',()=>{scene?.resize();needsRender=true;});
function frame(time){syncActivity();const dt=Math.min(.05,Math.max(0,(time-lastFrame)/1000));lastFrame=time;
 if(view==='play'&&run){run.step(dt,input);if(run.status==='playing'||renderedRun!==run||renderedStatus!==run.status||needsRender){scene?.render(run,input,run.status==='playing'?dt:0);renderedRun=run;renderedStatus=run.status;needsRender=false;}updateHUD();if(run.status==='question'&&!$('quiz').open)showQuestion();if(run.status==='finished'&&!$('result').open)finish();}
 else if(view==='shop')scene?.render(null,{steer:0,jump:false},dt);
 requestAnimationFrame(frame);}
try{const selection=JSON.parse(localStorage.getItem(SELECTION_KEY));const book=BOOKS.find(b=>b.id===selection?.book);if(book){selectedBook=book;selectedUnit=book.units.find(u=>u.id===selection.unit)||book.units[0];}}catch{}
$('grade').value=selectedBook.grade;$('term').value=termLabel(selectedBook.term);const initialUnit=selectedUnit.id;updateBook();$('unit').value=initialUnit;updateSelection();updateCoins();renderSkins();requestAnimationFrame(frame);

let courseCloud;
const course=mountCourse({root:$('courseRoot'),onSave:payload=>courseCloud?.onSave(payload),onActivity:value=>{coursePlaying=value;syncActivity();},speak,read:lines=>reader.read(lines),stopAudio:stopReading,notice:toast,
 onReward:id=>{if(completeCard(save,`course:${id}`)){persist();toast('这课首次完成，+200金币！');}},
 openPages:(number,unitId)=>{stopReading();selectedBook=BOOKS.find(b=>b.id==='g3-upper');$('grade').value=3;$('term').value='上';updateBook();$('unit').value=unitId;updateSelection();openStudy();studyPages=selectedBook.textbookPages;const section=$('studyContent').querySelector('.textbook-section');section.outerHTML=textbookSection({textbookPages:studyPages},esc);$('textbookPage').value=String(number);$('textbookPage').dispatchEvent(new Event('change',{bubbles:true}));}
});

courseCloud=createCourseCloud({course,onState:()=>renderCloudState(),onAuthLoss:()=>{familyClearIdentity();familyUser=null;familyProfiles=[];renderFamily()}});
window.englishCourseCloud=courseCloud;

// Optional family learning: game coins and adventure reconnect state stay on this device.
const familyStyle=document.createElement('link');familyStyle.rel='stylesheet';familyStyle.href=new URL('../shared/family.css',import.meta.url).href;document.head.append(familyStyle);
const familyBar=document.createElement('section');familyBar.className='family-toolbar';familyBar.setAttribute('aria-label','英语学习档案');$('courseRoot').before(familyBar);
let familyUser=null,familyProfiles=[],familyLoading=false,familyImporting=false,familyEpoch=0;
function familyMessage(text){toast(text)}
function renderFamily(){const selected=courseCloud.profile?.id;familyBar.innerHTML=familyUser?`<label>学习档案 <select id="familyProfile" aria-label="选择孩子学习档案"><option value="">此设备的访客进度</option>${familyProfiles.map(p=>`<option value="${esc(p.id)}" ${selected===p.id?'selected':''}>${familyAvatars[p.avatar]||'🌱'} ${esc(p.nickname)}</option>`).join('')}</select></label><a href="/account.html">管理孩子档案 ↗</a>${selected?'<button id="familyImportOpen" class="family-button family-secondary">导入访客进度</button>':''}`:'<span>🌱 访客学习 · 进度保存在此设备</span><a href="/account.html">家长中心 · 多设备接着学 ↗</a>';familyBar.insertAdjacentHTML('beforeend','<span id="familySyncStatus" class="family-sync-status" role="status" aria-live="polite">此设备</span><div id="familyConflict" class="family-conflict" hidden></div><div id="familyImport" class="family-import" hidden></div>');renderCloudState()}
function renderCloudState(){const state=$('familySyncStatus');if(state)state.textContent=courseCloud.status;const panel=$('familyConflict');if(panel){panel.hidden=!courseCloud.conflict;if(courseCloud.conflict){const describe=progress=>{const session=progress.session,lesson=COURSE_LESSONS.find(l=>l.id===session?.lessonId);return session?`${lesson?.title||'英语小课'} · 第${session.index+1}步`:'课程首页（没有未完成的小课）'};panel.innerHTML=`<p><strong>另一台设备也更新了学习进度</strong><br>答题记录会一起保留。请选择这次从哪里继续。</p><p>此设备：${esc(describe(courseCloud.conflict.local))}<br>云端：${esc(describe(courseCloud.conflict.cloud))}</p><button class="family-button" data-conflict="local">从此设备继续</button><button class="family-button family-secondary" data-conflict="cloud">从云端继续</button>${(courseCloud.conflict.alternatives||[]).length>1?`<p>这台浏览器有几份未同步的小课。也可以选其中一份：</p>${courseCloud.conflict.alternatives.map((saved,index)=>`<button class="family-button family-secondary" data-conflict="local:${index}">记录${index+1}：${esc(describe(saved.data))}</button>`).join('')}`:''}`}}$('courseRoot').inert=familyLoading||familyImporting;const selector=$('familyProfile');if(selector)selector.disabled=familyLoading||familyImporting;const importButton=$('familyImportOpen');if(importButton)importButton.disabled=familyLoading||familyImporting;}
async function changeFamilyProfile(id){if(familyImporting)return;const token=++familyEpoch;familyLoading=true;renderCloudState();try{if(!id){familySelectProfile(familyUser.id,'');await courseCloud.logout()}else{const profile=familyProfiles.find(p=>p.id===id);if(!profile)return;familySelectProfile(familyUser.id,id);await courseCloud.select(familyUser.id,profile)}}catch(error){if(token!==familyEpoch)return;if(error.status===401||error.status===403){familyClearIdentity();familyUser=null;familyProfiles=[]}familyMessage(familyAccountError(error))}finally{if(token===familyEpoch){familyLoading=false;renderFamily();}}}
async function loadFamily(){const token=++familyEpoch;try{const status=await familyAPI.status();if(token!==familyEpoch)return;if(!status.enabled){familyLoading=false;return renderCloudState()}const session=await familyAPI.session();if(token!==familyEpoch)return;if(!session?.user?.emailVerified){familyClearIdentity();await courseCloud.logout();familyUser=null;familyProfiles=[];renderFamily();return}const profiles=(await familyAPI.profiles()).profiles;if(token!==familyEpoch)return;familyUser={id:session.user.id,email:session.user.email};familyProfiles=profiles;localStorage.setItem(familyVerifiedOwnerKey,JSON.stringify(familyUser));localStorage.setItem(`family-profiles-v1:${familyUser.id}`,JSON.stringify(familyProfiles));const selected=localStorage.getItem(familySelectedProfileKey(familyUser.id));const profile=selected===''?null:familyProfiles.find(p=>p.id===selected)||familyProfiles[0];if(profile)await changeFamilyProfile(profile.id);else{familyLoading=false;await courseCloud.logout();renderFamily();}}catch(error){if(token!==familyEpoch)return;if(!error.status){try{const cached=JSON.parse(localStorage.getItem(familyVerifiedOwnerKey));if(cached?.id){familyUser=cached;familyProfiles=JSON.parse(localStorage.getItem(`family-profiles-v1:${cached.id}`))||[];const id=localStorage.getItem(familySelectedProfileKey(cached.id));if(familyProfiles.some(p=>p.id===id))await changeFamilyProfile(id);else{familyLoading=false;renderFamily()}}else{familyLoading=false;renderCloudState()}}catch{familyLoading=false;renderCloudState()}}else{familyClearIdentity();await courseCloud.logout();familyUser=null;familyProfiles=[];renderFamily()}}}

familyBar.addEventListener('change',event=>{if(event.target.id==='familyProfile')changeFamilyProfile(event.target.value)});
familyBar.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;try{if(button.dataset.conflict){button.disabled=true;await courseCloud.resolveConflict(button.dataset.conflict);renderCloudState()}else if(button.id==='familyImportOpen'){let local;try{local=JSON.parse(localStorage.getItem('pearl-english-course-v1'))}catch{}const completed=Object.values(local?.lessons||{}).filter(l=>l.completed).length,hasSession=!!local?.session;const panel=$('familyImport');panel.hidden=false;panel.innerHTML=`<p><strong>把访客学习记录带给谁？</strong><br>此设备访客记录：已完成 ${completed} 节小课${hasSession?'，有一节进行中的小课':''}。<br>目标：${esc(courseCloud.profile.nickname)}。只能导入空档案，原来的访客记录会保留。</p><button id="familyImportConfirm" class="family-button">确认导入这个孩子</button><button id="familyImportCancel" class="family-button family-secondary">暂不导入</button>`}else if(button.id==='familyImportCancel')$('familyImport').hidden=true;else if(button.id==='familyImportConfirm'){button.disabled=true;familyImporting=true;renderCloudState();try{await courseCloud.importGuest();$('familyImport').hidden=true;familyMessage('访客进度已导入，原记录仍保留在此设备。')}finally{familyImporting=false;renderCloudState();if(familyUser){const selected=localStorage.getItem(familySelectedProfileKey(familyUser.id));if(selected!==courseCloud.profile?.id)changeFamilyProfile(selected||'')}}}}catch(error){familyMessage(error.message==='请先完成进度同步。'?error.message:familyAccountError(error));button.disabled=false}});
addEventListener('online',()=>{if(familyUser)courseCloud.flush();else loadFamily()});
addEventListener('pagehide',()=>{course.save();courseCloud.flush()});
addEventListener('storage',event=>{if(event.key===familyVerifiedOwnerKey){if(!event.newValue){familyEpoch++;familyLoading=false;familyImporting=false;courseCloud.logout();familyUser=null;familyProfiles=[];renderFamily()}else{try{const next=JSON.parse(event.newValue);if(next.id!==familyUser?.id){familyEpoch++;familyLoading=false;familyImporting=false;courseCloud.logout();familyUser=null;familyProfiles=[];renderFamily();loadFamily()}}catch{}}}else if(familyUser&&event.key===familySelectedProfileKey(familyUser.id)){if(!event.newValue)changeFamilyProfile('');else loadFamily()}});
addEventListener('family-logout',()=>{familyEpoch++;familyLoading=false;familyImporting=false;courseCloud.logout();familyUser=null;familyProfiles=[];renderFamily()});
renderFamily();loadFamily();
