const {origin}=require('../config.js');
const owners=new WeakMap();
const url=path=>path.startsWith('/english/')?origin+path:path;
function validResult(r){const score=n=>Number.isFinite(n)&&n>=0&&n<=100;return r?.engine==='local-phoneme'&&score(r.score)&&score(r.accuracy)&&score(r.completeness)&&r.duration>0&&r.duration<=20&&Array.isArray(r.words)&&r.words.length&&r.words.every(w=>typeof w.word==='string'&&w.word.trim()&&score(w.score))}
function createMedia(wx,{onState=()=>{}}={}){
 const state={playing:false,recording:false,requesting:false,assessing:false,clip:false,result:null,message:''};
 let epoch=0,playEpoch=0,dead=false,target=null,audio=null,file=null,task=null,capture=false,discard=false,recorder=null;
 const emit=()=>{if(!dead)onState({...state})};
 const unlink=path=>{if(path)wx.getFileSystemManager().unlink({filePath:path,fail(){}})};
 function stopAudio(){playEpoch++;if(audio){const old=audio;audio=null;old.stop();old.destroy()}state.playing=false;emit()}
 function play(paths){stopAudio();if(state.recording||state.requesting)return;const current=playEpoch,queue=paths.filter(Boolean);function next(){if(dead||current!==playEpoch)return;const path=queue.shift();if(!path){state.playing=false;emit();return}const player=wx.createInnerAudioContext();audio=player;player.src=url(path);player.onEnded(()=>{player.destroy();if(audio===player)audio=null;next()});player.onError(()=>{if(current!==playEpoch)return;stopAudio();state.message='这段声音暂时无法播放，请重试。';emit()});state.playing=true;emit();player.play()}next()}
 function detach(){if(!recorder)return;recorder.offStart(onStart);recorder.offStop(onStop);recorder.offError(onError)}
 function onStart(){if(!capture)return;if(dead||discard){recorder.stop();return}state.requesting=false;state.recording=true;state.message='正在录音，读完后点停止。最长20秒。';emit()}
 function onStop(result){if(!capture)return;capture=false;if(owners.get(recorder)===api)owners.delete(recorder);state.recording=false;state.requesting=false;if(dead||discard){unlink(result.tempFilePath)}else{unlink(file);file=result.tempFilePath;state.clip=!!file&&result.duration>=250;state.result=null;state.message=state.clip?'可以先回听，准备好了再提交练习反馈。':'录音太短，请读完后再停止。'}if(dead)detach();emit()}
 function onError(){if(!capture)return;capture=false;if(owners.get(recorder)===api)owners.delete(recorder);state.recording=false;state.requesting=false;state.message='录音未完成，请检查麦克风权限后重试。';if(dead)detach();emit()}
 const invoke=(name,options={})=>new Promise((resolve,reject)=>wx[name]({...options,success:resolve,fail:reject}));
 async function record(){if(dead||capture||state.requesting||state.assessing||target?.speakable===false)return;cancel();const current=epoch;state.requesting=true;state.message='请同意隐私说明并允许使用麦克风。';emit();try{if(!wx.requirePrivacyAuthorize)throw new Error('请更新微信后再录音。');await invoke('requirePrivacyAuthorize');if(dead||current!==epoch)return;await invoke('authorize',{scope:'scope.record'});if(dead||current!==epoch)return;if(!recorder){recorder=wx.getRecorderManager();recorder.onStart(onStart);recorder.onStop(onStop);recorder.onError(onError)}if(owners.has(recorder))throw new Error('上一次录音正在结束，请稍后重试。');owners.set(recorder,api);capture=true;discard=false;recorder.start({duration:20000,sampleRate:16000,numberOfChannels:1,encodeBitRate:48000,format:'wav'})}catch(error){if(current!==epoch||dead)return;state.requesting=false;state.message=error.message||'还未获得麦克风权限。可以继续听读，或在设置中允许麦克风。';emit()}}
 function stopRecord(){if(capture&&!discard){recorder.stop();state.message='正在结束录音…';emit()}}
 function cancel(){epoch++;task?.abort();task=null;stopAudio();if(capture){discard=true;recorder.stop()}unlink(file);file=null;Object.assign(state,{recording:false,requesting:false,assessing:false,clip:false,result:null,message:''});emit()}
 async function submit(){if(dead||!file||!state.clip||state.assessing||!target?.id)return;stopAudio();const current=++epoch,path=file,id=target.id;state.assessing=true;state.result=null;state.message='正在取得练习反馈…';emit();try{const data=await new Promise((resolve,reject)=>wx.getFileSystemManager().readFile({filePath:path,success:r=>resolve(r.data),fail:reject}));if(dead||current!==epoch)return;const result=await new Promise((resolve,reject)=>{task=wx.request({url:origin+'/api/miniprogram/pronunciation?target='+encodeURIComponent(id),method:'POST',data,header:{'Content-Type':'audio/wav'},timeout:90000,success:r=>r.statusCode===200?resolve(r.data):reject({status:r.statusCode}),fail:reject})});if(dead||current!==epoch)return;if(!validResult(result))throw new Error('反馈格式无效');state.result=result;state.message='这是本次跟读的练习反馈。'}catch(error){if(dead||current!==epoch)return;state.message=error.status===503?'评分服务尚未准备好，仍可录音和回听。':error.status===422?'这次没有听清，请靠近麦克风再读一次。':error.status===429?'请求较多，请稍后再提交。':'这次没有取得有效反馈，请稍后重试。'}finally{if(current===epoch&&!dead){task=null;state.assessing=false;emit()}}}
 const api={state,play,stopAudio,record,stopRecord,submit,cancel,replay:()=>file&&play([file]),setTarget(next){cancel();target=next},destroy(){cancel();dead=true;if(!capture)detach()}};return api;
}
module.exports={createMedia,validResult};
