import {createCourseCloud} from '../english/course-cloud.js';
import {familyAPI,escapeHTML as esc,avatars,selectedProfileKey,verifiedOwnerKey,selectProfile,clearFamilyIdentity,accountError,browserStorage} from '../shared/family-client.js';
export function mountFamily({course,root,notice}){
 const storage=browserStorage();let user=null,profiles=[],busy=false,epoch=0,cloud,resetting=false;
 cloud=createCourseCloud({subject:'chinese',course,storage,onState:()=>renderState(),onAuthLoss:()=>reset()});
 function render(){root.dataset.guest=String(!user);root.innerHTML=user?`<label>学习档案 <select id="familyProfile" aria-label="选择孩子学习档案"><option value="">此设备的访客进度</option>${profiles.map(p=>`<option value="${esc(p.id)}" ${cloud.profile?.id===p.id?'selected':''}>${avatars[p.avatar]||'🌱'} ${esc(p.nickname)}</option>`).join('')}</select></label><a href="/account.html">管理档案 ↗</a>${cloud.profile?'<button id="familyImportOpen">导入访客进度</button>':''}`:'<span>🌱 访客学习 · 进度保存在此设备</span>';root.insertAdjacentHTML('beforeend','<span id="familySyncStatus" role="status"></span><div id="familyConflict" hidden></div><div id="familyImport" hidden></div>');renderState();}
 function describe(p){const s=p?.session,l=course.lessons.find(l=>l.id===s?.lessonId);return s?`${l?.title||'小课'} · 第${s.index+1}步`:'课程首页';}
 function renderState(){if(!cloud)return;const status=root.querySelector('#familySyncStatus');if(status){status.textContent=cloud.status;status.hidden=!user;}course.root.inert=busy;const select=root.querySelector('select');if(select)select.disabled=busy;const panel=root.querySelector('#familyConflict');if(panel){panel.hidden=!cloud.conflict;if(cloud.conflict)panel.innerHTML=`<p>另一台设备也更新了进度。答题记录会保留，请选择从哪里继续。</p><p>此设备：${esc(describe(cloud.conflict.local))}<br>云端：${esc(describe(cloud.conflict.cloud))}</p><button data-conflict="local">从此设备继续</button><button data-conflict="cloud">从云端继续</button>${(cloud.conflict.alternatives||[]).map((p,i)=>`<button data-conflict="local:${i}">本机记录${i+1}：${esc(describe(p.data))}</button>`).join('')}`;}}
 async function change(id){const token=++epoch;busy=true;renderState();try{const p=profiles.find(p=>p.id===id);selectProfile(user.id,p?.id||'',storage);if(p)await cloud.select(user.id,p);else await cloud.logout();}catch(e){if(token===epoch){if(e.status===401||e.status===403)await reset();notice(accountError(e));}}finally{if(token===epoch){busy=false;render();}}}
 async function load(){const token=++epoch;try{const status=await familyAPI.status();if(token!==epoch)return;if(!status.enabled)return;const session=await familyAPI.session();if(token!==epoch)return;if(!session?.user?.emailVerified){await reset();return;}const result=await familyAPI.profiles();if(token!==epoch)return;user={id:session.user.id};profiles=result.profiles;storage.setItem(verifiedOwnerKey,JSON.stringify(user));storage.setItem(`family-profiles-v1:${user.id}`,JSON.stringify(profiles));const selected=storage.getItem(selectedProfileKey(user.id));await change(selected===''?'':profiles.find(p=>p.id===selected)?.id||profiles[0]?.id||'');}catch(e){if(token!==epoch)return;if(!e.status){try{const cached=JSON.parse(storage.getItem(verifiedOwnerKey));if(cached?.id){user=cached;profiles=JSON.parse(storage.getItem(`family-profiles-v1:${user.id}`))||[];await change(storage.getItem(selectedProfileKey(user.id))||'');}}catch{notice('暂时离线，访客进度保存在此设备。');}}else if(e.status===401||e.status===403)await reset();else notice(accountError(e));}}
 async function reset(){
  // clearFamilyIdentity emits family-logout synchronously; do not re-enter this reset.
  if(resetting)return;
  resetting=true;epoch++;busy=false;user=null;profiles=[];
  try{clearFamilyIdentity(storage);await cloud.logout();render();}
  finally{resetting=false;}
 }
 root.addEventListener('change',e=>{if(e.target.id==='familyProfile'&&!busy)change(e.target.value);});
 root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||busy)return;try{if(b.dataset.conflict){busy=true;renderState();await cloud.resolveConflict(b.dataset.conflict);}else if(b.id==='familyImportOpen'){const raw=JSON.parse(storage.getItem('pearl-chinese-course-v1')||'null');root.querySelector('#familyImport').hidden=false;root.querySelector('#familyImport').innerHTML=`<p>把此设备的语文访客记录导入「${esc(cloud.profile.nickname)}」？已完成 ${Object.values(raw?.lessons||{}).filter(l=>l.completed).length} 课${raw?.session?'，有进行中的小课':''}。只能导入该孩子的空语文进度，访客原记录会保留。</p><button id="familyImportConfirm">确认导入这个孩子</button><button id="familyImportCancel">暂不导入</button>`;}else if(b.id==='familyImportCancel')root.querySelector('#familyImport').hidden=true;else if(b.id==='familyImportConfirm'){busy=true;renderState();await cloud.importGuest();render();notice('语文访客进度已导入，原记录仍保留。');}}catch(e){notice(accountError(e));}finally{busy=false;renderState();}});
 addEventListener('pagehide',()=>{course.save();cloud.flush();});addEventListener('online',()=>user?cloud.flush():load());addEventListener('family-logout',reset);addEventListener('storage',e=>{if(e.key===verifiedOwnerKey){if(!e.newValue)reset();else load();}else if(user&&e.key===selectedProfileKey(user.id))change(e.newValue||'');});render();load();return cloud;
}
