const {answerMatches}=require('../../lib/core.js');
const {createMedia}=require('../../lib/media.js');
const {mediaHandlers,mediaItem}=require('../../lib/view.js');
const locked=media=>!!(media.recording||media.requesting||media.assessing||(media.clip&&!media.result));
const pageChoices=Array.from({length:90},(_,index)=>'第 '+(index+2)+' 页');
function readingGroups(page){
 const groups=[];
 const wordsIn=blocks=>new Set(blocks.flatMap(b=>b.lines.flatMap(l=>(l.en.toLowerCase().match(/[a-z]+(?:['’-][a-z]+)*/g)||[]))));
 const heading=wordsIn(page.blocks.filter(b=>b.kind==='heading')),body=wordsIn(page.blocks.filter(b=>b.kind!=='heading'));
 const support=word=>word.id.startsWith('photo-')&&heading.has(word.en.toLowerCase())&&!body.has(word.en.toLowerCase());
 const add=(title,lines,wordGroup,tip,supportWords=false)=>{for(let offset=0;offset<lines.length;offset+=6)groups.push({title:title+(lines.length>6?' · '+(Math.floor(offset/6)+1):''),lines:lines.slice(offset,offset+6),wordGroup,tip:tip||'',supportWords})};
 add('本页词句 · 单词',page.words.filter(w=>!support(w)),true);
 for(const block of page.blocks){if(block.lines.length)add(block.title,block.lines,false,block.tip);else groups.push({...block,wordGroup:false,supportWords:false})}
 add('栏目用词',page.words.filter(support),true,'来自本页标题的用词，也可以听读。',true);
 return groups;
}
Page({...mediaHandlers(wx),data:{loading:true,error:'',page:null,tab:'read',media:{},mediaLocked:false,speakingTarget:null,speakingTargets:[],speakingIndex:0,pageChoices,pagePickerIndex:0,readingGroups:[],allReadingGroups:[],supportWordCount:0,showSupportWords:false,readingGroup:null,readingGroupIndex:0,questions:[],question:null,questionIndex:0,roundNumber:1,roundCount:1,feedback:null,tokens:[],picked:[],practiceFinished:false},
 onLoad(options){this.pageNumber=Math.max(2,Math.min(91,Math.floor(Number(options.page)||2)));this.client=getApp().client;this.media=createMedia(wx,{onState:media=>this.setData({media,mediaLocked:locked(media)})});this.loadEpoch=0;this.load()},
 onShow(){this.refreshEncouragementSound();const wasHidden=this.hidden;this.hidden=false;if(this.identity!==this.client.identity||(wasHidden&&this.data.loading))this.load()},
 async load(){this.resetEncouragement();this.identity=this.client.identity;const epoch=++this.loadEpoch;this.media.cancel();this.setData({loading:true,error:'',speakingTarget:null,question:null});try{const source=await this.client.content('pages/'+this.pageNumber+'.json');if(this.hidden||epoch!==this.loadEpoch)return;this.targets=source.targets;this.allQuestions=source.questions;this.history=this.client.pageHistory(source.page);this.attempted=new Set();this.picked=[];const practiceIds=new Set(source.questions.map(q=>q.targetId));const itemView=item=>({...mediaItem(item),hasPractice:practiceIds.has(item.targetId)});const page={...source,words:source.words.map(itemView),blocks:source.blocks.map(b=>({...b,lines:(b.lines||[]).map(itemView)}))};const allGroups=readingGroups(page),groups=allGroups.filter(g=>!g.supportWords),speakingTargets=this.targets.filter(t=>t.audio&&t.speakable!==false);const cursor=this.client.pageCursor(source.page);const validCursor=Number.isInteger(cursor?.roundStart)&&cursor.roundStart>=0&&cursor.roundStart<this.allQuestions.length&&cursor.roundStart%6===0&&Number.isInteger(cursor.questionIndex)&&cursor.questionIndex>=0&&cursor.questionIndex<=Math.min(6,this.allQuestions.length-cursor.roundStart);this.roundStart=validCursor?cursor.roundStart:0;this.retryQuestionId=validCursor&&cursor.retry===true?this.allQuestions[this.roundStart+cursor.questionIndex]?.id:null;this.setData({loading:false,page,pagePickerIndex:source.page-2,readingGroups:groups,allReadingGroups:allGroups,supportWordCount:allGroups.filter(g=>g.supportWords).reduce((count,g)=>count+g.lines.length,0),showSupportWords:false,readingGroup:groups[0]||null,readingGroupIndex:0,speakingTargets,speakingIndex:0,practiceFinished:false});this.startRound({questionIndex:validCursor?cursor.questionIndex:0,save:false});if(this.data.tab==='speak'&&speakingTargets.length)this.selectTarget(0)}catch(error){if(epoch===this.loadEpoch)this.setData({loading:false,error:error.message})}},
 canNavigate(){return !this.data.loading&&!locked(this.data.media)},
 scrollStart(){wx.pageScrollTo({scrollTop:0,duration:0})},
 switchTab(e){if(!this.canNavigate())return;const tab=e.currentTarget.dataset.tab;if(!['read','practice','speak'].includes(tab))return;this.media.cancel();this.setData({tab});if(tab==='speak'&&!this.data.speakingTarget&&this.data.speakingTargets.length)this.selectTarget(0);this.scrollStart()},
 readPage(){if(!this.canNavigate())return;this.media.toggleAudio([...(this.data.page.words||[]),...this.data.page.blocks.flatMap(b=>b.lines)].filter(t=>t.speakable!==false).map(t=>t.audio),'page')},
 readGroup(){if(!this.canNavigate())return;this.media.toggleAudio((this.data.readingGroup?.lines||[]).filter(t=>t.speakable!==false).map(t=>t.audio),'group')},
 toggleSupportWords(){if(!this.canNavigate())return;const showSupportWords=!this.data.showSupportWords,groups=this.data.allReadingGroups.filter(g=>showSupportWords||!g.supportWords);const index=Math.max(0,groups.findIndex(g=>g.title===this.data.readingGroup?.title));this.setData({showSupportWords,readingGroups:groups,readingGroupIndex:index,readingGroup:groups[index]||null})},
 selectReadingGroup(e){this.setReadingGroup(Number(e.detail.value))},
 adjacentReadingGroup(e){this.setReadingGroup(this.data.readingGroupIndex+Number(e.currentTarget.dataset.delta))},
 setReadingGroup(index){if(!this.canNavigate()||!this.data.readingGroups[index])return;this.media.cancel();this.setData({readingGroupIndex:index,readingGroup:this.data.readingGroups[index]});this.scrollStart()},
 selectTarget(index){if(!this.canNavigate())return;const target=this.data.speakingTargets[index];if(!target)return;this.media.setTarget(target);this.setData({speakingTarget:target,speakingIndex:index})},
 chooseTarget(e){this.selectTarget(this.data.speakingTargets.findIndex(t=>t.id===e.currentTarget.dataset.id))},
 selectSpeakingTarget(e){this.selectTarget(Number(e.detail.value))},
 adjacentTarget(e){this.selectTarget(this.data.speakingIndex+Number(e.currentTarget.dataset.delta));if(this.canNavigate())this.scrollStart()},
 chooseAndSpeak(e){if(!this.canNavigate())return;this.chooseTarget(e);if(this.data.speakingTarget){this.setData({tab:'speak'});this.scrollStart()}},
 practiceTarget(e){if(!this.canNavigate())return;const index=this.allQuestions.findIndex(q=>q.targetId===e.currentTarget.dataset.id);if(index<0)return;this.media.cancel();this.roundStart=Math.floor(index/6)*6;this.attempted=new Set();this.retryQuestionId=null;this.resetEncouragement();this.retryQuestionId=null;this.setData({tab:'practice'});this.startRound({questionIndex:index-this.roundStart});this.scrollStart()},
 listenTarget(e){if(!this.canNavigate())return;const target=this.targets.find(t=>t.id===e.currentTarget.dataset.id);if(target?.audio&&target.speakable!==false)this.media.toggleAudio([target.audio],target.id)},
 saveCursor(){if(this.identity===this.client.identity)this.client.savePageCursor(this.pageNumber,{roundStart:this.roundStart,questionIndex:this.questionIndex,...(this.retryQuestionId===this.questions[this.questionIndex]?.id?{retry:true}:{})})},
 startRound({questionIndex=0,save=true}={}){this.questions=this.allQuestions.slice(this.roundStart,this.roundStart+6);this.questionIndex=questionIndex;this.setData({questions:this.questions,roundNumber:Math.floor(this.roundStart/6)+1,roundCount:Math.max(1,Math.ceil(this.allQuestions.length/6))});this.showQuestion();if(save)this.saveCursor()},
 showQuestion(){this.media.cancel();const question=this.questions[this.questionIndex];this.picked=[];this.setData({question:question||null,questionIndex:this.questionIndex+1,feedback:null,picked:[],tokens:(question?.tokens||[]).map((text,i)=>({text,index:i,selected:false})),practiceFinished:!question})},
 listenQuestion(){if(!this.canNavigate())return;const target=this.targets.find(t=>t.id===this.data.question?.targetId);if(target?.audio)this.media.toggleAudio([target.audio],'question')},
 answer(e){this.submitAnswer(e.currentTarget.dataset.answer)},
 submitAnswer(answer){if(this.identity!==this.client.identity)return this.load();if(!this.canNavigate())return;const q=this.data.question;if(!q||this.data.feedback?.correct)return;const correct=answerMatches(q,answer),firstTry=this.retryQuestionId!==q.id;if(!correct)this.retryQuestionId=q.id;if(!this.attempted)this.attempted=new Set();if(!this.attempted.has(q.id)){const old=this.history[q.id]||{attempts:0,correct:0};this.history[q.id]={attempts:old.attempts+1,correct:old.correct+(correct?1:0),lastAt:Date.now()};this.client.savePageHistory(this.pageNumber,this.history);this.attempted.add(q.id)}this.setData({feedback:{correct,selected:answer,text:correct?'答对了！':'再听一遍，再试一次。'}});this.saveCursor();this.encourageAnswer(q.id,correct,firstTry)},
 pick(e){if(!this.canNavigate())return;const index=Number(e.currentTarget.dataset.index);if(this.picked.includes(index)||this.data.feedback?.correct)return;this.picked.push(index);this.showTokens()},
 removeToken(e){if(!this.canNavigate()||this.data.feedback?.correct)return;this.picked.splice(Number(e.currentTarget.dataset.index),1);this.showTokens()},
 showTokens(){this.setData({picked:this.picked.map((n,i)=>({text:this.data.question.tokens[n],position:i})),tokens:this.data.question.tokens.map((text,i)=>({text,index:i,selected:this.picked.includes(i)})),feedback:null})},
 checkSentence(){if(this.picked.length===this.data.question.tokens.length)this.submitAnswer(this.picked.map(i=>this.data.question.tokens[i]).join(' '))},
 nextQuestion(){if(!this.canNavigate()||!this.data.feedback?.correct)return;this.questionIndex++;this.showQuestion();this.saveCursor();if(this.data.practiceFinished)this.encourageComplete('page-'+this.pageNumber+'-'+this.roundStart);this.scrollStart()},
 restartPractice(){if(!this.canNavigate())return;this.attempted=new Set();this.retryQuestionId=null;this.resetEncouragement();this.roundStart+=this.questions.length;if(this.roundStart>=this.allQuestions.length)this.roundStart=0;this.startRound();this.scrollStart()},
 changePage(e){this.goToPage(this.pageNumber+Number(e.currentTarget.dataset.delta))},
 selectPage(e){this.goToPage(Number(e.detail.value)+2)},
 goToPage(number){if(!this.canNavigate()||number<2||number>91||number===this.pageNumber)return;this.pageNumber=number;this.attempted=new Set();this.load();this.scrollStart()}
});
